### ISSUE TITLE
Support for RFC2069 HTTP digest (for WGET)

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#187]
_Original author: ukawu...@gmail.com (July 25, 2011 20:32:32)_

I'm trying to download a ICS-File(ICS-Plugin with option &quot;?export&quot;) from my CalDAV-Server with the standard WGET-Tool and it doesn't work. I have no other problems with the server and the same URL is working with IE, FF and my own written WGET-Tool without any problems.

It seems, that SabreDAV v1.4.4 is a little bit unhappy with the response challenge from WGET ;-). I played a little bit with a network sniffer and I'missing some (more unimportant) parameters in the challenge of the standard WGET tool.

Hope it helps ...

_Original issue: http://code.google.com/p/sabredav/issues/detail?id=134_

**Comment by Hywan** [comment]
Still needed?

**Comment by evert** [comment]
I don't think this is still needed. Nice for completeness but almost nobody actually uses it :/
