### ISSUE TITLE
warning on getQuotaInfo (lib\Sabre\DAV\FS\Directory)

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#193]
_Original author: kingd...@gmail.com (February 27, 2009 16:17:44)_

<b>What steps will reproduce the problem?</b>
1. i tested the getting started sample on windowsxp-apache (xampp) with ie6
2. webDAV access failed, http-request responses with 3 Warnings: 
disk_total_space() [..] Das System kann den angegebenen Pfad nicht finden. 
(translated: File/path not found) lib\Sabre\DAV\FS\Directory.php on line 
101
(same warning for disk_free_space() 2 times, line 101, 102)
3. if i comment out the body of the function, webDAV access successes

<b>What is the expected output? What do you see instead?</b>
no warnings!

Hint / proposal: use the functions with real paths
 -&gt; disk_total_space(realpath($this-&gt;path))
or save the configured path in the object as a real path?

Kind Regards

Carsten

_Original issue: http://code.google.com/p/sabredav/issues/detail?id=4_

**Comment by KuenzelIT** [comment]
You talked about this quite a while ago, and I have the same problem now. With "realpath" its working fine. It seems disk_total_space needs an absolute path to work.

**Comment by Cruiser13** [comment]
+1 with this issue. Using realpath works for me.
