### ISSUE TITLE
PDO Locks backend use UNSIGNED INT

### ISSUE THREAD

**Issue by vaclavvanik** [fruux/sabre-dav#350]
In PDO auth backend on line 64 in WHERE clasule is this condition:

```sql
((created + timeout) > CAST(? AS UNSIGNED INTEGER))
```

I recommend to change to:

```sql
(created > (? - timeout))
```

- CAST to INT is unnecessary, because bind parameter is INT
- UNSIGNED INT is mysql specific
- this condition cannot use index

**Comment by TCKnet** [comment]
The exact same problem also affects vendor/sabre/dav/lib/DAV/Locks/Backend/PDO.php:62
of version 3.0.1. Thanks for taking care of it.

In the mean time, just patch your file with

    sed 's/((created + timeout) > CAST(\? AS UNSIGNED INTEGER))/(created > (? - timeout))/g' \
        vendor/sabre/dav/lib/DAV/Locks/Backend/PDO.php > tmp
    mv tmp vendor/sabre/dav/lib/DAV/Locks/Backend/PDO.php

**Comment by evert** [comment]
This was fixed here: https://github.com/fruux/sabre-dav/issues/699
