### ISSUE TITLE
support offset/size parameters to ::get() and drop stream_copy_to_stream in httpget?

### ISSUE THREAD

**Issue by VRciF** [fruux/sabre-dav#457]
Hi,
i'm implementing a virtual file system using \FSExt\File und thus i provide the get() method which shall return either a file resource or the requested content string.
now my problem is that the requested file is not hosted locally, so i need to grab the given file by myself from a remote host using a custom api. but since i dont have offset and size given, i need to query the whole file and provide just the slice requested by the dav client. in my case this is a pretty overhead cause of big files.

so i would kindly like to ask for the following changes:
* add $offset=0,$size=0 parameters for get() calls so one can provide the parts needed
* in server.php in function httpGet the function stream_copy_to_stream is used on a temporary php://temp because a few lines below httpResponse->sendBody() doesnt handle parts of the body - a simple solution would be to just change sendBody($body) to sendBody($body, $size=0) and just send $size bytes if greater zero

i could provide the code changes if above modifications get approved or any other thoughts on how to handle this?
thx

**Comment by evert** [comment]
No feedback
