### ISSUE TITLE
scheduling : issue with local delivery

### ISSUE THREAD

**Issue by ma2thieu** [fruux/sabre-dav#581]
I can't get local delivery to work with scheduling, if the 2 users (attendant and organizer) are on the same server the invitation is still sent by email.

When I look at `$iTipMessage->recipient` in [scheduleLocalDelivery](https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Schedule/Plugin.php#L366) there is a `mailto:` in front of the email address and the function returns because it can't find the principal.

**Comment by evert** [comment]
Fixed in #604
