### ISSUE TITLE
How to disable windows cache

### ISSUE THREAD

**Issue by misterx** [fruux/sabre-dav#585]
I try to use next code
```php
namespace Sabre;
$root = new DAV\SimpleCollection('root',array(
	new DAV\SimpleFile('date.txt',date('c')),
));

$server = new DAV\Server($root);
$server->exec();
```
When i try to read this file from windows network drive (Windows 7), i has the same content in 60 seconds. But i want real dynamic content in this case with timestamp. I think this is problem in windows cache. Can i do something  from server-side?

**Comment by evert** [comment]
Lets add this to sabre.io. @misterx, I don't think this is fixable server-side.
