### ISSUE TITLE
SCHEDULE-STATUS should not contain an explanatory text

### ISSUE THREAD

**Issue by kewisch** [fruux/sabre-dav#586]
I was looking at the `IMipPlugin` sabredav provides and was wondering about the `scheduleStatus` values being set in the `Itip\Message`. Reading through http://tools.ietf.org/html/rfc6638#section-7.3 it looks like there is no room for explanatory text and it should instead be a list of statcodes.

I haven't checked what scheduling emails actually look like so I may be wrong here, but I think its a bug.

Another trivial issue you might want to just piggyback here, `$server` is defined as a class variable, but the `initialize` function does not set it.

**Comment by evert** [comment]
Thanks!

I wonder where I got the reason phrase from... I couldn't just have made that up I feel :P

**Comment by Hywan** [comment]
Re-open the issue because it is partly fixed.

**Comment by evert** [comment]
@Hywan what did I miss?

**Comment by Hywan** [comment]
@evert The description of this PR raises 2 issues:
1. `scheduleStatus` does not contain the right information,
2. an unsed variable.

#588 addressed 2. So 1 is still opened. Nop?

**Comment by evert** [comment]
You may have missed b16493c =)

**Comment by evert** [comment]
Going to assume that @Hywan overlooked that commit. Reopen and elaborate if I was wrong.

**Comment by Hywan** [comment]
@evert Yup, I missed b16493c, because you didn't make a PR :-D!
