### ISSUE TITLE
Schedule plugin shouldn't assume owner is user when detecting attendee/organizer

### ISSUE THREAD

**Issue by kewisch** [fruux/sabre-dav#587]
The way we have sabredav set up, we have principals for group calendars and users. Each group member is attendee on events in the group calendar. I've now enabled the IMipPlugin, but emails are not being sent. I've tracked this down to [Sabre\CalDAV\Schedule\Plugin:283](https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Schedule/Plugin.php#L283) where the addresses for the owner principal are retrieved.

If I change this to use the addresses of the current user principal instead, the organizer/attendee is detected correctly and mails are sent. Does this change make sense, or would that break some other logic?

**Comment by kewisch** [comment]
Yes, the calendar is owned by a principal, that the current user is a member of. 

`processICalendarChange` needs "list of addresses needs to be specified, so the system knows who made the update". In the case where the owner principal is not an individual, the user-address-set won't help at all.

If you say current-user-principal is not the right thing, I'm not quite sure what is left. The `ORGANIZER` is set correctly, but that still doesn't give us a new actor that would be making the change. Do we have anything else aside from the owner and current user that we could use at that point?

I was thinking we could check if the owner principal has cal:calendar-user-type == INDIVIDUAL and only use the addresses in that case. But we can't just check the other group members in the != case, what if one group member is acting on behalf of another group member?

Maybe we need to introduce some sort of header to identify the principal the current user is acting on behalf of in the delegation case, and fall back to the current user principal if the header is not present.

I'll bring this to the mailing list in the next few days and settle with a hack to move forward.

**Comment by evert** [comment]
Well.. just hypothetically... if the calendar is owned by `principals/groups/sales`, you could just use that for the `ORGANIZER`:

    ORGANIZER:http://server/principals/groups/sales

Or provide some kind of address for the sales group (`mailto:sales@example.org`), or make up a new type of URI, as long as it matches `calendar-user-address-set` for the owner of the calendar.

I think in the context of scheduling, if the group owns calendars, it can (or perhaps _should_) have a `calendar-user-address-set`. For scheduling purposes the group here acts as a calendar-user.

**Comment by kewisch** [comment]
If I change the `ORGANIZER` to be one of the things in the calendar-user-address-set of the group calendar (which in sabredav is currently just the principal uri), then any change made by a member of the group will look like the organizer made the change, because per above linked code it will look up the owner, get the address set and then compare that with the organizer.

**Comment by evert** [comment]
I'm starting to understand the issue. This is actually related to discussions that are currently going on in TC-SHARING. http://lists.calconnect.org/pipermail/tc-sharing-l/2014-December/000044.html

There's multiple ways to address this issue, but so far there's basically been no conclusions.

In sabredav's case, so far we assume that scheduling operations in a shared calendar are always on behalf of the owner of the calendar. I know other servers (the Darwin one at least I think) simply does not allow scheduling in shared calendars.

Would it be possible for your caldav backend to just return the shared calendars as if they are not shared, so always owned by the user that owns the calendar-home-set?

Then these calendars just behave like regular calendars, but with a shared data-store.

**Comment by kewisch** [comment]
Modifying the caldav backend to make them seem like they are not shared is an interesting idea, its worth an experiment when I have some time to kill. It might even make some things easier. Closing the question for now, thanks for the input and suggestions.

Unfortunately I won't be at the next calconnect, but I hope to see you again some time soon :-)
