### ISSUE TITLE
Realm option not honored when passed through Auth\Plugin

### ISSUE THREAD

**Issue by massar** [fruux/sabre-dav#590]
This is likely a regression in the current git edition, likely because of changes in the auth code.

As per:
 http://sabre.io/dav/authentication/
one would use:
```
 $authBackend = new Auth\Backend\PDO($pdo);
 $authPlugin = new Auth\Plugin($authBackend, "somethingelse");
```
But it seems the latter realm change is not taken and the standard "SabreDAV" realm is presented.

Adding a:
```
$authBackend->setRealm("somethingelse");
```

resolves it and one does not get the standard "SabreDAV" realm but the "somethingelse" realm.

**Comment by evert** [comment]
This API will indeed change, but has not been documented yet.

**Comment by massar** [comment]
Well, that is why the stuff in git is beta eh ;)

This ticket will at least let people google for it, till that has been resolved/documented.

**Comment by evert** [comment]
Yea for sure =) if you want stable and documented, definitely use the 2.1 branch, but testing the master branch is definitely appreciated as well.

**Comment by massar** [comment]
With only a few users on my private instance (but enough to notice issues), a 'git pull' is easy enough, and also to revert if really needed. In the end a better SabreDAV is a greater SabreDAV :)

**Comment by evert** [comment]
Closing this, as we now have a sabre.io ticket for this.

**Comment by jobo** [comment]
Version 3 is released now, and suddenly all your user password hashes are broken if you generated them against a different realm than the default one.

The easy fix is to hard code your realm inside the auth backend plugin, as referenced above. The only alternative is to crack all passwords and generate new hashes.

This should definitively go into the documentation, and prominently displayed on upgrading. I can't seem to find the referenced sabre.io ticket but the discussion should probably continue there.
