### ISSUE TITLE
iCalendar files are generated with CR instead of CRLF line breaks

### ISSUE THREAD

**Issue by rfc2822** [fruux/sabre-dav#591]
Is it possible that SabreDav generates multi-line content like this:

```
DESCRIPTION:this is a<CR>
  very long line
```

instead of

```
DESCRIPTION:this is a<CR><LF>
  very long line
```

I couldn't test it myself, but people are reporting parsing errors from SabreDav servers and it seems that is the reason. According to [RFC 2445](http://tools.ietf.org/html/rfc2445#section-4.1), "a long line can be split between any two characters by inserting a CRLF immediately followed by a single linear white space character (i.e., SPACE, US-ASCII decimal 32 or HTAB, US-ASCII decimal 9)".

**Comment by evert** [comment]
Not that I'm aware of.

This is the serialization code for iCalendar properties:

https://github.com/fruux/sabre-vobject/blob/3.3/lib/Property.php#L231
