### ISSUE TITLE
Support empty password in basic auth

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#596]
See https://github.com/owncloud/core/issues/13398

Applies to 1.8 branch

**Comment by evert** [comment]
Not a bug in sabre/http, so only 1.8 needs to be fixed.

**Comment by evert** [comment]
See commit 49104623ae10caf58649a93f25de6b098de60f0f, which got an incorrect ticket id associated with it.

**Comment by Hywan** [comment]
:+1:!
