### ISSUE TITLE
MKCALENDAR broken

### ISSUE THREAD

**Issue by untitaker** [fruux/sabre-dav#603]
The [WebDAV RFC](http://tools.ietf.org/html/rfc4918#section-9.3):

    When MKCOL is invoked without a request body, the newly created collection
    SHOULD have no members.

However, SabreDAV seems to explicitly forbid such requests:

* When sending an MKCOL without request body, ownCloud 8 reports:

        MKCOL http://127.0.0.1:8080/remote.php/caldav/calendars/asdf/test
        {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
        None
        Sending request...
        403
        {'x-xss-protection': '1; mode=block', 'content-security-policy': "default-src 'self'; script-src 'self' 'unsafe-
        eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *", 'x
        -content-type-options': 'nosniff', 'x-powered-by': 'PHP/5.6.5', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'connection
        ': 'close', 'host': '127.0.0.1:8080', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post
        -check=0, pre-check=0', 'x-frame-options': 'Sameorigin', 'content-type': 'application/xml; charset=utf-8', 'x-robots-ta
        g': 'none'}
        <?xml version="1.0" encoding="utf-8"?>
        <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
          <s:exception>Sabre\DAV\Exception\InvalidResourceType</s:exception>
          <s:message>You can only create calendars in this collection</s:message>
          <s:sabredav-version>1.8.12</s:sabredav-version>
          <d:valid-resourcetype/>
        </d:error>

* So I supposed that MKCOLs are not allowed on calendar resources. Oh well, let's try MKCALENDAR:

        MKCALENDAR http://127.0.0.1:8080/remote.php/caldav/calendars/asdf/test
        {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
        <?xml version="1.0" encoding="utf-8" ?>
                <C:mkcalendar xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
                 <D:set>
                   <D:prop>
                   </D:prop>
                 </D:set>
               </C:mkcalendar>
        debug:
        Sending request...
        415
        {'x-xss-protection': '1; mode=block', 'content-security-policy': "default-src 'self'; script-src
        'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; m
        edia-src *; connect-src *", 'x-content-type-options': 'nosniff', 'x-powered-by': 'PHP/5.6.5', 'expires':
         'Thu, 19 Nov 1981 08:52:00 GMT', 'connection': 'close', 'host': '127.0.0.1:8080', 'pragma': 'no-cache',
          'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'x-frame-options': '
          Sameorigin', 'content-type': 'application/xml; charset=utf-8', 'x-robots-tag': 'none'}
          <?xml version="1.0" encoding="utf-8"?>
          <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
            <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
            <s:message>The request body for the MKCOL request must be a {DAV:}mkcol request construct.</s:m
          essage>
            <s:sabredav-version>1.8.12</s:sabredav-version>
          </d:error>

At this point I started suspecting that there is indeed a bug in SabreDAV (or
ownCloud, or both), and not just me reading the RFCs badly, because it can't
differentiate between the request methods made.

* SabreDAV confuses MKCALENDAR with MKCOL (or simply doesn't support MKCALENDAR)

* SabreDAV requires a request body for MKCOL. I am not sure if this is a bug
  that SabreDAV requires me to specify a content type, however it would be nice
  if I were able to just issue an empty MKCOL to the wanted endpoint and let
  SabreDAV infer the content type (if it has that information from ownCloud).

**Comment by evert** [comment]
Hi!

I need to look at the MKCALENDAR issue. That _should_ work. We don't intend to fix the MKCOL issue though. The resourcetype cannot easily be inferred from context. A calendar-home may have a notifications collection, inbox, outbox, subscriptions and calendars.

An empty MKCOL maps to creating a plain collection, which is not allowed there.

**Comment by untitaker** [comment]
I see, thanks.

**Comment by untitaker** [comment]
Thinking more about this:

>A calendar-home may have a notifications collection, inbox, outbox, subscriptions and calendars.

But can the user create more than one of any other collection type than a calendar?

**Comment by evert** [comment]
Yes, a subscription :) But a more important reason is this: if I allow this and people start relying on this feature, they may make the assumption it will work on other caldav servers.

There's some benefit in being a bit strict when it comes to stuff like this.

**Comment by untitaker** [comment]
Oh I didn't intend to request a nonstandard extension. My current understanding is that this is a grey area, so yeah, I suppose it would be made useless through that anyway.

**Comment by evert** [comment]
I betcha that there's servers out there that allow you to create regular collections in the calendar-home. CalDAV actually allows for this to create deeper a calendar organization than just 1-level.

**Comment by untitaker** [comment]
Yeah, FastMail does this, which used to be the only server where I actually tested this. Oh and I think iCloud too.

**Comment by untitaker** [comment]
@evert Have you had a look at the MKCALENDAR issue?

**Comment by evert** [comment]
No.. I thought that this ticket was only about the MKCOL issue and I had forgotten about the other one.

**Comment by evert** [comment]
Ok so this:

```
curl -i -H "Content-Type: application/xml" -X MKCALENDAR --digest --user admin:admin http://localhost/~evert/sabre/dav/groupwareserver.php/calendars/admin/testcalendar3/
-d '<C:mkcalendar xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
         <D:set>
           <D:prop>
           </D:prop>
         </D:set>
       </C:mkcalendar>'
```

Works for me... Can you alter that statement so I can reproduce the problem?

**Comment by untitaker** [comment]
Hmm, sorry, I probably should have said that I am reproducing this with latest ownCloud. I'll try to reproduce it with SabreDAV from master when I have the time.

**Comment by evert** [comment]
I tested this with the latest stable sabredav (2.1.3)

**Comment by untitaker** [comment]
This is probably fixed with SabreDAV 2.1.3, which doesn't even have the error message I showed above.

Unfortunately I wasn't able to set up a barebones SabreDAV server, @evert if you have time, could you test your above request against 1.8?

Also your testcase is curiously missing the XML header `<?xml ... ?>`.

**Comment by evert** [comment]
Hi!

I just tested that:

```
$ curl -i -H "Content-Type: application/xml" -X MKCALENDAR --digest --user admin:admin http://localhost/~evert/sabre/dav/server.php/calendars/admin/testcalendar17/ -d '<C:mkcalendar xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
>          <D:set>
>            <D:prop>
>            </D:prop>
>          </D:set>
       </C:mkcalendar>'>        </C:mkcalendar>'
HTTP/1.1 401 Unauthorized
Date: Mon, 18 May 2015 13:24:25 GMT
Server: Apache/2.4.10 (Unix) PHP/5.5.23
X-Powered-By: PHP/5.5.23
WWW-Authenticate: Digest realm="SabreDAV",qop="auth",nonce="5559e809deca9",opaque="df58bdff8cf60599c939187d0b5c54de"
Content-Length: 1155
Content-Type: application/xml; charset=utf-8

HTTP/1.1 201 Created
Date: Mon, 18 May 2015 13:24:25 GMT
Server: Apache/2.4.10 (Unix) PHP/5.5.23
X-Powered-By: PHP/5.5.23
Content-Length: 0
Content-Type: text/html
```

This is 1.8.12

**Comment by untitaker** [comment]
Oh my god.

This is the fault of PHP's built-in web server (`php -S`). It seems to change every MKCALENDAR request to MKCOL.

**Comment by untitaker** [comment]
Filed https://bugs.php.net/bug.php?id=69655

**Comment by evert** [comment]
Oh my... reading this, it suddenly makes perfect sense.

@Hywan ran into this as well, and actually submitted several patches to https://github.com/joyent/http-parser.

@Hywan, did your patches get accepted?

**Comment by evert** [comment]
Looks like @helje got ahead : https://github.com/joyent/http-parser/pull/179

**Comment by evert** [comment]
It does for its internal websever. It's the same parser used by node js.

That parser is all about speed. It's not so much about conflating them, as it is about matching the least amount of bytes possible and then picking the correct method (`MKC`).

I don't think it's the right thing to do, as a HTTP agent should allow any methods it doesn't know about, but I get the reason why it was done that way.

**Comment by untitaker** [comment]
That's kind of disgusting. It isn't even correctly behaving if the method starts with MK in some cases.

**Comment by untitaker** [comment]
At least that's my impression, might as well be a bug in PHP

**Comment by helje5** [comment]
AFAIK the parser was written for nginx, not as a general purpose parser. The implementation was right for this purpose (why support stuff nginx didn't support ...). Then the Node.JS people 'took it' and used it for Node.JS. Looks like PHP did the same. The parser has some great advantages (zero copy!), but to be general purpose, this one bit should be adjusted.
