### ISSUE TITLE
Question: Can I use MySQL views?

### ISSUE THREAD

**Issue by nheimann1** [fruux/sabre-dav#634]
Hi,
Sorry to open an issue for this. I didn't really see a better outlet though for my question.

My particular use case cannot allow write privileges anyway (my use case is a contacts sync between my server and iOS contacts). Seeing as this is the case, do you think it will be possible to use MySQL VIEW(s) instead of implementing the backend, in order to integrate SabreDAV with my system?

I've run some tests where I've replaced `users` and `principals` which seemed to have worked quite well. But before I'm committing more of my time and effort, I thought it would be prudent to ask the creators if they see any inherent flaws as long as there are *no* write events?

I'd really appreciate your input, cheers!

**Comment by evert** [comment]
Well, it should be possible if you can exactly replicate the table structure.

**Comment by nheimann1** [comment]
Sure.
Thanks for the quick response
