### ISSUE TITLE
PUT a file with content results in a file with no content

### ISSUE THREAD

**Issue by tchaly-bethmaure** [fruux/sabre-dav#638]
Hi,

I'm testing the experimental DAV client. When I tried to create a file with a PUT verb (PUT http://localhost/webdav/calendar.ics for instance), the request return a 201 created code, the file is created, but there is no content inside.

Here is an exemple of how I use the DAV client :
use Sabre\DAV\Client;
$settings = array(
    'baseUri' => 'http://localhost/webdav',
    'userName' => '',
    'password' => '',
    'proxy' => '',
);
$client = new Client($settings);
$response = $client->request('PUT', $settings['baseUri'].'/calendar.ics',
                "Some content");

I was expecting (on localhost/webdav/) a file with "Some content" inside it, but I got a file with a size equal 0 instead. I've checked if the $body in the request(...) method of Client class was well set (set to "Some content"), I've also checked if "(string)$body" cast does not empty the variable, and it turns out that the content is set (not null and not empty). So I'm wondering what could be the matter. Do you have any idea of what make the content file empty ?

**Comment by evert** [comment]
I honestly i have no idea! What version of sabre/dav are you using?

**Comment by tchaly-bethmaure** [comment]
I was using the sabre/dav version 1.8.*, now I'm using sabre/dav version 2.1.3 and the issue is no more. Thanks to you. Have a nice week.
