### ISSUE TITLE
 Invalid version string "3.3.4 <4" in provider-sabre$dav.json

### ISSUE THREAD

**Issue by b4nderl0g** [fruux/sabre-dav#641]
When I downloading http://packagist.org/p/sabre/dav$a03452df3d9f085c953307158b7738b7a7b8ede89d945c43fe17d55b70b55191.json
to ~/.composer/cache/repo/https---packagist.org/provider-sabre$dav.json
the composer gives me a RuntimeException:
Could not load package sabre/dav in http://packagist.org: [UnexpectedValueException] Could not parse version constraint >=3.3.4 <4: Invalid version string "3.3.4 <4"

**Comment by evert** [comment]
Update your composer.

**Comment by b4nderl0g** [comment]
thx!!!
