### ISSUE TITLE
How to keep using Composer after integration of SabreDAV is complete?

### ISSUE THREAD

**Issue by nheimann1** [fruux/sabre-dav#644]
Just a question which may betray my ignorance using Composer or PHP Namespaces.

### The situation:
I've installed SabreDAV via Composer and have gone about changing the Backend PDO files in order to integrate it with my backend.

Now I've got changes to these files, but they're not saved because the vendor folder is in `.gitignore` (as I understand it should be). Obviously, I also realise changing files in `vendor` is ill-advised. What is the proper way to go about integrating SabreDAV with my backend, keep using Composer, and save my integration changes? Is there a place to put override files for the Backend PDOs? Or do I need to use `--prefer-source` in some sort of way?

I know I can always just fork the GIT repository, but I prefer using Composer when possible. Just not sure if Composer is built for this kind of thing or just for complete libraries.

Cheers!

**Comment by evert** [comment]
This  is much more of a basic programming question, than a sabre/dav specific one.

You should _never_ modify library files. You subclass the PDO classes.

**Comment by nheimann1** [comment]
Ok, thanks, it was just a namespace error.
