### ISSUE TITLE
Support PHP 5.5 for sabre/dav 3.0 onward

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#647]
Hey guys,

I just changed the version of the upcoming sabre/dav release from 2.2 to 3.0,.

One question that pops up, is should be switch to PHP 5.5 as the minimum PHP version.

The advantage is that we can:

1. Start using generators and reduce memory footprint.
2. Release sabre/vobject 4.0, and integrate support for xCal/xCard.

The ability to use generators will be a huge step up. This means we'll be able to handle all the requests that tend to be bottlenecks right as a stream. This means that the HTTP server can start sending output to the client faster, and since we don't need to have the entire xml response (and the data it's based on) in memory, this could result in massive memory wins and thus better scalability for busy servers.

Not supporting PHP 5.5 right now means that we'll do it at the next major release, which means that it's likely another year away.

There's a fairly massive drawback though, I feel that a big part of our user-base is still on PHP 5.4 and will not be able to upgrade yet. If a large portion of the user-base stays behind, it means that we likely have to maintain multiple code bases for longer. Having older versions 'out in the wild' is kind of bad for us too, as we're solving long-standing problems right now that will take longer until they reach end-users.

My personal preference would definitely be to switch to PHP 5.5, aside from the earlier reasons mentioned, there's a few other advantages:

* Increased 'developer happiness'. We can take advantage of new, fun features and not wait forever. Happy developers are productive developers ;)
* PHP 5.5 itself is faster and has a better memory footprint. By forcing PHP 5.5 on everyone, the people that can run it are also forced into a faster environment, which is good for the perception that sabre/dav itself is fast.

Dragging in a few people that might have an opinion : @fruux/developers , @DeepDiver1975 , @staabm, @PVince81, @jeromeschneider., @icewind1991 , @DavidPrevot. First: sorry for having done that, if you don't appreciate this, let me know =). Any concerns with switching to PHP 5.5 for sabre/dav-next ?

**Comment by DeepDiver1975** [comment]
This will require ownCloud to stick with sabredav 2.x series for a long time.
We have php 5.4 minimum requirement which we will most likely keep for years - FYI: we dropped 5.3 support with ownCloud 8.0.

Besides that I fully understand the move to 5.5. THX

**Comment by yunosh** [comment]
Same here, we will probably bump to 5.4 with Horde 6. We are still not updgraded to Sabre 2.1 though, so we are a bit behind anyway. Still we probably won't require 5.5 with any other libraries or apps anytime soon.

**Comment by DavidPrevot** [comment]
[ Adding Debian PHP PEAR (and composer) Maintainers, as well as Debian
  ownCloud maintainers list to the loop. Reply should go through GitHub
  to reach upstream. I’m happy to proxy anything relevant if needed.
  Full quote on <https://github.com/fruux/sabre-dav/issues/647>. ]

Le 29/04/2015 18:26, Evert Pot a écrit :

> I just changed the version of the upcoming sabre/dav release from 2.2
> to 3.0,.
>
> One question that pops up, is should be switch to PHP 5.5 as the
> minimum PHP version.

No objection with my Debian hat on: the latest stable release (Jessie,
as released last weekend), ship with PHP 5.6, so it shouldn’t be a
problem to run the latest Sabre stack on Debian (or any of its derivative).

Jessie already ship sabre/dav 1.8 (as used by ownCloud and Horde), so
the above only apply for backports/development, “normal” users should
anyway not be affected.

The previous stable (oldstable) Debian release, Wheezy, ship with
PHP 5.4 (as well as the one before (oldoldstable), Squeeze, that with
PHP 5.3), and is still around, but is less likely to be used for
development/deployment with the latest versions of sabre/dav ;).

> Dragging in a few people that might have an opinion : […] @DavidPrevot

Much appreciated, do not hesitate to continue keeping me in the loop if
I might be of help in the future.

Regards

David

**Comment by Hywan** [comment]
From a technical/developer point of view, I would say :+1:. It's funnier, faster, better.
From a pragmatic point of view, I don't know. I am afraid we lost some users. However, 3.0 is a great opportunity to: Clean some stuffs, get better performances and “restart” the release numbers (by adopting semver for instance). PHP5.4 is going to die at the end of this year (in September). As the father of Hoa too, we are going to drop PHP5.4 at the end of this year, because we only maintain alive versions of PHP. It bumps the major version of every libraries for nothing most of the time, but it “forces” users to upgrade, and it's good for the eco-system.

So… I would say :+1: :-).

**Comment by Hywan** [comment]
Also, I am afraid users will miss some awesome features if they don't upgrade to PHP5.5+, but that's the game. Even if we could provide these features even with PHP5.3, it won't be comfortable for us, and it won't help to get a clean and maintanable code, so… I think we just need to stick on the latest alive PHP version, which is PHP5.4 right now, and for the next couple of months.

We could release sabre/dav 2.2 with all the new features, and then, in few months, release sabre/dav 3.0, which requires PHP5.5 and includes all the cleanings.

Thoughts?

**Comment by DeepDiver1975** [comment]
> PHP5.4 is going to die at the end of this year (in September).

Regardless of the death of a certain version - linux distributions (some LTS and enterprise linuxes) will continue to support these out dated version for much more years.

e.g. RHEL 6 is still on php 5.3 and RHEL 7 is on php 5.4 - http://distrowatch.com/table.php?distribution=redhat

**Comment by evert** [comment]
Hey guys,

Thanks for all the feedback. It's definitely much appreciated and makes me think a little bit.

One thing I don't fully understand though, is that I completely get why you would want to support PHP 5.4 for any current versions of the projects that are out there today, I don't really understand why you would it's as important for your next major versions.

After all, if a user is ok with running older software (because they are on a LTS or a slower moving distribution), they can also accept that they have to run older versions of Owncloud and Horde.

In fact, they probably will, because I imagine that many of those people will use .deb or .rpm's for your respective software, which (probably?) also won't get updated to the next major version.

So what's holding you back? Do you anticipate that most of your user-base will want to run the bleeding edge of your software on older distributions? Or are you not in a good place to maintain multiple versions of your software?

Just a note that I promise I won't waste your time with a long-drawn argument about this ;) but I'm still curious if you can elaborate on your motivation :).

That all being said, if I can't convince the both of you to require PHP 5.5 for your next major version, I think we decided to support PHP 5.4 for sabre/dav 3.0, and start requiring PHP 5.5 on the master branch immediately after release =).

Thanks so much for replying!

**Comment by DeepDiver1975** [comment]
> So what's holding you back? Do you anticipate that most of your user-base will want to run the bleeding edge of your software on older distributions?

Talking about pure enterprise business: we are facing the fact that companies run RHEL 6 or RHEL 7 but want to deploy the latest ownCloud version which holds features we just did implement for the latest version. Telling them to use a different distro or have some special setup (like deploy a more recent php version) is our of scope because of support contracts or the way they manage their infrastructure.

**Comment by staabm** [comment]
Agree with @evert on all his points. Companies relying on LTS Versions explicitly agree to use "older" or non-bleeding-edge stable-releases of software components.

Dropping old PHP Version on new major relies while maintaining bugfix only release for older setups is the regular way to handle those environments.

**Comment by yunosh** [comment]
Zitat von Thomas Müller <notifications@github.com>:

>> So what's holding you back? Do you anticipate that most of your
>> user-base will want to run the bleeding edge of your software on older
>> distributions?
>
>   Talking about pure enterprise business: we are facing the fact that
> companies run RHEL 6 or RHEL 7 but want to deploy the latest ownCloud
> version which holds features we just did implement for the latest
> version. Telling them to use a different distro or have some special
> setup (like deploy a more recent php version) is our of scope because of
> support contracts or the way they manage their infrastructure.

Same here.
-------------------------
Jan Schneider
The Horde Project
http://www.horde.org/
https://www.facebook.com/hordeproject

**Comment by evert** [comment]
It's decided then. 3.0 will support 5.4, and the version after will require 5.5 =)

**Comment by DeepDiver1975** [comment]
> It's decided then. 3.0 will support 5.4, and the version after will require 5.5 =)

Awesome! Thanks a lot!
