### ISSUE TITLE
Base URI is URL-encoded by Browser plugin

### ISSUE THREAD

**Issue by zeymon** [fruux/sabre-dav#651]
The browser plugin apparently [re-encodes the base URI](https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Browser/Plugin.php#L287), which should be URL-encoded already and would break if it contained special characters.

Shouldn't this line

```php
$fullPath = URLUtil::encodePath($this->server->getBaseUri() . $subPath);
```

be changed to this?

```php
$fullPath = $this->server->getBaseUri() . URLUtil::encodePath($subPath);
```

**Comment by evert** [comment]
Sounds about right
