### ISSUE TITLE
CardDAV weirdness

### ISSUE THREAD

**Issue by stevewi** [fruux/sabre-dav#652]
sabre/dav v. 2.1.3
Contacts v. 9.0 (1579) [OS X Yosemite 10.10.3 (14D136)]

I can create CardDAV accounts just fine...and I can create cards in them.  However, when I use the principal URI of the form:

          https://<server>/card.php/principals/user/

Contacts will not let me change the description on the account.  If I use the form:

          https://<server>/card.php/addressbooks/user/

everything works just great.  My code for card.php is the vanilla example you provide...  The only thing I added was a call to date_default_timezone_set() at the beginning to eliminate some pesky PHP warnings and I use a different database name.

FWIW, if I use the form:

         https://<server>/cal.php/principals/user/

for CalDAV accounts, everything works as expected in Calendar.

**Comment by stevewi** [comment]
This appears to be some weirdness with Contacts.  I was successfully able to change the display name for the CardDAV account but had to use a different procedure to do it.  Don'tcha just love it when there's more than one way to do something ?!?

**Comment by evert** [comment]
Hi Steve,

It indeed is weird. The name actually doesn't get sent to the server at all, so it sounds like it must have been some kind of bug. Glad you figured it out though!
