### ISSUE TITLE
{http://calendarserver.org/ns/}me-card is returned incorrectly

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-dav#680]
A stock sabre/dav installation with activated propertyStorage plugin stores an URI for the `{http://calendarserver.org/ns/}me-card` property as follows in the database:

```
O:27:"Sabre\DAV\Xml\Property\Href":2:{s:8:"*hrefs";a:1:{i:0;s:64:"/addressbooks/foo/book1/ef068c36-dbf4-400d-a844-4df53d98c46d.vcf";}s:13:"*autoPrefix";b:1;}
```

When the server returns the property (e.g. during a `PROPFIND`) is incorrectly returned with a double slash `//`, which breaks the me-card feature in clients like OS X Contacts.app.

```
<d:href>//addressbooks/foo/book1/ef068c36-dbf4-400d-a844-4df53d98c46d.vcf</d:href>
```

**Comment by DominikTo** [comment]
Might be related to the autoPrefixing in:
* https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Xml/Property/Href.php#L107

**Comment by evert** [comment]
Ah interesting :+1:

**Comment by evert** [comment]
The issue here is that either autoPrefix must be false, or the URI must be modified to become relative.

**Comment by DominikTo** [comment]
We should probably also set `$autoPrefix = false` in the migration script now, @evert:
* https://github.com/fruux/sabre-dav/blob/master/bin/migrateto30.php#L163
* https://github.com/fruux/sabre-dav/blob/master/bin/migrateto30.php#L166

**Comment by evert** [comment]
yes i suppose we should!

**Comment by evert** [comment]
No actually it's fine. The original migrated value did not have a base uri associated to it.
