### ISSUE TITLE
Throw an exception when no HTTP status code was set when sending the response.

### ISSUE THREAD

**Issue by tohojo** [fruux/sabre-dav#684]
See comment on the HEAD commit here:

https://github.com/fruux/sabre-dav/commit/d9a2626ea9bea28381653003b912a98915abc3b3#diff-1912a70ed906bb86ae73200e6a7cf9daR257

Quoted the comment below:

>The GET method can return without $response having a status set, which will be converted into a 500 error further up the chain, breaking clients.
>
> Adding a line:
> ```if(!$response->getStatus()) throw new Exception\NotImplemented;```
> 
> prior to the exception being caught has fixed it for me.
> 
> Ran into this on Owncloud 8.1 using the android client.

**Comment by tohojo** [comment]
I should probably add that I realise my "fix" is probably not the correct way to deal with this; fixing the GET method would probably be better :)

**Comment by Wurmdosungen** [comment]
Unfortunately, this fix doesn't work for me (with the Android client). It did solve, though, the problem with the Owncloud desktop clients (I was able to use existing installations, but unable to change account settings, and unable to set up the Owncloud client on new systems).

**Comment by evert** [comment]
Sorry for the super long delay in responding to this. I think this is a classic case of fixing a symptom, and not the underlying cause. The big question is: in which case does httpGet return with no status code? That should afaik not happen.

**Comment by evert** [comment]
So hopefully you can provide a bit more feedback on this, I'll keep the issue open a bit longer

**Comment by Wurmdosungen** [comment]
I don't know if I am able to help (my setup is not the usual one, I am using Arch Linux, and I use UWSGI for executing Owncloud), but let me know if I can provide any information. Is there a (not too complicated) way to get the integrated SabreDAV to log e.g. to a file?

What happens for me is that the HEAD request to /remote.php/webdav/ fails (message now, with Owncloud 8.1.1: "669 upstream prematurely closed connection while reading response header from upstream, [...] upstream: "uwsgi://127.0.0.1:3333""). At the same time, UWSGI logs "HEAD /remote.php/webdav/ => generated 0 bytes in 920 msecs". Owncloud itself doesn't log anything. :-(

**Comment by tohojo** [comment]
Yes, fixing the HTTP get method is probably the right thing to do. I think it's this line that is the culprit: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/CorePlugin.php#L81

If I understand the calling code correctly, that should really be a 'return true' to signal that the function has *not* handled the request...

**Comment by Wurmdosungen** [comment]
This sounds very reasonable, but it seems not to be the only problem: When I change the respective line appropriately (to return true), for me this leads to nginx complaining "upstream prematurely closed connection while reading response header from upstream", indicating that the situation doesn't get handled elsewhere, either. The OwnCloud Android client sticks with its descriptive error message "Unknown error" ;-)

**Comment by evert** [comment]
@Wurmdosungen whatever problem you are having, it's not described in this issue. If the problem description here is correct, the HEAD request will still return a 501 HTTP error. Your problem is definitely different as it seems as if the entire TCP connection is broken. In the case of PHP this happens in rare cases when there's for example a segmentation fault. Check your PHP and apache errors logs.

@tohojo, the line you pointed out is not problematic. When `false` is returned there (and every other http `GET` method handler), this line will eventually trigger: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Server.php#L462

**Comment by tohojo** [comment]
But doesn't that only trigger when the method returns true, not false? The comment at https://github.com/fruux/sabre-dav/blob/master/lib/DAV/CorePlugin.php#L197 would indicate so...

**Comment by evert** [comment]
So it's a bit confusing.... 

1. Returning `false` will *stop* the event handler and will cause the server to no longer look for other method handlers to try to handle the `GET` handler.
2. Return *anything other than `false`* will *not* stop the event handler. So if `null` is returned, the event handler will keep on triggering event handlers.

Returning `false` is like calling `preventDefault` in javascript.

After the events have been handled, the `emit()` function itself will return `false` if *any* of the method handlers interrupted the event with `false`, but it will return `true` if no method handlers did.

So if `httpGet` returns `null` and no other method handlers were around, eventually `emit()` returns `true`.

**Comment by tohojo** [comment]
Ah, right, well that *is* a tiny bit confusing... ;)

But okay, I guess that means searching for a different culprit is necessary. I'll try to go back to my original pre-patch setup and see if I can figure out where the GET handler fails...

**Comment by gdamjan** [comment]
I'm facing this same issue with uwsgi/owncloud 

But I've tested the example `fileserver.php` with sabre 2.1.6 in uwsgi, and the HEAD requests do work fine there. So there's something in the way owncloud integrates sabre that creates the problem. And possibly connected to uwsgi too (though it shouldn't be different than fpm).

**Comment by gdamjan** [comment]
Aaaand. I'm a genious* :)

commenting out
```
$server->addPlugin(new \OC\Connector\Sabre\DummyGetResponsePlugin());
```
in ./apps/files/appinfo/remote.php fixes the issue with the android app instant upload.


* not actually but I got over-exited that finally I've found something tangible about the problem after months of suffering.

**Comment by evert** [comment]
If this also solves the issue for @tohojo and @Wurmdosungen, i think it's safe to guess that this is an owncloud bug.

I imagine though that commenting out the plugin might have other side effects.

**Comment by gdamjan** [comment]
So this is what happens, a HEAD request comes in,
CorePlugin::httpHead is called, it calls invokeMethod with the subrequest method changed to GET, the request goes to CorePlugin::httpGet, it denies to process it, but the DummyGetResponsePlugin::httpGet takes over an returns the string response.

Then we get back to CorePlugin::httpHead which doesn't notice any error (and it would really like to catch a Exception\NotImplemented), and just returns back.
At this point we have 'some' response to the HEAD request that uwsgi doesn't quite like and it just drops the connection.

I'll try to understand further what uwsgi is not happy about, but one issue for me is, is DummyGetResponsePlugin::httpGet actually done by sabre specs? Or should it also throw an exception for non-files?

https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/dummygetresponseplugin.php

**Comment by teemu-torma** [comment]
I compared earlier today the output of GET /remote.php/webdav/ using curl to see if there is difference between fpm and uwsgi.  fpm version returns the response from DummyGetResponsePlugin, whilst uwsgi returns different headers and empty body.  I didn't have any time to dig further to see why they behave differently in this case.

**Comment by evert** [comment]
@gdamjan , I think the main issue is then that `DummyGetResponsePlugin::httpGet()` does not set a status code.

Try adding:

```php
$response->setStatus(200);
```

On the sabre/dav end, we should probably really try to catch that problem and then throw an alternative exception.

**Comment by gdamjan** [comment]
@evert true.
adding status(200) there makes owncloud return a proper HEAD and GET response (200 ok) with the same headers.

**Comment by LukasReschke** [comment]
@evert To double check: So you recommend sending a 200 there? – If so I can prepare a PR…

**Comment by evert** [comment]
Yep, that should be all that's needed. Closing this ticket then.

**Comment by gdamjan** [comment]
the owncloud fix, is good for me, but maybe sabre-dav (or ... where does the $response object come from) should be more defensive? 

What uwsgi got in the end was a status header of just 'HTTP/1.1 ' which is simply wrong.

OTOH, uwsgi needs to be more defensive too, but that's another story.

**Comment by evert** [comment]
You're right. Reopening and re-titling this.

**Comment by tohojo** [comment]
So my original work-around was just to put this line into the try{} block in the httpHead function in CorePlugin.php:

    if(!$response->getStatus()) throw new Exception\NotImplemented;

Not sure it's the right place to throw the exception, though; but it did work :)

**Comment by evert** [comment]
The solution this needs, needs to work for every method. And it also needs to throw a HTTP 500, not 501.
