### ISSUE TITLE
NoInstancesException

### ISSUE THREAD

**Issue by mschering** [fruux/sabre-dav#688]
Hi,

I get a fatal error on a wierd but I think valid vcalendar object (version 1.8.9):

PHP Fatal error:  Uncaught exception 'Sabre\VObject\Recur\NoInstancesException' with message 'This recurrence rule does not generate any valid instances' in /usr/share/groupoffice/go/vendor/VObject/lib/Sabre/VObject/Recur/EventIterator.php

The strange thing about the vobject is that it's a recurring event but all the recurring instances have an exdate set:

BEGIN:VCALENDAR
BEGIN:VEVENT
UID:fa0400c1-b6b7-5d83-b452-0e1f92cc70c2
DTSTAMP:20150716T151809Z
DTSTAMP:20150716T131809Z
LAST-MODIFIED:20150701T114454Z
CREATED:20150701T114454Z
SUMMARY:Sabre bug
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin:20150826T100000
DTEND;TZID=Europe/Berlin:20150826T103000
LOCATION:DB
RRULE:FREQ=DAILY;UNTIL=20150827T235900
EXDATE;TZID=Europe/Berlin:20150826T100000
EXDATE;TZID=Europe/Berlin:20150827T100000
END:VEVENT
END:VCALENDAR

Shouldn't this be valid and secondly, shouldn't the error at least be caught and handled with a proper response code?

Thanks!

**Comment by evert** [comment]
Hey,

This is an issue that came up a little while ago. It's not clear if this is a valid event, the spec don't really seem to say if it is or isn't. What I can say is that it's completely useless data. This event will never show up in a calendar anywhere, and it can't be deleted by a user. So we decided to consider it invalid.

I agree that it should be met with a good status code. Which HTTP request is triggering the exception?

**Comment by evert** [comment]
No feedback received
