### ISSUE TITLE
Locks backend SQL query not working with PostgreSQL

### ISSUE THREAD

**Issue by TCKnet** [fruux/sabre-dav#699]
Can be fixed with:

sed 's/((created + timeout) > CAST(\? AS UNSIGNED INTEGER))/(created > (? - timeout))/g' vendor/sabre/dav/lib/DAV/Locks/Backend/PDO.php > tmp
mv tmp vendor/sabre/dav/lib/DAV/Locks/Backend/PDO.php

Thanks :+1:

**Comment by evert** [comment]
Pretty sure that CAST was there for a reason, but I'll apply the patch and see if the unittests break =)

**Comment by evert** [comment]
Applied this fix. Note that Postgres is completely untested and has other problems. All postgres contributions and fixes come from random people and I've never verified it.

If you use postgres and you're interested to make it better, take a look at #521 for a work in progress that has sadly been abandoned.
