### ISSUE TITLE
Cyberduck isn't seeing files/folders with spaces in them.

### ISSUE THREAD

**Issue by docmattman** [fruux/sabre-dav#704]
I have the latest SabreDav up and running.  With the browser plugin, I can see everything.  But when I use Cyberduck to connect to the webdav, I can't see any files or folders that have spaces in them.  Any advice for fixing this?

**Comment by evert** [comment]
Because I don't have access to a OS X or Windows machine right now, I can't reproduce it.

If would be helpful if someone else could take a look at this to verify the issue. If it exists for others, I'd need to take a look at a charles http proxy dump to see if the issue is our fault.

**Comment by legsak1mbo** [comment]
I can reproduce this. It looks like CyberDuck doesn't like the fact that the href tag returned in a propfind (which it calls before downloading files with spaces in) isn't url encoded.

Changing line 65 of Sabre/DAV/Xml/Element/Response.php to...

    $this->href = implode('/', array_map('rawurlencode', explode('/', $href)));

...seems to make CyberDuck behave. I haven't tested thoroughly with any other clients yet though.

**Comment by legsak1mbo** [comment]
So the above breaks if you have directories with spaces in their names (they get double-encoded). It seems that SabreDAV is ignoring getName on a Sabre\DAV\File object (where I call rawurlencode).

The response which CyberDuck receives is...

` <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> 
	<d:response> 
		<d:href>/drive/WebDAV%20Test/test copy.png</d:href> 
		<d:propstat> 
			<d:prop> 
				<d:getcontentlength>1008</d:getcontentlength> 
				<d:resourcetype /> 
				<d:getetag>1234567890</d:getetag> 
			</d:prop> 
			<d:status>HTTP/1.1 200 OK</d:status> 
		</d:propstat> 
	</d:response> 
</d:multistatus>`

If I send `<d:href>/drive/WebDAV%20Test/test%20copy.png</d:href> ` then CyberDuck is happy.

**Comment by evert** [comment]
`getName()` should never return urlencoded names. All the encoding should be done during serialization. So if you're seeing this, it definitely would be a bug. What version are you running @legsak1mbo ?

**Comment by legsak1mbo** [comment]
3.1.0-alpha2

**Comment by legsak1mbo** [comment]
If I don't call rawurlencode in getName then I don't see the items in the response. That goes for directories and files.

**Comment by legsak1mbo** [comment]
A cheap way around it is to url decode the href before encoding it in the response constructor.

**Comment by evert** [comment]
Issue is confirmed on the 3.0 branch as well. Looking into it.

**Comment by evert** [comment]
Comitted a fix to the 3.0 branch. Going to release this real soon too.

**Comment by legsak1mbo** [comment]
Confirmed fixed.
