### ISSUE TITLE
Make it possible to disable deletion on MOVE + overwrite

### ISSUE THREAD

**Issue by PVince81** [fruux/sabre-dav#705]
Consider the current scenario:

1. a file exists in "/a/test.txt" but the user only has read permissions
2. another file exists as "/test.txt"
3. the user performs a MOVE "/a/test.txt" "/test.txt" with overwrite

In the normal case of MOVE + overwrite, Sabre will automatically delete the target file "/test.txt".
But here the user isn't allowed to move the source file.

It should be possible to tell Sabre to not automatically delete the target file and leave the decision up to the implementation of $tree->move() to decide whether to delete the target or not.

Also the `beforeMove` hook is fired too late: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/CorePlugin.php#L636

The only way I can think of is overriding the Server class / Core plugin somehow and overriding either `httpMove` or `getCopyAndMoveInfo` and return false for "destinationExists".

What do you think ?

**Comment by evert** [comment]
Hmm.. aren't we simply missing a preemptive `beforeUnbind` on the destination? That would prevent the operation from happening in the first place.

I agree that the event order is definitely broken :/

**Comment by PVince81** [comment]
Seems to be the same for a copy operation.

**Comment by PVince81** [comment]
@evert how about the COPY operation ?

**Comment by evert** [comment]
Well, the core issue here was that "if the source file can not be deleted" then "the destination file still got wiped out". That's not really a concern with copy... but I take it from your comment there's a similar issue there too?

**Comment by evert** [comment]
Looking at the copy method, there is still indeed an ordering issue. We really need to trigger all the "before" events before making any permanent changes. I'm opening a new ticket for this.

**Comment by PVince81** [comment]
Thanks :smile:
I was asking for COPY mostly for consistency, this is not required for ownCloud.
