### ISSUE TITLE
iPhone and CardDAV synchronization - why sabre.io URL in sync-token XML

### ISSUE THREAD

**Issue by wjgilmore** [fruux/sabre-dav#706]
Hi,

I just posted to the SabreDAV discussion group only to have the message immediately deleted? No idea why, as the message definitely was not spam.

We are running SabreDAV 3.0, when installing a configuration profile on iPhone everything goes fine, the SabreDAV address book immediately shows up. However, the phone thereafter refuses to synchronize new additions to the address book (contacts added to the sabre-dav cards table and the address book's synctoken updated).

As I understand it, the synctoken column determines whether the client should look into updating the address book, correct? So after synctoken changes (we are just incrementing it), the phone will eventually ask the server for the token, and if it changes, the phone will then ask the server for the cards' etags. If those have changed (or if cards are added), the phone will update the address book accordingly?

Something that caught our attention was the very last response the SabreDAV server sends when I refresh the iPhone Groups UI (click on Groups inside Contacts app which causes the phone to immediately start talking to our SabreDAV server). Here it is:

    <?xml version="1.0"?>
    <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"
    xmlns:card="urn:ietf:params:xml:ns:carddav">
    <d:sync-token>http://sabre.io/ns/sync/188</d:sync-token>
    </d:multistatus>

Does this cause the phone to them try to talk to http://sabre.io/ns/sync/188? If so clearly this is the problem however I can see no way to update this. Again, the initial address book is sent from SabreDAV server to phone just fine, but something very strange is happening when synchronization needs to happen.

Thanks!
Jason

**Comment by evert** [comment]
> I just posted to the SabreDAV discussion group only to have the message immediately deleted? No idea why, as the message definitely was not spam.

9 times out of 10 it's misconfigured outgoing email. Is SPF and DKIM setup correctly? Are you using the correct stmp server and not a random other one?

> As I understand it, the synctoken column determines whether the client should look into updating the address book, correct? 

Correct.

> So after synctoken changes (we are just incrementing it), 

This is wrong. The synctoken system depends on the sync-token REPORT returning correct information. My guess is that you are just returning the property, but you also need to track every change. Take a look at the PDO backend:

https://github.com/fruux/sabre-dav/blob/master/lib/CardDAV/Backend/PDO.php#L460

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"
xmlns:card="urn:ietf:params:xml:ns:carddav">
<d:sync-token>http://sabre.io/ns/sync/188</d:sync-token>
</d:multistatus>
```

That response looks broken, but that's also likely because you didn't correctly implement it.

> Does this cause the phone to them try to talk to http://sabre.io/ns/sync/188? If so clearly this is the problem however I can see no way to update this. 

No, that url is correct. The url is *just* used as an identifier. Much like an xml namespace, it's treated as a name or identifier, not as a resource where information should be fetched from. The identifier must be a valid URI, so we picked a namespace we own.

**Comment by wjgilmore** [comment]
Oooooohhh aha. I was wondering what in the world that `addressbookchanges` table was for, however presumed SabreDAV was somehow using it because the documentation at http://sabre.io/dav/sync/ states "The standard CalDAV and CardDAV PDO backends already provide support for this, and therefore, all you need to do to enable this is add the Sync Plugin". No matter though I am SO happy to know the answer. :-)

So in the end all I need to do is additionally update the addressbookchanges to identify the card uri, associated addressbook synctoken, addressbookid, and operation? And the operation value is one of added, modified, deleted?

Thank you so much for clarifying, this has been driving us crazy!

Jason

**Comment by evert** [comment]
Well, the real question is... why are you manually making database changes? it sounds like you are using the default PDO classes for this.

Just instantiate Sabre\CardDAV\Backend\PDO and call its methods. This should handle all the logic for you and will give you an actual upgrade path (database layout tends to change between versions).

**Comment by wjgilmore** [comment]
We are batch processing large numbers of contacts (tens of thousands) originating within a separate system. The contacts are pushed into the SabreDAV database. Due to the sensitive nature of the separate database, the SabreDAV server will not talk to it, meaning Sabre\CardDAV\Backend\PDO can't be used to talk to it.

I understand that indeed the upgrade path will be more difficult, however otherwise we just have to update that addressbooks table accordingly, correct? This is because the SabreDAV PDO class is used by the server to retrieve the synctoken and then all corresponding sync token-specific changes in `addressbooks`.  So in a nutshell even if we aren't using the SabreDAV PDO class to *insert* the data, as long as we properly update `addressbooks` with the appropriate information, everything should work just fine?

Thanks again for clarifying! Seriously you made my day.

Jason

**Comment by evert** [comment]
You're going to insert it into the database at one point, why not use sabredav code to actually do this? I don't see a security difference here.

Anyway, your funeral!
