### ISSUE TITLE
OAuth 2.0 Bearer/Introspection support

### ISSUE THREAD

**Issue by fkooman** [fruux/sabre-dav#708]
Hi,

I'm working on implementing [0,1] Bearer [2] token support in SabreDAV with introspection support [3]. Is there any interest in merging this upstream as an additional authentication backend? It will most likely be of interest to ownCloud for example to integrate with their (native) apps.

I still need to add some more unit tests and make the introspection more robust of course.

[0] https://github.com/fruux/sabre-http/compare/master...fkooman:bearer?expand=1
[1] https://github.com/fruux/sabre-dav/compare/master...fkooman:introspection?expand=1
[2] http://tools.ietf.org/html/rfc6750
[3] http://tools.ietf.org/html/draft-ietf-oauth-introspection

**Comment by fkooman** [comment]
@karlitschek

**Comment by evert** [comment]
Hi!

The sabre/http patch looks good (with the exception of the missing unittests), but I'm not really sure about the sabre-dav patch.

In particular, I don't really know introspection well, and how useful it will end up being in general. What's especially problematic, is that it will do a HTTP request for every request, greatly increasing latency.

However, I think it can be very useful to have something generic in place that can authenticated OAuth2 bearer tokens. I'm thinking, what if you rewrite the backend to behave more like Sabre\DAV\Auth\Backend\BasicCallback.

Similarly, this backend could recieve a callback in its constructor, which could be called with the token as an argument, and return a principal uri as its result.

This allows people to easily implement OAuth2 bearer tokens, and does not shut the door to using more advanced stuff like introspection. It will also allow you to create that callback in a way where you would cache the result.

**Comment by fkooman** [comment]
Hi!

Thanks for your feedback! There is a more or less complete unittest for the sabre/http patch, or do you mean writing additional testing is required?

I agree on your approach, I will work on that and update the code.

**Comment by fkooman** [comment]
I now created the AbstractBearer class and added a unit test for it as well. I can proceed and send pull requests for sabre/http and sabre/dav if you like! Both branches are now named `bearer`.

Do you think it still makes sense to create also the `BearerCallback` class? I mean, it is also possible to simply extend the `AbstractBearer` class and use stuff like Guzzle for doing the introspection request (in my case). But maybe the callback thing is useful as well, it is not that much extra work :)

https://github.com/fruux/sabre-http/compare/master...fkooman:bearer?expand=1
https://github.com/fruux/sabre-dav/compare/master...fkooman:bearer?expand=1

**Comment by evert** [comment]
Feel free to create the PR's. There's a few issues in them still, but it will be easier to comment line-by-line once it's posted =)

I don't think we need the 'Callback' class. For me it was either the "AbstractBearer" or the "BearerCallback" class, but we definitely don't need both.
