### ISSUE TITLE
add copyInto function

### ISSUE THREAD

**Issue by DannyZB** [fruux/sabre-dav#716]
I have a dedup virtual filesystem in place in my project, and when files are copied I just duplicate their pointer.
As it stands in sabre/dav I only see a way to override the moveInto function.
Where is the copyInto function ? how do I override that ?

It should be a feature , and if it is , it should be documented.

**Comment by evert** [comment]
You can subclass `Sabre\DAV\Tree` and override the `copy()` method.

**Comment by DannyZB** [comment]
That really needs to be documented in the same place as moveInto -> it's equally as important.
why isn't it in the moveTarget interface ? or a similar copyTarget interface


class MyDirectory extends DAV\Collection implements DAV\IQuota, DAV\IMoveTarget, DAV\IMultiGet
> How do I extend that class to implement a tree ? 
or is a separate implementation required

I don't see the Tree class anywhere in the inheritance structure.
P.S.
When I redirect to a secondary storage server ( 302/303/307 -> makes no difference ), is it a proper way to respond to a get request ?
Transmit on OS X ignores the redirect and throws an error.

**Comment by evert** [comment]
Move *generally* is much more important. Generally a move on most systems is a rename, which is atomic and very fast... there's only a a few types of systems where a cheap copy exist.

To implement a custom copy function, simply extend `Sabre\DAV\Tree` and pass that object in the constructor of `Sabre\DAV\Server`.

Normally passing a custom tree is optional in the `Sabre\DAV\Server`. I'd recommend looking at the source for it's constructor to see how the server, tree and nodes interact, and you should be able to figure it out based on that.

The tree lives *outside* of the node structure, it basically manages it.

>  When I redirect to a secondary storage server ( 302/303/307 -> makes no difference ), is it a proper way to respond to a get request ?

I haven't seen a webdav client yet that follows redirects.

**Comment by DannyZB** [comment]
Ah ok thanks ! I'll look into that

I haven't seen a webdav client yet that follows redirects.
__________________________
All the ones I tested follow redirects perfectly, it's actually documented in the microsoft documentation for webdav as part of the protocol implementation.

Right now Transmit has been the only client which refused a redirect ..
How do you usually handle Webdav over systems that may have files on different IP addresses ?
I thought a redirect makes perfect sense.

**Comment by evert** [comment]
I completely agree that it would be brilliant if it generally works, but in my experience most of the time it fails. Really nice to hear that (modern?) windows clients do it well though, that was new to me.

**Comment by DannyZB** [comment]
OS X does that natively.
So does Windows7 and Windows8, further testing is needed.

It's part of the spec - I'm really surprised some clients neglected to support it.
Will have to do more testing I guess ...

What clients did you test it on ?

**Comment by evert** [comment]
I spent some time with several clients listed on sabre.io back in the days. It's very possible that since then the landscape might have changed a bit. I believe the gvfs client also did it correctly, but I also remember both windows and mac failing this.

If the situation is very different now, it would be very interesting to know =) And I definitely agree, it *should* have always been the case =)

**Comment by DannyZB** [comment]
$root = new MyDirectory('filler/');

// The object tree needs in turn to be passed to the server class
$server = new DAV\Server($root);

How do I pass that tree to the DAV server constructor ?
Already passing my custom directory class..

I need to throw that entire class out now ? kind of confused..
Didn't really plan on rewriting everything else

**Comment by evert** [comment]
No I have indeed seen the same thing. There's also clients that don't DELETE entire collections, but instead delete every individual file in the directory first :/

**Comment by DannyZB** [comment]
ah oh well ..

Next question relevant to that :
PUT requests also need to be redirected.
I'm just concerned upload will start before the redirect.

How do I redirect PUT/CREATE requests to a different server ? where do I code that so it happens before anything is uploaded ?

p.s. I use nginx

**Comment by evert** [comment]
You could add an event handler for the HTTP PUT request, as such:

```
$server->on('method:PUT', function($request, $response) {
   $response->setStatus(307);
   $response->setHeader('Location', '/foo/bar');
   return false; // breaks event chain
});

See: http://sabre.io/dav/writing-plugins/

Note that I sincerely doubt anyone follows these types of redirects, even more so than `GET` requests. But ... could also be wrong here =) Most people just proxy PUT requests.

**Comment by DannyZB** [comment]
Ah thanks !

In regards to that , maybe it's related to : 
https://tools.ietf.org/html/rfc4437

look at number #5 

Maybe additional headers are needed for clients to follow ?

**Comment by evert** [comment]
Hi! I missed your last message.

For what it's worth, redirect references are not implemented. See here for a full list of standards we do and don't support:

http://sabre.io/dav/standards-support/

**Comment by DannyZB** [comment]
That is probably why it doesn't work.

How do I implement it ? i.e. what is required?

It's pretty vital to me - if need be I can code it myself

**Comment by evert** [comment]
Implementing redirect references? It's a bit hard to say. It will require a bit of research on my end as well to find out what an appropriate way is. Generally any new functionality in sabredav consists of two main things though:

1. A plugin, that handles all the request
2. A set of interfaces, extending `Sabre\DAV\INode`

I suspect this would be identical for RedirectReferences. If it's implemented that way, I don't think it's needed to also ship a "reference implementation". The interfaces + plugins should be enough.

**Comment by DannyZB** [comment]
Ok cool.
I may implement it at some point -> contributing to this project can be interesting.

Just one last question >
When the user makes a put request for a file and I redirect him, wouldn't the client try uploading the file before SabreDAV can tell it it's forbidden ?
I thought the file is uploaded before loading the script

**Comment by evert** [comment]
Yea this is correct. Unfortunately with PHP the entire request must be sent before PHP gets a chance to send a response. Perhaps with some other server technology it might have been possible to respond immediately.

**Comment by DannyZB** [comment]
I have nginx over PHP and can implement a thin javascript script over it to make sure redirected requests don't get to upload.

What needs to happen - on the data/protocol level - to prevent the upload happening and respond immediately ?
