### ISSUE TITLE
info icons sometimes not generated for files in the Browser plugin

### ISSUE THREAD

**Issue by mcassaniti** [fruux/sabre-dav#720]
Hi,
It took me a while to find out what was going on here since I have my own directory and file classes. What I found (which is still an issue in master) is that in DAV\Browser\Plugin.php in function generateDirectoryIndex, the line <code>if ($subNode instanceof DAV\IFile)</code> should be changed to <code>if ($subProps['subNode'] instanceof DAV\IFile)</code> (approx line 319).

Currently the code uses the last $subNode value from the previous loop, which in some cases is not an instance of DAV\IFile. Should be a simple fix.

**Comment by evert** [comment]
Thank you! This was recently fixed on master.
