### ISSUE TITLE
Issue in reading the files uploaded using sabre/dav

### ISSUE THREAD

**Issue by amirazma** [fruux/sabre-dav#722]
Hi Guys,
I have setup the sabre/dav and could see the page that has the form to upload files and create directories. Once I upload a file like a picture or PDF, then when I click on the picture name, I cannot see it in browser, but if I add the name "/public" before the file name  , I can see the picture. 
How I can fix this issue? I want to be able to open a uploaded files in the browser. 

My second issue is I am trying to use WebDav on my Mac, in Finder. When I drag a file to my remote folder it asks for username/password, but never accepts my username/pass... 
Should I setup the permission for sabre/dav somewhere?
Thank you so much , I appreciate you helps.
Andy

**Comment by evert** [comment]
Hi!

You posted this on the mailing list, on github, and to my personal email address. I read all three so in the future, please don't spam your problem wherever you can.

Please read this document and see if it solves your problem:

http://sabre.io/dav/baseuri/
