### ISSUE TITLE
Error: INTERVAL in RRULE must be a positive integer!

### ISSUE THREAD

**Issue by captainwasabi** [fruux/sabre-dav#723]
I am evaluating ownCloud and I have an Outlook user testing OutlookCalDavSynchronizer.  I am getting the error in the ownCloud logfile.  Things seemed to be working fine for him until he created a recurring event then it started throwing this error, after that it throws the error every time even though he deleted the recurring event.

here is the .ics of the problem event as exported from outlook.  This gives an error when importing into thunderbird as well.  however when adding it into thunderbird, while it doesn't display it in Lightning it DOES sync it to ownCloud and it shows up in ownCloud's calendar:  

BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 15.0 MIMEDIR//EN
VERSION:2.0
METHOD:PUBLISH
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16011104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20150923T134332Z
DESCRIPTION:\n
DTEND;TZID="Eastern Standard Time":20150924T093000
DTSTAMP:20150923T134332Z
DTSTART;TZID="Eastern Standard Time":20150924T090000
LAST-MODIFIED:20150923T134332Z
LOCATION:703-544-7603
PRIORITY:5
RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
SEQUENCE:0
SUMMARY;LANGUAGE=en-us:Director's Call
TRANSP:OPAQUE
UID:040000008200E00074C5B7101A82E008000000004045D39BE3F5D001000000000000000
	010000000112E1F996BE1AD42BD27A67BB636D3EB
X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//E
	N">\n<HTML>\n<HEAD>\n<META NAME="Generator" CONTENT="MS Exchange Server ve
	rsion rmj.rmm.rup.rpr">\n<TITLE></TITLE>\n</HEAD>\n<BODY>\n\n\n<P DIR=LTR><SPAN LANG="en-us"></SPAN></P>\n\n<
	/BODY>\n</HTML>
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-AUTOFILLLOCATION:FALSE
X-MS-OLK-AUTOSTARTCHECK:FALSE
X-MS-OLK-CONFTYPE:0
BEGIN:VALARM
TRIGGER:-PT5M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by evert** [comment]
Hi!

I don't think the file in question is what is triggering the issue. I think it's something else on the server, that's still there...

Also, owncloud questions should generally be directed to the owncloud project, not here. When it turns out there's an underlying sabredav bug, they tend to escalate to this project... which works well so far.

But in this case I'm happy to try to resolve this issue with you. Let me know.

**Comment by captainwasabi** [comment]
Ok, we've narrowed it down to something in the chain (and it looks like
it's outlookcaldavsync or ownCloud, doesn't like the way outlook specifies
events that are created to recur every weekday.  If the event is created on
Android, syncd to owncloud then to outlook no problem, created on owncloud
syncd to outlook, no problem. Created on outlook synced to ownCloud,
problem.  It's very odd.

--

**Comment by evert** [comment]
Alright, I will close this ticket here then. If it turns out this is a real sabredav problem, then a new ticket can always be reopened.

**Comment by aluxnimm** [comment]
There must be some event in Owncloud with invalid INTERVAL in a recurrence rule.
I found an issue with the Outlook Object Model that sets INTERVAL=0 for appointments with all workday recurrence, and we export it as
RRULE:FREQ=WEEKLY;INTERVAL=0;BYDAY=MO,TU,WE,TH,FR 
which should be INTERVAL=1 of course. 
Fix will be in next release of OutlookCalDavSynchronizer, see also
https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/99

**Comment by evert** [comment]
Makes sense
