### ISSUE TITLE
Reloading user contacts

### ISSUE THREAD

**Issue by wjgilmore** [fruux/sabre-dav#725]
Hi,

I realize what I'm about to ask is perhaps bending the capabilities of Sabre, however we've already extended the core classes to such an extent that I no longer feel shame asking such questions. :-)

Each of our users receives a global list of contacts, and an additional list of custom contacts. When the user modifies one of their custom contacts, we would ideally like to reload their global contacts. We know that not sending back the pertinent address book identifier (returned when `CardDAV/Backend/PDO.php class`' `getAddressBooksForUser` method executes) will indeed do the job, however there doesn't seem to be any sane way to manually execute this method since it is of course called further down the Sabre stack.

Another simpler solution involves asking the user to just reinstall their configuration profile by clicking on a text message link. These changes to the custom contact list are so infrequent (yet possible) that this was brought up as a likely acceptable solution.

Of course, automating the reloading would be preferable since it would be transparent to the user, but I can't really think of a sane way to do this and so thought I'd ask the experts.

Thanks!
Jason

**Comment by evert** [comment]
Hi Jason,

What do you mean with 'reloading' in this case. Are you saying that when a custom contact is changed, the global contacts also change and the client needs to see those changes as well?
