### ISSUE TITLE
Return/parse PROPPATCH result in DAV client

### ISSUE THREAD

**Issue by PVince81** [fruux/sabre-dav#726]
From looking at the code in DAV/Client.php it looks like no result is returned.

However usually a PROPPATCH response should contain a list of updated attributes.
This can help finding out whether the target server accepted the attribute or not (correct me if I'm wrong).

Concrete use case: ownCloud as Webdav server accepts PROPPATCH on the "lastmodified" property, but a regular Webdav server doesn't. It would be useful for a client to find out whether setting that property worked.

@evert

**Comment by evert** [comment]
I think we should simply throw an exception for failed `PROPPATCH`, but I do agree that this is a problem.

A `PROPPATCH` must in all cases 100% fail or 100% succeed, so I don't think it's _as_ useful to figure out exactly what individual status codes you got for every operation, but we can still expose that information in the exception.

**Comment by PVince81** [comment]
Makes sense

**Comment by PVince81** [comment]
I sent https://github.com/fruux/sabre-davclient/issues/18 but I realized that there is another "Client.php" in the DAV project. Which one is the correct one ?

Also, I see it's using Sabre\HTTP, so shouldn't it already automatically throw HTTP exceptions ?

**Comment by PVince81** [comment]
Okay, turns out in OC we already set `setThrowExceptions(true)`, so maybe the Apache DAV server doesn't return an error code when trying to set invalid properties.

I saw that in general a PROPPATCH to Sabre will return an XML response will a list of properties. I'd need to check if Apache DAV also does that.

**Comment by DominikTo** [comment]
What you are currently using is probably the Client that is included in `sabre/dav`. The standalone `sabre/dav-client` project is a work in progress.
