### ISSUE TITLE
Modify User-Agent check in CalDAV component to account for Windows 10

### ISSUE THREAD

**Issue by KHismoom** [fruux/sabre-dav#727]
There is a check of the user-agent string in owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php in line 620 to account for a problem with the CalDAV sync client in Windows Phone.
The native Windows 10 calendar app has the same problem (wrongly submitted depth value of 0), but a different user-agent ('MSFT-WIN-3/' instead of 'MSFT-WP/' on Windows Phone).

Modify check in owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php in line 620 to account for this user-agent, so the calendar app in Windows 10 works with OwnCloud, or add a more generic check to account for different (future) versions of Windows (Phone) CalDAV clients. Obviously, they all start with the string 'MSFT-', but I am not sure, if there are different clients that submit a user-agent string matching this pattern, for whom this would break functionality.

**Comment by elvenbone** [comment]
So, in combination with https://github.com/owncloud/calendar/issues/966, we can probably assume, that all Windows 10 platforms are affected (concerning their so-called "modern" apps that use the WINRT framework).
And that they pass a user-agent string of `MSFT-WIN-#` pattern, where:
# is 3 for Windows 10
# is 4 for Windows 10 Mobile
and 1 and 2 may also exist, perhaps for server or IOT/ARM platforms, maybe even more numbers...

Is there any way to implement the fix without the number or with a wildcard?
I don't have the necessary PHP knowledge for that.

**Comment by evert** [comment]
Thanks guys. This is fixed on master!

**Comment by mer-at** [comment]
Nothing is fixed!!!!!

In Owncloud 9:
>             if (strpos($this->server->httpRequest->getHeader('User-Agent'), 'MSFT-WP/') === 0) {

and that does not work with Windows 10 Mobile!
If you change MSFT-WP to MSFT-WIN-4, it works

So please fix that properly ;)

**Comment by RealRancor** [comment]
@mer-at It is fixed in SabreDAV: https://github.com/fruux/sabre-dav/commit/1feeb1bb87c5176ab1c9886c0761c7ac2ef151c4 but only in SabreDAV 3.1.0:

https://github.com/fruux/sabre-dav/blob/3.1/CHANGELOG.md

which is not part of ownCloud 9 ;-)
