### ISSUE TITLE
CardDAV/Backend/PDO.php mysql syntax

### ISSUE THREAD

**Issue by szonov** [fruux/sabre-dav#733]
in CardDAV/Backend/PDO.php on line 131 used mysql specific syntax. 
chars ` should be removed for compatibility with other db drivers.

**Comment by staabm** [comment]
hmm I guess we should also run sqlite related tests in travis to prevent regressions for this kind of situations..

**Comment by evert** [comment]
sqlite tests are actually running, all the time. I'm guessing your running into a postgresql compatibility issue?

**Comment by szonov** [comment]
Yes. Im using postgresql. I see in next function "createAddressBook" query with the same column names, but not escaped. I'm sure that removing escaping of "displayname" and "description" in "updateAddressBook" function will not broke tests.

**Comment by staabm** [comment]
> sqlite tests are actually running, all the time. I'm guessing your running into a postgresql compatibility issue?

actually I meant postgres ;-P

**Comment by evert** [comment]
Yes I would _LOVE_ this. I really need someone to contribute this. Some have tried and stopped. See: #521

**Comment by evert** [comment]
As soon as somebody gets this up and running I promise I will always maintain postgres compatibility. Until then I will only fix things on a case-by-case basis.

**Comment by evert** [comment]
Closing this because no further feedback was provided.
