### ISSUE TITLE
Error on Sabre Dav

### ISSUE THREAD

**Issue by thejoepeach** [fruux/sabre-dav#735]
Fatal error: Uncaught exception 'Sabre_DAV_Exception_BadRequest' in /mounted-storage/home39a/sub003/sc26785-PFHU/freefallmotion.com/files/backend/dav/kloudspeaker_dav.php:379 Stack trace: #0 /mounted-storage/home39a/sub003/sc26785-PFHU/freefallmotion.com/files/backend/dav/index.php(11): require_once() #1 {main} thrown in /mounted-storage/home39a/sub003/sc26785-PFHU/freefallmotion.com/files/backend/dav/kloudspeaker_dav.php on line 379

Any Clue?

**Comment by evert** [comment]
Hi @thejoepeach , I believe this is a ticket you should open at whoever implemented sabredav here.
This error is not specific to sabre/dav, but rather a developer who integrated sabre/dav in their application.
