### ISSUE TITLE
Errors in migrateto20.php script

### ISSUE THREAD

**Issue by pageer** [fruux/sabre-dav#739]
I just upgraded SabreDAV from 1.8.5 to 3.0.5 and encountered a couple of errors while running the migrateto20.php script.  Both errors cause the script to bomb out with an exception before completing.  The attached diff corrects them.  

The first was a logic error in the addressbook/calendar switch/case.  The block contains nested switch/case statements, but there are only break statements for the inner switches (on table name), so evaluation always falls through in the MySQL case for the outer switch.  The second error was a stray comma in the create table statement for the cards table.
[migrateto20-patch.txt](https://github.com/fruux/sabre-dav/files/75702/migrateto20-patch.txt)

**Comment by evert** [comment]
This is very confusing... did you send the opposite patch of what you intended?

**Comment by evert** [comment]
Note that you can just hit the 'edit' button on this page and make the changes in-line, it's a much better way to make contributions:

https://github.com/fruux/sabre-dav/blob/master/bin/migrateto20.php

**Comment by pageer** [comment]
Oops!  Yeah, sorry, looks like I did the diff backwards.
I never noticed GitHub even had an edit button on files, so I'll just do that then.

**Comment by pageer** [comment]
I edited file and submitted pull request, so I guess this can be closed now.
