### ISSUE TITLE
Broken generation of multistatus responses

### ISSUE THREAD

**Issue by jakobsack** [fruux/sabre-dav#751]
**Problem:** in rare cases the structure of `Sabre\DAV\Xml\Element\Response::$responseProperties` differs from the usual structure

**Expected result** The structure of the data should be like 
```php
array(2) {
  [200]=>
  array(1) {
    ["{DAV:}supportedlock"]=>
    object(Sabre\DAV\Xml\Property\SupportedLock)#2756 (0) {
    }
  }
  [404]=>
  array(0) {
  }
}
```

**Actual result** The test `testMKCOLAndProps` returns the following structure
```php
array(1) {
  ["{DAV:}displayname"]=>
  int(403)
}
```

**Reproduction steps**

1. Inserting `var_dump($this->getResponseProperties());` in `lib/DAV/Xml/Element/Response.php` after line 125 (as of commit 6293220)
2. Remove the two `@depends`-tags in `tests/Sabre/DAV/ServerMKCOLTest.php` on lines 313 and 314 to run this test alone
3. run the tests `phpunit --configuration tests/phpunit.xml tests/Sabre/DAV`
4. run the test `phpunit --configuration tests/phpunit.xml --filter testMKCOLAndProps tests/Sabre/DAV`
5. compare the output of the var_dumps in both cases.

**Comment by evert** [comment]
Thanks @jakobsack , super appreciated as usual.
