### ISSUE TITLE
Principal with name calendar-proxy-read not found

### ISSUE THREAD

**Issue by christophdb** [fruux/sabre-dav#755]
Hi everybody,
I am quite new to sabre-dav but I didn't get it why it is not working. I installed sabre-dav with caldav support like described on sabre.io.
I can enter the webpage and navigate to all layers. There is only one link that is not working. If I click on "calendar-proxy-read" it gives me always the same error message. 

Does anybody has an idea what I forgot?
Here two screenshots:

![calendarserver2](https://cloud.githubusercontent.com/assets/7803347/12199555/4010ed42-b619-11e5-8658-fb706531319f.png)
![calenderserver](https://cloud.githubusercontent.com/assets/7803347/12199556/4012318e-b619-11e5-8534-49c7be21bd97.png)

Thanks and best regards
Christoph

**Comment by evert** [comment]
Confirmed
