### ISSUE TITLE
ownCloud connecting to sabreDAV... 

### ISSUE THREAD

**Issue by kantakt2** [fruux/sabre-dav#766]
Hi I got sync error. In ownCloud Window's client. I think error may be connected near to    <d:status>HTTP/1.1 404 Not Found</d:status> - in responce.
But files are showing, uploading ok.
Any ideas, guys?
Alex.

Req/Resp - in the attachment
[Charlie.txt](https://github.com/fruux/sabre-dav/files/100842/Charlie.txt)

**Comment by evert** [comment]
You should report owncloud bugs in the owncloud project. Owncloud is just a sabredav user.
