### ISSUE TITLE
Support for utf8mb4

### ISSUE THREAD

**Issue by schmimat** [fruux/sabre-dav#769]
Hallo

as described in this articles
•	https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-upgrading.html
•	https://mathiasbynens.be/notes/mysql-utf8mb4
•	http://tonyshowoff.com/articles/better-unicode-support-for-mysql-including-emoji/

I think the mysql statements for creating the database tables should be modified.

In *mysql.addressbook.sql*
*displayname VARCHAR(255), --> displayname VARCHAR(100),*

like in *mysql.calendars.sql*

or using 
*displayname VARBINARY* ?

Is this correct?

Best regards

mfG Matthias

**Comment by evert** [comment]
We've already switches to utf8mb4 some time ago. Changing the length of the VARCHAR fields wouldn't do much I think though.
