### ISSUE TITLE
Logging of XML-Status to nginx-log

### ISSUE THREAD

**Issue by christophdb** [fruux/sabre-dav#771]
Hi everybody,
If there is an error in sabredav (like wrong credentials or bad ldap_bind) it show me the ErrorExeption as xml on the browser.

My question:
Is it possible to write in addition the ip of the requestor and the XML-Error or ErrorException to a log-file?

The main purpose is to use fail2ban to check for multiple wrong login-attempts. To reach that goal I need the IP of the requestor and any kind of error message in any log file.

Thanks you very much for every hint.
Best regards
Christoph

**Comment by evert** [comment]
Yea you could intercept the `exception` event and do something with that:

http://sabre.io/dav/writing-plugins/
