### ISSUE TITLE
Windows 7 fetching entire file on selection

### ISSUE THREAD

**Issue by DannyZB** [fruux/sabre-dav#773]
Whenever I right-clicked a file from a webdav share on windows 7, Explorer would freeze for minutes.

I set up charles proxy to see what's happening - and to my surprise - it is fetching the entire file when you click on it !

Is this a known issue ? what causes this?

**Comment by evert** [comment]
I can't say for certain if it would have been possible for Windows in this case to do a partial fetch using range requests. I imagine that right-clicking triggers something in the operating system that causes it to want access to the contents of the file. The only option the client then has (given that it doesn't do range, request, which I'll assume ... ) is to download the entire file.

I don't know if there's a workaround for this. You might want to try a more optimized client instead.
