### ISSUE TITLE
Hook to get attendee's event path

### ISSUE THREAD

**Issue by strokyl** [fruux/sabre-dav#775]
Hello Saber folks!

When an organizer push an event creation or an event modification to the Sabre, is there a way to get by a hook or something similar the event's path of created event in attendee's calendars ?

**Comment by evert** [comment]
There's two things that could help you get there, first, there's `schedule` event that you can hook into to listen for any changes. Documented here:

http://sabre.io/dav/writing-plugins/

Second, when sabre/dav itself receives a `schedule` event, it must itself find the 'attendee copy' of the event to make the updates there. There's not one function to do this, but here is the code of sabre/dav doing this internally:

https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Schedule/Plugin.php#L443

It's pretty much from that line, and then until this line:

https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Schedule/Plugin.php#L512

That's quite a bit of lines, so I'll break down the (relevant) steps.

1. We ask for the `principal uri` for the email address associated to the scheduling message.
2. On the `principal uri`, we ask for the `calendar-home-set` uri.
3. Then we extract the `UID` property from the scheduling message.
4. On the calendar-home-set, we call 'getCalendarObjectByUID`.

That last method actually returns a path for a calendar object, based on a iCalendar `UID` property, and that's literally what you asked.

Hope this helps!
