### ISSUE TITLE
Sabre XML response is missing encoding

### ISSUE THREAD

**Issue by PVince81** [fruux/sabre-dav#776]
I'm no XML standard expert, but we noticed that since the upgrade to Sabre 3.0 which uses the new serializer, the XML responses' header tag looks like:

```xml
<?xml version="1.0"?>
```

instead of what it was in the past:
```xml
<?xml version="1.0" encoding="utf-8"?>
```

It seems to be because when calling `startDocument` on PHP's XMLWriter, it doesn't pass any encoding and the default encoding is "NULL": http://php.net/manual/en/function.xmlwriter-start-document.php

**Comment by PVince81** [comment]
https://github.com/fruux/sabre-xml/blob/master/lib/Service.php#L186

**Comment by evert** [comment]
UTF-8 is the default encoding for XML. Parsers should basically be able to pick this up without issue. Are you running into issues with a client?

**Comment by staabm** [comment]
Per https://github.com/owncloud/core/issues/22326 it sounds like iOS has issues

**Comment by evert** [comment]
I find that a bit doubtful. Been happily syncing with iOS on sabre/dav 3 for months.

**Comment by PVince81** [comment]
I think it's the ios ownCloud client, not caldav/carddav. Either they are using a lib that doesn't parse properly or they mixed it up with another issue.
We could first try patching sabre xml locally in ownCloud to check whether that is the case.

**Comment by evert** [comment]
Alright. I'd definitely in the first place say that the bug is there, and not in sabre/dav. For that reason I'll close this ticket. If this proves impossible to fix on that end we can always discuss this again.
