### ISSUE TITLE
Composer only updates tp saber/dav 3.07

### ISSUE THREAD

**Issue by Kcm75** [fruux/sabre-dav#777]
I am trying to update to version 3.1, but with composer update, it only gets me 3.0.7.
Do I need to change the composer JSON files?

Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing sabre/http (4.1.0)
  - Installing sabre/http (4.2.1)
    Downloading: 100%         

  - Removing sabre/xml (1.2.0)
  - Installing sabre/xml (1.3.0)
    Downloading: 100%         

  - Removing sabre/vobject (3.4.7)
  - Installing sabre/vobject (3.5.0)
    Downloading: 100%         

  - Removing sabre/dav (3.0.6)
  - Installing sabre/dav (3.0.7)
    Downloading: 100%

**Comment by evert** [comment]
I assume that your composer.json will have a line that says something like:

    "sabre/dav" : "~3.0.0"

This will only install sabre/dav versions starting with `3.0`. So you do indeed need to change this to:

    "sabre/dav" : "~3.1.0"
