### ISSUE TITLE
Implement Doctrine connector instead of PDO

### ISSUE THREAD

**Issue by smalot** [fruux/sabre-dav#778]
To fit Symfony standard, I propose to implement Doctrine connector instead of PDO.
Basically I planed to generate a `plugin` as another composer package, but I think it's better to merge my work with this wonderful project.

Would you be interested on ?

**Comment by evert** [comment]
What would the advantage be?

**Comment by smalot** [comment]
Use the same connection as the rest of the application (if integrated in an app), a better integration with Symfony ecosystem such event listeners, and much more I hope.

**Comment by smalot** [comment]
I still need to work on Card backend, but here is a sample code:

````php
/**
 * Class CalController
 *
 * @package DavBundle\Controller
 *
 * @Route("/dav/cal")
 */
class CalController extends Controller
{
    /**
     * @Route("/{token}", name="dav_cal_index", requirements={"token"=".*"}, defaults={"token"=""})
     */
    public function indexAction()
    {
        $baseUri = $this->generateUrl('dav_cal_index');

        /** @var \Doctrine\ORM\EntityManager $entityManager */
        $entityManager = $this->get('doctrine.orm.default_entity_manager');

        /**
         * The backends. Yes we do really need all of them.
         *
         * This allows any developer to subclass just any of them and hook into their
         * own backend systems.
         */
        $authBackend      = new \Sabre\DAV\Auth\Backend\Doctrine($entityManager);
        $principalBackend = new \Sabre\DAVACL\PrincipalBackend\Doctrine($entityManager);
        $caldavBackend    = new \Sabre\CalDAV\Backend\Doctrine($entityManager);

        /**
         * The directory tree
         *
         * Basically this is an array which contains the 'top-level' directories in the
         * WebDAV server.
         */
        $nodes = array(
            // /principals
          new \Sabre\CalDAV\Principal\Collection($principalBackend),
            // /calendars
          new \Sabre\CalDAV\CalendarRoot($principalBackend, $caldavBackend),
        );

        // The object tree needs in turn to be passed to the server class
        $server = new \Sabre\DAV\Server($nodes);
        $server->setBaseUri($baseUri);

        // Plugins
        $server->addPlugin(new \Sabre\DAV\Auth\Plugin($authBackend, 'SabreDAV'));
        $server->addPlugin(new \Sabre\DAV\Browser\Plugin());
        $server->addPlugin(new \Sabre\CalDAV\Plugin());
        $server->addPlugin(new \Sabre\DAVACL\Plugin());

        // And off we go!
        $server->exec();

        exit(0);
    }
}
````

**Comment by evert** [comment]
Well, sabre/dav is not at all a symfony application. It's very unlikely for me to use symfony components as they are all rather massive and with huge dependency graphs. I can see myself use other dependencies if they are small and focused.

Can't you get access to the underlying PDO object from Doctrine?

However, if you are interested in creating the `Doctrine` backend classes (next to all the PDO ones) I _do_ think it could be useful as a second option. However, I think these classes need to live in a separate composer package such as `sabre/dav-doctrine`.

That package can then depend on both doctrine and sabredav, and helps doctrine users such as yourself, but does not make the dependency graph bigger for those that don't care about doctrine.

How does that sound? Are you interested in doing this?

**Comment by smalot** [comment]
Sounds good for me.

But if updates are made on PDO classes, they need to be made on Doctrine classes as well.
If integrated to the `fruux/sabre-dav` core repo, I guess they evolve at the same time because maintained by the same team.
Currently I have few time to create this package, but I'm afraid I won't be able to maintain it in the future.

Unless you will maintain the `sabre/dav-doctrine` too.

Do you see what I mean ?

For now I have updated `composer.json` by adding 'doctrine/orm' as suggest package.

That's as you like, I'm totally open to the best development.

**Comment by evert** [comment]
I agree that it will need a maintainer. At the very least you can be confident that if you use sabre-dav `^3.1.0` as a dependency, it will not break.

But when we release 3.2.0 it might. At that point we might have time to bring it up to date, or we ask contributors to help us bring it to that point.

I think the best thing would be if we simply state a message on the `README.md` that we don't officially support this package, and it exists for people who are interested to use doctrine instead. I can't guarantee we can keep it up to date, because we already have a lot of maintenance work, and I don't want to further increase that.

So if you are still interested in doing this, after all that... I can create a new github repository and make you a maintainer. Best would be to use this package as the 'template' for a new sabre package, as we use that everywhere:

https://github.com/fruux/sabre-skel

**Comment by smalot** [comment]
Still ok for me.
Don't hesitate to review my releases.

**Comment by staabm** [comment]
> Can't you get access to the underlying PDO object from Doctrine?

I feel we should discuss this point. In case this is possible we would not need any "unsupported classes" etc.

**Comment by smalot** [comment]
Sounds good for me.
I don't want to use all entity layers provided by Doctrine.
Currently I've rewritten parts of PDO calls using Doctrine native queries to avoid any over-consumption of memory.

**Comment by staabm** [comment]
Doctrine uses a `PDOConnection` class which is a subclass of `PDO`.
Therefore you can simple pass your PDOConnection from Doctrine into sabre-dav and you should need any adjustments on the sabre-dav side, no?

**Comment by smalot** [comment]
I'll check that ASAP

**Comment by smalot** [comment]
Found:

````php
/** @var \Doctrine\ORM\EntityManager $entityManager */
$entityManager = $this->get('doctrine.orm.default_entity_manager');

/** @var \Doctrine\DBAL\Driver\PDOConnection $pdo */
$pdo = $entityManager->getConnection()->getWrappedConnection();
````

or

````php
/** @var \Doctrine\DBAL\Connection $db */
$db = $this->get('doctrine.dbal.default_connection');

/** @var PDOConnection $pdo */
$pdo = $db->getWrappedConnection();
````

I agree it's working, but that's quite awful.

**Comment by staabm** [comment]
Why/what exactly is awfull?

**Comment by evert** [comment]
I don't get that either. If your end-goal is to simply re-use the connection object, then this is by far the most elegant solution. 2 lines of code definitely beats having to write and maintain entity classes for every bit of data.
