### ISSUE TITLE
CardDAV: Falsly encoded KEY field produces corrupt XML

### ISSUE THREAD

**Issue by timdrub** [fruux/sabre-dav#783]
Hi,

I use Outlook CalDAV Synchronizer to bi-directionally sync contacts between Outlook/Office365 and SabreDAV. On the other end there is Thunderbird and the SoGo Connector to make the contacts available in TB.

If I now add a certificate to an outlook contact it is uploaded to SabreDAV and further synced to the TB addressbook. I then opened the contact and directly closed it in TB. This results in an upload of the object to SabreDAV again. It seems as if this is where the KEY field gets messed with.

As a result SabreDAV serves corrupt XML and the sync back to Outlook fails. In fact, other clients (e.g. InfCloud stop working, too).

Here is a link to the thread I had with a OLK CalDAC Synchronizer developer:
[https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/217/](https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/217/)

I guess the issue lies with the SoGo Connector, but shouldn't SabreDAV accept the corrupt object in the first place and furthermore, this shouldn't lead to SabreDAV serving corrupted XML, should it?

Thanks for your help.

Regards
Tim

**Comment by aluxnimm** [comment]
Same problem with SOGo itself, SOGO connector destroys the encoding of the KEY attribute, SOGo accepts it and delivers an invalid encoded KEY to caldav clients. @timdrub did you create a ticket for sogo-connector, since there is the main cause.

**Comment by evert** [comment]
I'm having a little bit of trouble understanding the issue. Basically if I understand it correctly:

1. SOGo sends an invalid vcard
2. sabre/dav accepts it (it shouldn't)
3. sabre/dav then later on serves broken xml (it shouldn't)

If this is true then these are three distinct bugs, and I'd like to fix the last two. Would you be able to share a sample (broken) vcard that I could use to send to sabre/dav to reproduce the issue?

**Comment by aluxnimm** [comment]
not sogo but sogo-connector for thunderbird destroys the encoding for the key attribute.

e.g. we send KEY;ENCODING=b;TYPE=X509:<base64 cert> to a caldav server.
sogo-connector gets the vcard from the server
when you save it in Thunderbird again  sogo-connector stripes the encoding and sends it back decoded.
now invalid characters are in the vcard on the server ( sogo or sabre-dav doesn't matter, both accept It) and serve it back to clients.

**Comment by evert** [comment]
Right, I forget that there's two products with similar names.

**Comment by timdrub** [comment]
Hi,

this is what the vcf looks like when downloaded from SabreDAV. Also attached. Is this sufficient?

Regards
Tim

`BEGIN:VCARD
VERSION:3.0
PRODID:-//Inverse inc.//SOGo Connector 1.0//EN
UID:C6F57510-12D0-0001-AD93-1CE01D1E1CB5.vcf
N:Drub;Tim;;;
FN:Tim Drub
X-MOZILLA-HTML:FALSE
EMAIL;TYPE=work:tim.drub@gmail.eu
KEY:0!0	 ç\;0	*H÷
CLASS:PUBLIC
END:VCARD`

[C6F57510-12D0-0001-AD93-1CE01D1E1CB5.vcf.zip](https://github.com/fruux/sabre-dav/files/135090/C6F57510-12D0-0001-AD93-1CE01D1E1CB5.vcf.zip)

**Comment by evert** [comment]
Great! I'll take a look soonish

**Comment by timdrub** [comment]
Created the ticket with SOGo:
[http://sogo.nu/bugs/view.php?id=3535](http://sogo.nu/bugs/view.php?id=3535)

**Comment by aluxnimm** [comment]
Any news on this?

**Comment by evert** [comment]
Well, the main problem is with SOGo, but my plans for sabre/dav 3.2 are to automatically run validate/repair on every incoming vCard and iCalendar object. Adding that feature will catch this.

**Comment by aluxnimm** [comment]
thank you. that will help interopability with various clients a lot in the future! hopefully SOGo can implement something similar.

**Comment by evert** [comment]
This is implemented on the master branch.
