### ISSUE TITLE
CalDAV does not accept custom principals paths

### ISSUE THREAD

**Issue by TCKnet** [fruux/sabre-dav#785]
Would be great if it could be similar to CardDav.
In Sabre/CalDAV/Plugin.php, update the function as follows:

  function getCalendarHomeForPrincipal($principalUrl) {
    list(, $principalId) = \Sabre\HTTP\URLUtil::splitPath($principalUrl);
    return self::CALENDAR_ROOT . '/' . $principalId;
  }

**Comment by TCKnet** [comment]
The current code https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Plugin.php#L98
assumes that 1) the principal path has two components and 2) the first one is hardcoded to "principals", which sounds like a regression to me. Should the exclusion for the calendar proxies(?) be reworked? Is there an RFC constraint that all principals should be exactly below principals/ ? (If so, why develop on custom paths for users & groups in http://sabre.io/dav/principals/? I'm experimenting with that and hope to help by reporting issues/fixes that could be integrated in sabre).

**Comment by evert** [comment]
Yes. Sorry for the lack of response here. But indeed, subclassing and overriding that function is the way to go there. I'd be ok with slightly altering that function to be more like the carddav one, especially when given a patch for it ;)
