### ISSUE TITLE
[regression] Cannot use non-seekable stream wrappers with range requests

### ISSUE THREAD

**Issue by PVince81** [fruux/sabre-dav#787]
In Sabre 2.1, the CorePlugin was checking the result of `fseek` when using range requests.
If fseek failed, it would read enough bytes to reach the correct position.
https://github.com/fruux/sabre-dav/blob/2.1/lib/DAV/CorePlugin.php#L177

In Sabre 3, the result of fseek is not checked for errors any more: https://github.com/fruux/sabre-dav/blob/3.0/lib/DAV/CorePlugin.php#L176
A `stream_get_meta_data` checks the "seekable" property of the stream.

The problem is that stream wrappers always advertise themselves as seekable, even when the wrapped stream isn't. This is what we observed and was also observed by other people here http://php.net/manual/en/function.stream-get-meta-data.php#115608

It seems there is no way for a stream wrapper to control what data is returned by `stream_get_meta_data`, so using this cannot be used to safely check for seekability.

Please revert back or add a check for the `fseek` call.

@evert

**Comment by PVince81** [comment]
Ref https://github.com/owncloud/core/issues/22476 in which case the wrapped stream is a Guzzle response (curl).

**Comment by staabm** [comment]
could we detect whether the stream is provided using a custom-wrapper?

**Comment by PVince81** [comment]
Even if you could, how would you change the code to make it work ?
There are situations where the custom wrapper is wrapping a seekable stream and fseek will work.
In other situations where the underlying stream is not seekable, fseek would not work.

**Comment by evert** [comment]
I think just calling fseek and see if it did anything does indeed sound the sanest. Sucks that streams is in such a poor state in PHP.
