### ISSUE TITLE
Missing IACLs in several nodes - feature propsal

### ISSUE THREAD

**Issue by TCKnet** [fruux/sabre-dav#788]
Hello,

I'm trying to enforce Sabre\DAVACL\Plugin()->allowAccessToNodesWithoutACL = false; and it seems that some nodes are not implementing Sabre\DAVACL\IACL. I ran into:
- Sabre\CalDAV\Principal\Proxy{Read,Write}
- Sabre\CardDAV\AddressBookRoot
- Sabre\CalDAV\CalendarRoot
- Sabre\DAV\SimpleCollection (arguable if you do not want to use ACLs at all, but is annoying if you pass an array of nodes to the server, then the root will not be visible)

I solved this problem by using a trait in the above classes, and I'd like to integrate it now into sabre-dav. This could also reduce the boilerplate in other classes and testing.

```
trait SimpleACL {
  protected $owner=null, $group=null, $acl=[['principal'=>'{DAV:}authenticated', 'privilege'=>'{DAV:}read', 'protected'=>true]];
  protected function initACL($acl,$owner=null,$group=null) { $this->acl=$acl; $this->owner=$owner; $this->group=$group; }
  function getOwner() { return $this->owner; }
  function getGroup() { return $this->group; }
  function getACL() { return $this->acl; }
  function setACL(array $acl) { throw new Forbidden('Setting ACL is not allowed here'); }
  function getSupportedPrivilegeSet() { return null; }
}
```

Usage:
`class MySimpleCollection extends DAV\SimpleCollection implements DAVACL\IACL { use SimpleACL; }`
and if you want to be more specific, call initACL() in the class constructor.

Let me know if/how you want to integrate (and maybe the trait should be renamed ReadOnlyACL).

**Comment by TCKnet** [comment]
Here is a patch for that. I didn't write unit tests but I tried it on my setup and it worked as expected.

[patch.diff.txt](https://github.com/fruux/sabre-dav/files/149858/patch.diff.txt)

**Comment by TCKnet** [comment]
Also I think that the ACLs for 1) /principals/$user/ and 2) /principals/$user/calendar-proxy-{read,write}
should be instead
```
[
    ['privilege' => '{DAV:}read', 'principal' => '{DAV:}authenticated', 'protected' => true],
    ['privilege' => '{DAV:}all', 'principal' => $user, 'protected' => true],
]
```
so that 1) $user is allowed to change his displayname and 2) he can grant access to his calendars.

**Comment by evert** [comment]
I think turning this into a trait is a good idea, but a few caveats:

1. Instead of setting the trait to some of the root nodes, I would really just like to add a feature that acts as a 'default acl' for all nodes that don't have IACL set. I think this makes more sense for for example the root nodes. Adding this feature means we can remove the `$allowAccessToNodesWithoutACL` feature, which I agree is too dumb/simplistic.
2. It makes total sense to use this trait in all existing classes where IACL is now implemented 'manually'. It will save a lot of boilerplate!
3. It also makes a lot of sense to add it to the proxy principals and stuff.
4. But we can't add it to any nodes in the `Sabre\DAV` namespace, such as `SimpleCollection`. The `DAV` package is not allowed to have _any_ dependencies on `DAVACL`.

**Comment by TCKnet** [comment]
1) allowAccessToNodesWithoutACL could be transformed to assume that if the node doesn't implement IACL, it is equivalent to 
```
[ ['privilege' => '{DAV:}read', 'principal' => '{DAV:}authenticated', 'protected' => true] ]    
```
to do that maybe change getCurrentUserPrivilegeSet($node) line 509 not to return the above instead of null? (and remove allowAccessToNodesWithoutACL).

2) See my patch

3) These need to have write access for the owner to make sense, this is not in the patch, be careful.

4) I didn't added it to the SimpleCollection due to that dependencies concern. Solution is (1) above, or possibly have a DAVACL\SimpleCollection that implements DAVACL\IACL.

**Comment by evert** [comment]
> 1) allowAccessToNodesWithoutACL could be transformed to assume that if the node doesn't implement IACL, it is equivalent to 

Yea I like this. I think we need a better default here, and if we get rid of `allowAccessToNodesWithoutACL` and instead call it something like `defaultACL` I think it gives people a lot more flexibility.

**Comment by evert** [comment]
All of these things have now been implemented on the master branch.
