### ISSUE TITLE
Missing header field in IMIP

### ISSUE THREAD

**Issue by controlcde** [fruux/sabre-dav#790]
While accepting an event an email will be sent to organizer but it depends on the participant email servers the message will be transported or not. In my case (and maybe on others) the missing date field in header will cause a non delivered email. So the "date" header field should be add to any message.

**Comment by controlcde** [comment]
Or is this a problem of OSX (which seams to send the acceptance message?!

**Comment by evert** [comment]
I have never heard of this problem before. It could well be a OS X issue, but I've never ran into it myself. Have you heard of other people running into a similar issue on OS X?

**Comment by controlcde** [comment]
Well I´ve researched and now I know that iCal sends an email via mailsupport and I could see in my mail server log from amavisd-new
```
Passed BAD-HEADER-7
```
so I think the problem should be iCal and not SabreDAV :).

**Comment by evert** [comment]
Hmm.. so this ticket can close?

**Comment by controlcde** [comment]
Yes, I think so :).
