### ISSUE TITLE
Windows10 support on 3.0?

### ISSUE THREAD

**Issue by nickvergessen** [fruux/sabre-dav#799]
Would be nice, if https://github.com/fruux/sabre-dav/commit/1feeb1bb87c5176ab1c9886c0761c7ac2ef151c4 could be backported to the 3.0 branch, so ownCloud can support windows 10 ;)

cc @DeepDiver1975 

Ref https://decatec.de/home-server/owncloud-unter-windows-10-optimal-nutzen/

**Comment by evert** [comment]
I don't really see an issue with that

**Comment by evert** [comment]
This was merged.

**Comment by nickvergessen** [comment]
Any plan for the next release already? I know you just did one 24days ago, but would help on our side a bit ;)

**Comment by evert** [comment]
If I can manage it, I will try doing a release today.
