### ISSUE TITLE
CalDAV - It does not work with ios 12

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [fruux/sabre-dav#813]
I got SabreDAV 3.1.2 i launched CardDAV and it works well, but I have a problem with launching CalDAV.
I tried on a computer with IOS7 but it won't work.  The web version works well with an android device (with DAVdroid), the problem only occurs on IOS.
Seems like it connects me with CalDAV, but won't show calendars.

When I go to the calendar I get the message : The server shows invalid initial position of the calendar

A: http://sabredav.yetiforce.com/index.php
L: admin
P: admin

**Comment by mariuszkrzaczkowski** [comment]
How can I debug this type of errors ??

**Comment by evert** [comment]
This is all a bit weird because you mention iOS 12, which afaik iOS 9 is the latest. iOS 7 is pretty old though, but it should work.

I've also never seen "The server shows invalid initial position of the calendar" before. Is that a translation of a localized error message?

Regardless, the best way to debug issues like this is by:

* Installing Charles HTTP Proxy
* Setting up your iOS device (network settings) to us the proxy
* Try setting up caldav again, and then looking in charles if there are any problems. You can also send the charles session to me if you'd like me to analyze it.

**Comment by evert** [comment]
However, I noticed that this was not setup:

http://sabredav.yetiforce.com/.well-known/caldav

If you make sure that that url works, and is a redirect to:

http://sabredav.yetiforce.com/index.php/

It might solve the problem.

**Comment by mariuszkrzaczkowski** [comment]
I was wrong, I got OS X Mavericks 10.9.
I'm attaching a screenshot that illustrates the error, but only in Polish language
![os x mavericks-2016-04-05-15-28-19](https://cloud.githubusercontent.com/assets/10198654/14284240/f4a96c08-fb46-11e5-95f3-ea12fae11a4c.png)

Maybe it's giving a wrong address?
http://sabredav.yetiforce.com/index.php/
http://sabredav.yetiforce.com/index.php/calendars/admin/testcalendar/

I'm including the logs, maybe they'll help

 --- 2016-04-05 09:27:59 --- RequestInterface --- 
PROPFIND /index.php/ HTTP/1.1
Content-Length: 743
Content-Type: text/xml
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: pl-pl
Authorization: Digest REDACTED
Brief: t
Connection: keep-alive
Depth: 0
Host: sabredav.yetiforce.com
Prefer: return-minimal
User-Agent: Mac_OS_X/10.9 (13A476u) CalendarAgent/157.1

<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <B:calendar-home-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:calendar-user-address-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:current-user-principal/>
    <A:displayname/>
    <C:dropbox-home-URL xmlns:C="http://calendarserver.org/ns/"/>
    <C:email-address-set xmlns:C="http://calendarserver.org/ns/"/>
    <C:notification-URL xmlns:C="http://calendarserver.org/ns/"/>
    <A:principal-collection-set/>
    <A:principal-URL/>
    <A:resource-id/>
    <B:schedule-inbox-URL xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:schedule-outbox-URL xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:supported-report-set/>
  </A:prop>
</A:propfind>
 --- 2016-04-05 09:27:59 --- ResponseInterface --- 
HTTP/1.1 207 Multi-Status
X-Sabre-Version: 3.1.2
Content-Type: application/xml; charset=utf-8
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, calendar-access, calendar-proxy, addressbook, calendarserver-subscribed, calendar-auto-schedule, calendar-availability

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav">
 <d:response>
  <d:href>/index.php/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
 --- 2016-04-05 09:27:59 --- RequestInterface --- 
OPTIONS /index.php/ HTTP/1.1
Content-Length: 0
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: pl-pl
Authorization: Digest REDACTED
Connection: keep-alive
Host: sabredav.yetiforce.com
User-Agent: Mac_OS_X/10.9 (13A476u) CalendarAgent/157.1

 --- 2016-04-05 09:27:59 --- ResponseInterface --- 

 --- 2016-04-05 09:30:09 --- RequestInterface --- 
PROPFIND /index.php/calendars/admin/testcalendar/ HTTP/1.1
Content-Length: 743
Content-Type: text/xml
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: pl-pl
Authorization: Digest REDACTED
Brief: t
Connection: keep-alive
Depth: 0
Host: sabredav.yetiforce.com
Prefer: return-minimal
User-Agent: Mac_OS_X/10.9 (13A476u) CalendarAgent/157.1

<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <B:calendar-home-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:calendar-user-address-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:current-user-principal/>
    <A:displayname/>
    <C:dropbox-home-URL xmlns:C="http://calendarserver.org/ns/"/>
    <C:email-address-set xmlns:C="http://calendarserver.org/ns/"/>
    <C:notification-URL xmlns:C="http://calendarserver.org/ns/"/>
    <A:principal-collection-set/>
    <A:principal-URL/>
    <A:resource-id/>
    <B:schedule-inbox-URL xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <B:schedule-outbox-URL xmlns:B="urn:ietf:params:xml:ns:caldav"/>
    <A:supported-report-set/>
  </A:prop>
</A:propfind>
 --- 2016-04-05 09:30:09 --- ResponseInterface --- 
HTTP/1.1 207 Multi-Status
X-Sabre-Version: 3.1.2
Content-Type: application/xml; charset=utf-8
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, calendar-access, calendar-proxy, addressbook, calendarserver-subscribed, calendar-auto-schedule, calendar-availability

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav">
 <d:response>
  <d:href>/index.php/calendars/admin/testcalendar/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <cal:calendar/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
 --- 2016-04-05 09:30:10 --- RequestInterface --- 
OPTIONS /index.php/calendars/admin/testcalendar/ HTTP/1.1
Content-Length: 0
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: pl-pl
Authorization: Digest REDACTED
Connection: keep-alive
Host: sabredav.yetiforce.com
User-Agent: Mac_OS_X/10.9 (13A476u) CalendarAgent/157.1

 --- 2016-04-05 09:30:10 --- ResponseInterface ---

**Comment by evert** [comment]
Hmm.. I don't believe that the requests and responses match exactly, as either of those requests should have also returned `current-user-principal`. But regardless, you should try using the "principal url" for setup. This url will probably look like this for you:

http://sabredav.yetiforce.com/index.php/principals/admin/

**Comment by evert** [comment]
No further feedback received.
