### ISSUE TITLE
Problem with VAlarms

### ISSUE THREAD

**Issue by GrahamLinagora** [fruux/sabre-dav#819]
Hello!

We are building a CalDav client on top of a SabreDav server with a custom mongo backend, and we currently are adding the alarm feature.
Our goal is to have, for each attendee, the possibility to define his/her alarms for himself/herself independantly of other attendees.

The problem we encounter is : 
- Having an event with an organizer and an attendee.
- If the attendee adds VAlarm: only his copy of the ICS is updated with this new component.
- If the organizer adds a VAlarm and sends the ICS to Sabre: this VAlarm is added to the organizer ICS and is copied into the attendee ICS.
(We observed similar behavior using ThunderBird as a client)

So our main problem is that the organizer erases other attendees alarms with the one he/she created. And we find it weird that Sabre handles differently the changes for VAlarms depending on attendee/organizer status.

Is it a normal behavior of a CalDAV server ?
If it is normal, is there a helper/feature to help us with this in Sabre ?
If it is not, what should we change in the server ?

Thanks in avance for your answer

**Comment by evert** [comment]
Sorry for the late reply. I believe that you are correct in that we *should* strip VALARM from invitations, before delivering them and that we don't do that today.

I also agree that it would be best to merge any existing VALARM in the object. This really should just become a feature request for the https://github.com/fruux/sabre-vobject project.

**Comment by GrahamLinagora** [comment]
I created the corresponding feature request in sabre-vobject
