### ISSUE TITLE
A node has the "{DAV:}share" in its ACL list, but this privilege was not reported in the supportedPrivilegeSet list

### ISSUE THREAD

**Issue by manubaum** [fruux/sabre-dav#833]
In version 3.2.0-alpha1, after the installation, when creating a new ('default') calendar in the browser as explained in http://sabre.io/dav/caldav/ the following exception occurs:

```
3.2.0-alpha1 Sabre\DAV\Exception A node has the "{DAV:}share" in its ACL list, but this privilege was not reported in the supportedPrivilegeSet list
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.0-alpha1</s:sabredav-version>
<s:exception>Sabre\DAV\Exception</s:exception>
<s:message>
A node has the "{DAV:}share" in its ACL list, but this privilege was not reported in the supportedPrivilegeSet list
</s:message>
<s:message>...</s:message>
</d:error>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">...</d:error>
```

Note that the expected entries in 'calendarinstances' are created thouhg. However, this exception is persistent, rendering the functionality broken.

**Comment by evert** [comment]
Confirmed. A workaround you can do right now is to call `$server->addPlugin(new Sabre\DAV\Sharing\Plugin());` but this should not error, so definitely a bug.

**Comment by manubaum** [comment]
Thanks. The workaround is fine.
