### ISSUE TITLE
cards are rewritten on retrieval

### ISSUE THREAD

**Issue by mbiebl** [fruux/sabre-dav#834]
This is a followup for https://groups.google.com/d/msg/sabredav-discuss/VTqllUhSl4k/rwNE8TUcAgAJ

To reproduce the problem, I did the following

1/ create composer.json pulling in sabre/dav 3.1.*
```
  - Installing sabre/uri (1.1.0)
    Downloading: 100%         

  - Installing sabre/event (3.0.0)
    Loading from cache

  - Installing sabre/http (4.2.1)
    Downloading: 100%         

  - Installing sabre/xml (1.4.1)
    Downloading: 100%         

  - Installing sabre/vobject (4.1.0)
    Loading from cache

  - Installing sabre/dav (3.1.3)
    Loading from cache
```
2/ Create a server.php based on ./vendor/sabre/dav/examples/addressbookserver.php, setup mysql as backend
3/ Create a "sabredav" database and load ./vendor/sabre/dav/examples/sql/mysql.*.sql
4/ Use the browser plugin to login as admin/admin
5/ Create a "Test" addressbook and upload the attached test.vcf (renamed to .txt so I can attach to github).
[test.vcf.txt](https://github.com/fruux/sabre-dav/files/268358/test.vcf.txt)
This .vcf file was checked with vobject validate
```
vobject validate test.vcf 
sabre/vobject 4.1.0
vCard: 3.0
  No warnings!
```
6/ Check the mysql database, in the vcards table for this card. The contents of "cardsdata" are attached as cards-carddata.bin.txt (they are identical to test.vcf)
[cards-carddata.bin.txt](https://github.com/fruux/sabre-dav/files/268368/cards-carddata.bin.txt)

7/ Download the card again, I used the browser plugin. The resulting card is attached as test-get.vcf.txt
[test-get.vcf.txt](https://github.com/fruux/sabre-dav/files/268369/test-get.vcf.txt)

This card is no longer the original card or what's stored in the mysql db. See the diff

```
$ diff test.vcf.txt test-get.vcf.txt -u
--- test.vcf.txt	2016-05-17 16:02:55.571477700 +0200
+++ test-get.vcf.txt	2016-05-17 16:07:54.952288800 +0200
@@ -3,9 +3,9 @@
 UID:5C-2F-7F-08-B6-93-F8-EC-34-88-85-A4-14-DA-8A-A0
 N:Saveley;Art;;;
 ORG:Identity Corp;Sales
-EMAIL;INTERNET:Art.Saveley@Austria.IdentityPortal.local
+EMAIL;TYPE=INTERNET:Art.Saveley@Austria.IdentityPortal.local
 FN:Art Saveley
-TEL;WORK:7675-3425
-ADR;Work:;;Kälberpfad 215;Graz;Foo Bär;10112;Austria
+TEL;TYPE=WORK:7675-3425
+ADR;TYPE=WORK:;;Kälberpfad 215;Graz;Foo Bär;10112;Austria
 TITLE:Position Sales
 END:VCARD
```

So it seems the card is automatically "repaired" on retrieval for some reason.

**Comment by mbiebl** [comment]
As an additional note: I didn't see this behaviour with 2.*

**Comment by evert** [comment]
Confirming that I'm seeing the exact same thing.

**Comment by evert** [comment]
This is now fixed on master.

**Comment by mbiebl** [comment]
Thanks for the fix
Am 21.05.2016 05:45 schrieb "Evert Pot" <notifications@github.com>:
