### ISSUE TITLE
Trying to use the sharing functionality

### ISSUE THREAD

**Issue by manubaum** [fruux/sabre-dav#836]
This is more of a question than an issue.

I try to share a calendar from user02 with user01 but with no success so far. I tried to:

- right-click share in Apples Calendar (iCal) Application. However, the expected "Share calendar" feature is not visible/available
- I had a look into the calendarinstances tables after running the unit tests and I added a line to calendarinstances table, such that: calendarid='calendar to be shared id', access=2, uri='somethingrandom', share_ref='mailto:user02@domain.com', share_invitestatus=2.

I'd expect to see the newly shared calendar @ http://host/calendars/user02@domain.com.

I am happy for every advice.

**Comment by manubaum** [comment]
Figured it out:

After creating a calendar, naviagte to it, e.g. 
http://host/calendars/user02@domain.com/calendar

and use the "Share this resource" functionality.

**Comment by evert** [comment]
Sorry for the delay @manubaum , but I'm glad you figured it out. I guess there was something wrong when you manually added the instance.
