### ISSUE TITLE
Todos for 3.2 release

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#839]
Before release day:

* [x] Write blog post about the current sharing progress and what is changing for 3.2.
* [x] Write blog post about the changes we are making related to validation.
* [x] Finish migration document for 3.2.
* [x] Test Sqlite database migration.
* [x] Test MySQL database migration.
* [x] Update sharing doc on sabre.io/dav/caldav-sharing.
* [x] Make sure all bug reports for 3.2 are dealt with.
* [x] Check out coverage reports.

Testing clients:

* [x] Test OS X calendar
* [x] Test OS X addressbook
* [x] Test iOS Addressbook
* [x] Test iOS Calendar
* [x] Test BusyCal / BusyContacts
* [x] Test Thunderbird / Lightning
* [x] Test DavDroid

If anyone is willing to test other clients let me know, those are the ones I will test ;)

Near release day:

* [x] tag release.
* [x] write blog post.
* [x] write post on mailing list.
* [x] generate zip release.
* [x] write github releases page and upload zip.

**Comment by kralo** [comment]
How would I approach testing the beta ? I tried installing baikal, updating the sabre/dav to the beta via composer, but then I get `SQLSTATE[HY000]: General error: 1 no such table: calendarinstances` while manually browsing the collection. Is it supposed to be as this ? How can I proceed ?

**Comment by evert** [comment]
You can manually update the sabre/dav database by running the `vendor/sabre/dav/bin/migrate32.php` script. Running the script will give you some more instructions.

However, after you upgrade the baikal admin interface will break. The admin will probably be rewritten entirely in silex before we can fix this, because the framework is just too rigid to make changes like this :(

**Comment by evert** [comment]
So I would almost recommend switching to vanilla sabre/dav without baikal if you are really interested in this feature. It's a saner setup.

**Comment by kralo** [comment]
ok, do I get rudimentary user setup / database or will I have to code in
php ? How to getting started 'plain vanilla' ?

**Comment by kralo** [comment]
ok, got it. Tested creation (first try yields status 201, no repairs),
deletion, sync between

`DAVdroid/1.0.9.1 (2016/05/27; dav4android; okhttp3) Android/5.1.1`
and
`Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
Thunderbird/38.5.1 Lightning/4.0.5.2`

Seems good (y) for both clients !

**Comment by evert** [comment]
Awesome! Good news =)

**Comment by manubaum** [comment]
Is there an estimate when this release will be ready?

**Comment by evert** [comment]
@manubaum not sure... but you can make this time shorter if you help test =)
