### ISSUE TITLE
Baïkal on the PI

### ISSUE THREAD

**Issue by jpalcantara** [fruux/sabre-dav#840]
Hello,

  There was a tutorial that allowed the installation of Baïkal onto a pi computer.  I tried to installed and failed.
1  Is there an update to this install?
2  Is it still possible to do?

**Comment by evert** [comment]
I'm not aware of this tutorial, but yes I see no reason why it wouldn't work on the pi, as it can run linux.
If you're running into specific issues, feel free to ask here.

**Comment by jpalcantara** [comment]
PHP5:
sudo apt-get install php5 php5-xmlrpc php5-curl
Apache2:
sudo apt-get install apache2 libapache2-mod-php5
Sqlite:
sudo apt-get install php5-sqlite
In the /var/www folder, download and extract the "flat" package from Baikal's website:
sudo wget http://baikal-server.com/get/baikal-flat-0.2.7.zip
sudo unzip baikal-flat-0.2.7.zip
sudo mv baikal-flat/ baikal/
sudo chown -R www-data:www-data baikal/
sudo chmod 755 baikal
cd baikal/
sudo chmod 755 Specific/
sudo chmod 755 Specific/db
sudo chmod 755 Specific/db/db.sqlite
sudo touch Specific/ENABLE_INSTALL


On this part it fails
In the /var/www folder, download and extract the "flat" package from Baikal's website:
sudo wget http://baikal-server.com/get/baikal-flat-0.2.7.zip
****sudo unzip baikal-flat-0.2.7.zip

  It never finds the file when unzipping, or it is corrupted.

**Comment by evert** [comment]
That's because that file doesn't exist anymore. It's an old version that's no longer supported. Instead, go to the releases page and grab a more recent one:

https://github.com/fruux/Baikal/releases
