### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by phucnguyenvn** [fruux/sabre-dav#842]
I tried to build a client with these settings below, but always get the message:
 **"3.1.3 Sabre\DAV\Exception\NotAuthenticated Username1 or password was incorrect " ["statusCode"]=> int(401)"**
Tried with password in plain text and also MD5 password (digesta) but won't work.

Below is my addressbookserver.php configuration:

```
/*

Addressbook/CardDAV server example

This server features CardDAV support

*/

// settings
date_default_timezone_set('Asia/Ho_Chi_Minh');

// Make sure this setting is turned on and reflect the root url for your WebDAV server.
// This can be for example the root / or a complete path to your server script
$baseUri = '/sabredav/addressbookserver.php';

/* Database */
//$pdo = new PDO('sqlite:data/db.sqlite');
$pdo = new \PDO('mysql:host=localhost;dbname=sabre','root','');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

//Mapping PHP errors to exceptions
function exception_error_handler($errno, $errstr, $errfile, $errline) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
}
set_error_handler("exception_error_handler");

// Autoloader
require_once 'vendor/autoload.php';

// Backends
$authBackend      = new Sabre\DAV\Auth\Backend\PDO($pdo);
$principalBackend = new Sabre\DAVACL\PrincipalBackend\PDO($pdo);
$carddavBackend   = new Sabre\CardDAV\Backend\PDO($pdo);
//$caldavBackend    = new Sabre\CalDAV\Backend\PDO($pdo);

// Setting up the directory tree //
$nodes = [
    new Sabre\DAVACL\PrincipalCollection($principalBackend),
//    new Sabre\CalDAV\CalendarRoot($authBackend, $caldavBackend),
    new Sabre\CardDAV\AddressBookRoot($principalBackend, $carddavBackend),
];

// The object tree needs in turn to be passed to the server class
$server = new Sabre\DAV\Server($nodes);
$server->setBaseUri($baseUri);

// Plugins
$server->addPlugin(new Sabre\DAV\Auth\Plugin($authBackend));
$server->addPlugin(new Sabre\DAV\Browser\Plugin());
//$server->addPlugin(new Sabre\CalDAV\Plugin());
$server->addPlugin(new Sabre\CardDAV\Plugin());
$server->addPlugin(new Sabre\DAVACL\Plugin());
$server->addPlugin(new Sabre\DAV\Sync\Plugin());

// And off we go!
$server->exec();
```

Below is my addressbookclient.php configuration:

```
// settings
date_default_timezone_set('Asia/Ho_Chi_Minh');

// Make sure this setting is turned on and reflect the root url for your WebDAV server.
// This can be for example the root / or a complete path to your server script
$baseUri = 'http://localhost:8081/sabredav/addressbookserver.php';

use Sabre\DAV\Client;

include 'vendor/autoload.php';

$settings = array(
    'baseUri' => $baseUri,
    'userName' => 'admin',
    'password' => 'admin',
    'authType' => Sabre\DAV\Client::AUTH_DIGEST,
);

$client = new Client($settings);

$response = $client->request('GET'); 

var_dump($response);
```

I had make a var_dump in **validate()** function to try to output the value:

```
    /**
     * Validates the digest challenge
     *
     * @return bool
     */
    protected function validate() {

        $A2 = $this->request->getMethod() . ':' . $this->digestParts['uri'];

        if ($this->digestParts['qop'] == 'auth-int') {
            // Making sure we support this qop value
            if (!($this->qop & self::QOP_AUTHINT)) return false;
            // We need to add an md5 of the entire request body to the A2 part of the hash
            $body = $this->request->getBody($asString = true);
            $this->request->setBody($body);
            $A2 .= ':' . md5($body);
        } else {

            // We need to make sure we support this qop value
            if (!($this->qop & self::QOP_AUTH)) return false;
        }

        $A2 = md5($A2);

        $validResponse = md5("{$this->A1}:{$this->digestParts['nonce']}:{$this->digestParts['nc']}:{$this->digestParts['cnonce']}:{$this->digestParts['qop']}:{$A2}");
        var_dump("digestParts['response']=".$this->digestParts['response']);
        var_dump("validResponse=".$validResponse);
        return $this->digestParts['response'] == $validResponse;

    }
```

And the output value here:

```array(3) { ["body"]=> string(414) "string(56) "digestParts['response']=754c5eb5c3362b0fe0b9774b9fa11139" string(46) "validResponse=a4b80df54e14558902c9aa86aa8f52a6" 3.1.3 Sabre\DAV\Exception\NotAuthenticated Username1 or password was incorrect " ["statusCode"]=> int(401) ["headers"]=> array(6) { ["date"]=> array(1) { [0]=> string(29) "Wed, 25 May 2016 06:24:12 GMT" } ["server"]=> array(1) { [0]=> string(47) "Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.5.27" } ["x-powered-by"]=> array(1) { [0]=> string(10) "PHP/5.5.27" } ["www-authenticate"]=> array(1) { [0]=> string(98) "Digest realm="SabreDAV",qop="auth",nonce="5745450c61db8",opaque="df58bdff8cf60599c939187d0b5c54de"" } ["content-length"]=> array(1) { [0]=> string(3) "414" } ["content-type"]=> array(1) { [0]=> string(30) "application/xml; charset=utf-8" } } }```

Please help me to solve this issue, thank you all.

**Comment by evert** [comment]
Hi! Could your try calling `var_dump` on `$digestParts`? Also, are you sure that your username and password is `admin`? Can you access the sabre/dav server from a browser?

Lastly, what realm are you using? If you used the default `SabreDAV` realm your md5 hash for admin:admin should be `87fd274b7b6c01e48d7c2f965da8ddf7`, but neither of your hashes match that.

**Comment by nhphuc392** [comment]
Thank you very much for your answer, I made var_dump for digestParts and output is here:

`array(3) { ["body"]=> string(853) "string(56) "digestParts['response']=edea4b56ef68c2e547e2bd5da20b9a88" string(46) "validResponse=afa0cce704a23eb561eb61819d7ebffa" array(9) { ["username"]=> string(5) "admin" ["realm"]=> string(2) """" ["nonce"]=> string(13) "5747231becc29" ["uri"]=> string(31) "/sabredav/addressbookserver.php" ["cnonce"]=> string(32) "52aefd4dab3cc13f6649fe80108100a1" ["nc"]=> string(8) "00000001" ["response"]=> string(32) "edea4b56ef68c2e547e2bd5da20b9a88" ["qop"]=> string(4) "auth" ["opaque"]=> string(32) "df58bdff8cf60599c939187d0b5c54de" } 3.1.3 Sabre\DAV\Exception\NotAuthenticated Username1 or password was incorrect " ["statusCode"]=> int(401) ["headers"]=> array(6) { ["date"]=> array(1) { [0]=> string(29) "Thu, 26 May 2016 16:23:55 GMT" } ["server"]=> array(1) { [0]=> string(47) "Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.5.27" } ["x-powered-by"]=> array(1) { [0]=> string(10) "PHP/5.5.27" } ["www-authenticate"]=> array(1) { [0]=> string(98) "Digest realm="SabreDAV",qop="auth",nonce="5747231c01ca7",opaque="df58bdff8cf60599c939187d0b5c54de"" } ["content-length"]=> array(1) { [0]=> string(3) "853" } ["content-type"]=> array(1) { [0]=> string(30) "application/xml; charset=utf-8" } } }`

Of  couse, I can access sabre/dav server from a browser, also can connect by CardDav service on my iPhone and my Blackberry Passport, I used default realm "SabreDAV".

But.. I found in **sabredav/vendor/sabre/http/lib/Auth/Digest.php on line 47** have the following realm:

`function __construct($realm = 'SabreTooth', RequestInterface $request, ResponseInterface $response)`

I changed the realm in that line to "SabreDAV" also won't work.
I used default password is admin, you can see the hash in output.

**Comment by nhphuc392** [comment]
One more thing:

as you can see in output of digestParts, the realm is empty, I don't know why but I tried to add

`digestParts["realm"] = "SabreDAV";`

I added this line before it's generate the validResponse but also won't work, hmm..

**Comment by evert** [comment]
Super weird. `realm` being empty is probably exactly the source of your problem. The question is then.. why?

The plugin definitely seems to emit it... so I don't fully understand why curl is not correctly sending it. Would you be able to do a request with the curl command-line tool, or are you getting a similar problem there?

You can just run:

    curl -v -X PROPFIND http://yourserver/ --user admin

**Comment by nhphuc392** [comment]
Here is an result of curl command:

```
C:\Users\Admin>curl -v -X PROFIND http://localhost:8081/sabredav/addressbookserver.php --user admin
Enter host password for user 'admin':
*   Trying ::1...
* Connected to localhost (::1) port 8081 (#0)
* Server auth using Basic with user 'admin'
> PROFIND /sabredav/addressbookserver.php HTTP/1.1
> Host: localhost:8081
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.49.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Date: Fri, 27 May 2016 02:30:47 GMT
< Server: Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.5.27
< X-Powered-By: PHP/5.5.27
< WWW-Authenticate: Digest realm="SabreDAV",qop="auth",nonce="5747b1579b2e6",opaque="df58bdff8cf60599c939187d0b5c54de"
< Content-Length: 355
< Content-Type: application/xml; charset=utf-8
<
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.1.3</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>
* Connection #0 to host localhost left intact
```


Infact, I have tried with baikal server before I posted question in here, also doesn't work.

**Comment by i77ipan** [comment]
Hi all, I've this problem too when I tried to update sabre/dav via composer from 2.0 -> 3.1 on my development server. In my case I custom realm of my own.

**Below this is my Calendar's server config files.**
`<?php
/*
CalendarServer
This server features CalDAV support
*/

// settings
date_default_timezone_set('Asia/Bangkok');

// If you want to run the SabreDAV server in a custom location (using mod_rewrite for instance)
// You can override the baseUri here.
// $baseUri = '/';

/* Database */
$pdo = new PDO('mysql:dbname=sabredav;host=127.0.0.1', '***', '****');
$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);

//Mapping PHP errors to exceptions
function exception_error_handler($errno, $errstr, $errfile, $errline ) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
}
set_error_handler("exception_error_handler");

// Files we need
require_once 'vendor/autoload.php';

// Backends
$authBackend = new Sabre\DAV\Auth\Backend\PDO($pdo);
$calendarBackend = new Sabre\CalDAV\Backend\PDO($pdo);
$principalBackend = new Sabre\DAVACL\PrincipalBackend\PDO($pdo);

// Directory structure
$tree = [
    new Sabre\CalDAV\Principal\Collection($principalBackend),
    new Sabre\CalDAV\CalendarRoot($principalBackend, $calendarBackend),
];

$server = new Sabre\DAV\Server($tree);

if (isset($baseUri))
    $server->setBaseUri($baseUri);

/* Server Plugins */
$authPlugin = new Sabre\DAV\Auth\Plugin($authBackend,'TCPDAV'); // default realm is SabreDAV
$server->addPlugin($authPlugin);


/* Server HTTP Bacsic Authentication Plugins */

/*
$authBacsicPlugin = new Sabre\DAV\Auth\Backend\AbstractBasic();
$server->addPlugin($$authBacsicPlugin);
*/
$aclPlugin = new Sabre\DAVACL\Plugin();
$server->addPlugin($aclPlugin);

/* CalDAV support */
$caldavPlugin = new Sabre\CalDAV\Plugin();
$server->addPlugin($caldavPlugin);

/* Calendar subscription support */
$server->addPlugin(
    new Sabre\CalDAV\Subscriptions\Plugin()
);

/* Calendar scheduling support */
$server->addPlugin(
    new Sabre\CalDAV\Schedule\Plugin()
);

/* WebDAV-Sync plugin */
$server->addPlugin(new Sabre\DAV\Sync\Plugin());

// Support for html frontend
$browser = new Sabre\DAV\Browser\Plugin();
$server->addPlugin($browser);

// And off we go!
$server->exec();
`

**Comment by i77ipan** [comment]
**In my case when I curl to query an event by curl** 

`curl -i -X REPORT    -H "Content-Type:application/xml"    -H "Depth:1"    -d '   <C:calendar-query xmlns:D="DAV:"
                 xmlns:C="urn:ietf:params:xml:ns:caldav">
     <D:prop>
       <D:getetag/>
       <C:calendar-data>
         <C:comp name="VCALENDAR">
           <C:prop name="VERSION"/>
           <C:comp name="VEVENT">
             <C:prop name="SUMMARY"/>
             <C:prop name="UID"/>
             <C:prop name="DTSTART"/>
             <C:prop name="DTEND"/>
             <C:prop name="DURATION"/>
             <C:prop name="RRULE"/>
             <C:prop name="RDATE"/>
             <C:prop name="EXRULE"/>
             <C:prop name="EXDATE"/>
             <C:prop name="RECURRENCE-ID"/>
           </C:comp>
           <C:comp name="VTIMEZONE"/>
         </C:comp>
       </C:calendar-data>
     </D:prop>
     <C:filter>
       <C:comp-filter name="VCALENDAR">
         <C:comp-filter name="VEVENT">
           <C:time-range start="20160104T000000Z"
                         end="20160105T000000Z"/>
         </C:comp-filter>
       </C:comp-filter>
     </C:filter>
   </C:calendar-query>' --digest -u 'admin:admin' 'http://192.168.1.205/calendar/calendar.php/calendars/admin/working/'`

**Result is display realm not correct of my config**

`HTTP/1.1 401 Unauthorized
Date: Tue, 07 Jun 2016 10:10:44 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.17
WWW-Authenticate: Digest realm="SabreDAV",qop="auth",nonce="57569da461538",opaque="df58bdff8cf60599c939187d0b5c54de"
Content-Length: 283
Connection: close
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.1.3</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password was incorrect</s:message>
</d:error>`

**Comment by i77ipan** [comment]
Like @nhphuc392 found on **sabredav/vendor/sabre/http/lib/Auth/Digest.php** I try to change default real in constructor of this class but it still SabreDAV.

I'm back to my production server that use sabre/dav 2.0 and try the same curl that I've tested on my development it OK I can get result and realm on HTTP header return correct that I config in my server configure file.

**Comment by evert** [comment]
@i77ipan please don't hijack the thread. Your issue is different. In sabre/dav 3.0 you can no longer specify the realm in the auth plugin, it must be done on the actual backend class. If you have follow-up questions please open a new ticket.

**Comment by i77ipan** [comment]
I'm apologize @evert @nhphuc392  to hijack this thread (I'm a newbie of Github thread) and thank you for your suggestion.

**Comment by nhphuc392** [comment]
@evert @i77ipan This problem just on master branch, I changed to version 3.1.3 and it's worked!
But it's will be better when some one can fix this problem in master branch of this project.
@i77ipan please visit here: https://github.com/fruux/sabre-dav/releases to find the stable version, for me is 3.1.3.

**Comment by nhphuc392** [comment]
Ahh! one more thing:
I installed version 3.1.3 like a server in my macbook and I used master branch in my desktop to build client, but it's not work. Then I change the version of desktop to 3.1.3 and it's worked.
Maybe some problem with client library.

**Comment by evert** [comment]
Ah weird. We did make a lot of changes to the master branch, but not that much in the Client class! So I still have no clue what could be different =)

**Comment by nhphuc392** [comment]
@evert Haha, then God bless master branch :v

**Comment by evert** [comment]
Looks like the original issue was resolved.
