### ISSUE TITLE
Database column "components" too small for enabling notes and todo

### ISSUE THREAD

**Issue by hcderaad** [fruux/sabre-dav#843]
Selecting both notes and todo's on a calendar in Baikal 0.4.4 with a MySQL/Mariadb database server results in a PDO Exception mentioning the data is too long for the "components" field in the "calendars" table.
Increasing the length of that VARBINARY column to 30 fixes the issue:

```
ALTER TABLE `calendars` CHANGE `components` `components` VARBINARY(30) NULL DEFAULT NULL;

```

**Comment by evert** [comment]
This has been fixed in #805
