### ISSUE TITLE
right delegation in table groupmember is only working for some users

### ISSUE THREAD

**Issue by karstengit** [fruux/sabre-dav#844]
My system is a Debian server running Apache and PHP 5.4.45.
So sabredav 3.0.9 is installed.
The clients are Thunderbird with sogo-connector and CategoryManager.

Here is my problem:

I have 3 user accounts with own calender and adressbook.
Additional i have 1 user account for a shared calender and adressbook.
I have added the calendar-proxy-read/write principal id's of the shared account for all 3 users to the groupmember table.

Thunderbird authenticate on each PC with the personal user account.
On my PC i can access and work with my personal and the shared calender and adressbook.
But the second user can only work with his personal calender and adressbook!

When i try to access with the 2. user account via browser i get
```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.0.9</s:sabredav-version>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "calendars/sharedaccount
"</s:message>
<d:need-privileges>
<d:resource>
<d:href>/sabredav/groupwareserver.php/calendars/sharedaccount</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

I have double checked the groupmember entries and everything should be perfect.
The entries are correct with similar id's of the principals to my user that is working!

When i look into the principals of the user that is not working
https://192.168.1.3/sabredav/groupwareserver.php/principals/user2/
i can see that the groupmember rights are empty!

```
cs:calendar-proxy-read-for    
cs:calendar-proxy-write-for
d:supported-report-set    d:expand-property, d:principal-property-search, d:principal-search-property-set
d:resourcetype    d:collection, d:principal
```

But they are defined in the table groupmember!

So sabredav has a bug and is not working. :-(

**Comment by evert** [comment]
Please note that addressbook sharing does not work. The delegation / proxy stuff _only_ applies to calendars.

That being said, it should still work. Could you share the actual database values for the relevant principals and entries in groupmembers?

**Comment by karstengit** [comment]
Up to now i only tried to use a shared calendar.
This produced this error.
I checked the apache logfiles and no php error is logged.

It's a pity that sharing of adressbooks does not work!
Do you know if it is possible to login in Thunderbird with multiple accounts?
Or is there another workaround?
I only want to have a private and a shared calendar and adressbook for each user.

Here the anonymized content of the tables.
[sabredav.sql.zip](https://github.com/fruux/sabre-dav/files/283617/sabredav.sql.zip)

**Comment by evert** [comment]
The only way that you can log in to multiple accounts with thunderbird, is if you have multiple subdomains all running the same sabre/dav. Thunderbird will cache credentials based on an entire domain, so that's a workaround.

Looking into the zip now.

**Comment by evert** [comment]
Based on the zip, I can tell that there's some errors.

You need to make sure that if `user_a` wants to delegate their calendars to `user_b`, then the `principal_id` in the group members table for that record needs to refer to `principals/user_a/calendar-proxy-read` and the `member_id` needs to refer to `principals/user_b`.

You also shouldn't add them to both the `read` and `write` group. Just `write` is enough.

Sorry if this is a bit annoying/complicated. I plan to add an interface at one point to the browser plugin for this.

**Comment by evert** [comment]
So to conclude, only `admin` is currently added to the shared account. Correct?

**Comment by karstengit** [comment]
Now i understand. Doing the things right is working! :-)
There should be a much better description **with examples** for it!
The principals are very important but nearly not documented.
I made it wrong because i followed this page http://publications.jbfavre.org/web/online-calendars-sabredav-php-fpm-nginx.en
So this guy did not understand it even. ;-)

> I plan to add an interface at one point to the browser plugin for this.

You should do it immedeately because this is absolutely missing.
You can add an calender direct over the php of sabredav but not the users and user rights!
With two additional PHP's all problems of misunderstanding would be solved.

> So to conclude, only admin is currently added to the shared account. Correct?

No - admin should not be used - i was afraid that something is not working when i delete this account.
All users should have there own calendar and additional the rights for the shared calendar.
The correct solution is:
INSERT INTO `groupmembers` (`id`, `principal_id`, `member_id`) VALUES
(1, 15, 4),
(2, 15, 7),
(3, 15, 10);

It is working now - thank you for your support!

> The only way that you can log in to multiple accounts with thunderbird, is if you have multiple subdomains all running the same sabre/dav. Thunderbird will cache credentials based on an entire domain, so that's a workaround.

Here i need some additional help.
I can enter a address with my account in my private and in the shared addressbook.
Then i can see this addresses with my user in each addressbook.
With the second user on the other PC i can open the shared addressbook but it seems to be empty!
I don't understand this?

At this time i work locally in the LAN - so i address the server of it's IP like 
https://192.168.1.5/sabredav/groupwareserver.php/addressbooks/shareduser/shared/
What would be the best/easiest solution to solve the problem?

**Comment by karstengit** [comment]
I could find out that the entered shared addresses are only stored locally on my PC in Thunderbird.
This is very irritating, because there is no message that synchronizing will not work for the shared account!

So - how can i implement a shared addressbook that is working?

**Comment by karstengit** [comment]
> The only way that you can log in to multiple accounts with thunderbird, is if you have multiple subdomains all running the same sabre/dav. Thunderbird will cache credentials based on an entire domain, so that's a workaround.

This is a good hint - Thank you.
I implemented the Subdomain locally over /etc/hosts in the client.
With an entry "192.168.1.5 server dav.server" i could create additional alternate Names to work with.
So i can access the shared addressbook now additionally.

But it would be fine to manage the rights for the addressbook access too.
Is it not possible to create a principal like "principals/user/addressbook-proxy-read" even it is not specified in an RFC?
Maybe it is not so much work to implement a delegation of the rights in the same way like for the calender?

**Comment by evert** [comment]
Hi Karsten,

It is actually possible to allow a user _full_ access to another user's accounts + addressbooks and calendars. In that case the user needs to be added a as  _member_ of the account that is being shared.

**Comment by karstengit** [comment]
> It is actually possible to allow a user full access to another user's accounts + addressbooks and calendars. In that case the user needs to be added a as member of the account that is being shared.

How can i do that?
With the current rights i have full access as user to the shared user calendar - but nor address book.
I must login as shared user to access the address book.

It would be interesting to have an CardDAV account where users can read an insert addresses, but not modify or delete them.
How could that be realized?

**Comment by evert** [comment]
Basically, the purpose of groups is when you add a principal as a member of any other principal, they will inherit all their privileges.

This will only allow you to do a read/write thing. Not read-only.

**Comment by karstengit** [comment]
O.K. Where can i find a list of all possible principals?
