### ISSUE TITLE
OS X 10.11 only displays one addressbook, an old non-existant one.

### ISSUE THREAD

**Issue by coderiekelt** [fruux/sabre-dav#846]
As the title says, OS X will not show more then one address book, which has been removed from the system all together and has no reason whatsoever to be visible, contacts are loaded normally however they are not placed in any address books.

Loading the address books and contacts works just fine on Android and iOS. (tested on an Samsung Galaxy S3 and an iPad)

**Comment by evert** [comment]
OS X unfortunately supports just one addressbook. The one it uses is basically the 'first one in the list'.

You might need to setup OS X again to see the address book. There's not a ton we can do about this. In the future we might detect OS X connecting and automatically merge all of a user's addressbooks into one, but this is a fairly large undertaking.
