### ISSUE TITLE
Is PHP7 supported?

### ISSUE THREAD

**Issue by woutersamaey** [fruux/sabre-dav#851]
Just a quick question. Is PHP7 supported?

**Comment by staabm** [comment]
I think so, at least tthe testsuite passes on php7
https://travis-ci.org/fruux/sabre-dav/builds/133666386

**Comment by davedags** [comment]
yes, see here:  http://sabre.io/dav/upgrade/3.0-to-3.1/

First release that supports php 7 officially is 3.1, but older ones might
work too
