### ISSUE TITLE
No old calendars visible in Apple iCal after upgrade + fix

### ISSUE THREAD

**Issue by massar** [fruux/sabre-dav#852]
It seems that the LEFT outer join used in PDO's getCalendarsForUser() [1] fails to fetch old calendars after an upgrade. In theory it should work, but the "cal:supported-calendar-component-set" remain empty and thus, it does not get outputted.

I noticed the discrepancy as the 'cal:supported-calendar-component-set' property was empty in the web browser, while for a newly created calendar one existed. In Apple iCal the old calendars would not pop up at all anymore, while in the browser everything still looked okay (except for that empty property). Adding a new calendar did show up in iCal and then did have that property set.

I thus manually did, per calendar:
```
insert into calendars (id,synctoken,components) VALUES(19,1,'VEVENT,VTODO');
```
where 'id' matches the 'calendarid' from the 'calendarinstances' table and things work again.

I thus think the migrate script needs to populate the calendar table properly by looping over calendarinstances. Other version would be to have getCalendarsForUser() set the properties to the default, or maybe a consistency-check script is in order?

After the inserts everything is working again from what I can tell, which is good :)

Note that I upgraded from possibly a rather old fcf446d5d12452b29d90e00f64dd80fe93895cf6 (Tue Aug 11 15:21:21 2015 -0400) to current-ish 3bd4eb8f6d4303a0829f56b2ce7c1e88439b5a7f (Sat May 21 01:35:51 2016 -0400) and re-ran the migrate scripts again as I was not sure which the old version was; thus that might have messed something up.

[1] 
https://github.com/fruux/sabre-dav/blob/72399026e7d343a043fa7ede48efa6128107078c/lib/CalDAV/Backend/PDO.php

**Comment by evert** [comment]
hmm... this is the relevant line:

    INSERT INTO calendars (id, synctoken, components) SELECT id, synctoken, COALESCE(components,"VEVENT,VTODO,VJOURNAL") as components FROM $calendarBackup

Could you try running that manually and see what happens?

Note that `$oldcalendarbackup` refers to a backup calendar table that's unique for every installation but looks a bit like `calendars_3_1_unixtimestamp`.

**Comment by massar** [comment]
Yes, that should have done the trick (manually checking the backups), no idea where that went wrong (the migrate scripts are quite fragile in a way, see note below).

I primarily filed this so that you are aware that it went wrong at least once, and that others who google might find the issue.

From my POV, you can close this, as the problem on my side has been resolved, and using the former db on a separate box I was unable to replicate the issue.


Maybe it is a good idea to introduce a 'version' value in the DB so that an upgrade can be based on that instead of the guessing how many columns a DB has? The migrate script can then check that column/field what version it contains and base their actions on that.

**Comment by evert** [comment]
I agree that having a version field in the db would be nice. I'm opening up a separate feature request for that.
