### ISSUE TITLE
[CardDAV] Fatal error with many contacts (200k+)

### ISSUE THREAD

**Issue by cedtaz** [fruux/sabre-dav#853]
I have an addressbook with 200k+ contacts and when I want to synchronize it, I have this error : 

PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 33554432 bytes) in /web/vendor/sabre/dav/lib/DAV/Server.php on line 874

Would you have a solution ?

**Comment by staabm** [comment]
@cedtaz could you create a blackfire.io profile so we can dig into where all the memory is consumed?

**Comment by evert** [comment]
I don't think that thats needed @staabm.

200.000 is a lot of contacts. Generally I would not recommend going over 1000. It would in theory be possible for sabre/dav to support this, but it requires architectural changes that are simply not in place yet.

At the moment, at 200.000 contacts the initial sync would actually have to load in *all of those contacts* to then generate an xml response. I think the total required memory for this exceeds what's reasonably available.

We have plans to switch to unbuffered sql queries and using generators, so we can basically 'live stream' the data, but we haven't really worked on this yet.

So for now I don't really have a good answer. In theory it might be possible to modify the CardDAV pdo backend to page it using synctokens as well, but I've never tried this and I don't know how well clients deal with this. 

Sorry for not having a better answer...

**Comment by cedtaz** [comment]
Thank you for your help.
