### ISSUE TITLE
[CardDAV] Problem with encoding quoted printable

### ISSUE THREAD

**Issue by cedtaz** [fruux/sabre-dav#857]
I have a contact with data : 
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Mac OS X 10.11.3//EN
N:;Sabine;;;
FN:Sabine
UID:fc33f9e1-e7c0-4a0b-8586-0a6537fc0012
LABEL;POSTAL;ENCODING=QUOTED-PRINTABLE:Chemin Des Fleurettes, 31=0D=0A=1007
 = Lausanne=0D=0A=Switzerland
END:VCARD
```

With Addressbook (9.0) on MAC OS X (10.11), I have an error when I synchronize this contact with this message in the console : 

> [CardDAVPlugin-ERROR] -_handleAddsOrModifies:https://{myserver}/addressbooks/AA00000/{UUID}/ Error Domain=CoreDAVErrorDomain Code=3 "(null)"

If I remove the encoding, I have no problem, the synchronization is OK.

Have you ever had this problem ?

**Comment by evert** [comment]
Quoted-printable is a vCard 2.1-only feature. So yes, this is invalid.

**Comment by cedtaz** [comment]
I have the same error with VERSION 2.1
The problem is with this line : 
```
LABEL;POSTAL;ENCODING=QUOTED-PRINTABLE:Chemin Des Fleurettes, 31=0D=0A=1007
 = Lausanne=0D=0A=Switzerland
```
And these characters : 

> =0D=0A=

Replaced by : 

> =0D=0A

And it's OK !

**Comment by evert** [comment]
Ah I see. That makes sense. So this ticket can be closed then?

**Comment by cedtaz** [comment]
Yes thanks.
