### ISSUE TITLE
Synchronization issue with debian jessie

### ISSUE THREAD

**Issue by Philppe** [fruux/sabre-dav#859]
Hi all,

I've a baikal server (v0.2.6) running for several years without any issue.

I suppose since the upgrade of Debian version from wheezy to jessie, I can't synchronize my contacts and my calendars. I've tried to install a new instance (v0.4.5) to debug and same result.

With Sogo Connector, I can connect to baikal (it asks me the user/password) but no synchronization.
I've tried with the thunderbird add-on Cardbook and I have a log with error 500.

I have a return on "php -i  | grep mbstring".

Any idea ?

**Comment by evert** [comment]
Hi @Philppe ,

Is there anything in your error logs?
What happens if you open the webdav endpoint directly in a browser? If there's an error there too it might give you a hint what's wrong.

**Comment by Philppe** [comment]
Hi Evert,

I can see error 500 in apache access.log when I try to connect to an address books :
"PROPFIND /test/dav.php/addressbooks/philippe/default/ HTTP/1.1" 500 644 "-" "Thunderbird Lightning/4.0.8"

What do you mean by "open webdav endpoint" ?
If it means access to the baikal dashboard, I can access to it without error.

Thank you for your help

**Comment by Philppe** [comment]
I've written the url of the address book in a  browser and I get an xml page with error :
<d:error>
<s:sabredav-version>3.1.3</s:sabredav-version>
<s:exception>LogicException</s:exception>
<s:message>Requested uri (/test/dav.php/addressbooks/philippe/default) is out of base uri (/html/dav.php/)</s:message>
</d:error>

**Comment by evert** [comment]
Are you using url rewriting? If so, stop doing that!

**Comment by evert** [comment]
Because the problem here is that you are accessing your server with :

    /test/dav.php/

and the server expects it to be:

    /html/dav.php/

**Comment by Philppe** [comment]
I'm really sorry but I don't understand.
If you use the virtualhost given by the example with 
"DocumentRoot /var/www/test/html"
I can access with test/dav.php which mean /test/html/dav.php

No ?

**Comment by Philppe** [comment]
sorry for my bad skills with apache but before the upgrade, everything works well.
And even if my config was bad, it worked.

**Comment by Philppe** [comment]
url rewriting means Alias in a apache config file ?

**Comment by Philppe** [comment]
I remove the Alias conf and created a virtualhost as the example.
And it works.

Thank you Evert but I would to understand what is the difference between the two configurations (Alias vs Virtualhost) ?

**Comment by evert** [comment]
Hi Philippe,

That question is a little bit too broad for me to give you a useful answer. If you are interested in the subject, I would suggest to sit down and properly learn it. Maybe buy a book or study the apache manual.

**Comment by Philppe** [comment]
Thank you for your help
