### ISSUE TITLE
Get properties for calendar can't be filtered

### ISSUE THREAD

**Issue by tcitworld** [fruux/sabre-dav#860]
The `getProperties` [function](https://github.com/fruux/sabre-dav/blob/master/lib/CalDAV/Calendar.php#L79L97) accepts a `$requestedProperties` argument but it's never used to filter properties retrieved.

**Comment by evert** [comment]
It's not really a big deal if functions like this return too much data. The information *is* filtered further down in the stack, but the argument there sort of serves as a hint that a class can use to make operations like this cheaper.
