### ISSUE TITLE
iOs duplicate group

### ISSUE THREAD

**Issue by coderiekelt** [fruux/sabre-dav#861]
In iOs 9.3 the CardDav synchronization creates a duplicate group, which is of one group only. e.g.:
- Test Group 1
- Test Group 2
- Out of place group (duplicate)
- Out of place group (duplicate)
- Out of place group (duplicate)
- Out of place group (duplicate)
- Out of place group (duplicate)
- Out of place group (duplicate)
- Out of place group (duplicate)
- Test Group 3
- Test Group 4
- Test Group 5
- Test Group 6

These duplicate groups are all empty.

I have no idea where they're coming from, and this only occurs on an iPhone. Tried to reproduce the problem on an iPad with iOs 9.2 (13C75) but this would sync just fine.

The weird thing also is that the user does not have access to the duplicate group, however it still shows up but is completely empty.
##

**Comment by coderiekelt** [comment]
Just updated the iPad to iOs 9.3.2 and the problem does not exist on the iPad, just on the iPhone.

**Comment by DominikTo** [comment]
Have you looked at the actual data?
iOS (unlike macOS) supports multiple addressbooks in one CardDAV account, but displays them in the same user interface where it also displays groups, which sometimes ends up showing quite confusing results.

**Comment by evert** [comment]
I'm closing this ticket because it's been a while since the last comment.

If this is indeed still an issue, feel free to comment here so we can continue discussing.
