### ISSUE TITLE
CardDAV "updateAddressBook" function not working.

### ISSUE THREAD

**Issue by Nildric** [fruux/sabre-dav#862]
Updating an AddressBook with the "updateAddressBook" function doesn't yield to any error or result.
The procedure seems to work correctly but no changes can be seen in the actual Database.

Following the code used to execute an update procedure:
```php
// Building CardDAV Backend
        $cardDAVBackend = new Sabre\CardDAV\Backend\PDO($connectionPDO);

        // Updating the AddressBook by ID
        $cardDAVBackend->updateAddressBook($addressBookID, new \Sabre\DAV\PropPatch(
            array(
                '{DAV:}displayname' => $addressBookDisplayName,
                '{' . Sabre\CardDAV\Plugin::NS_CARDDAV . '}addressbook-description' => $addressBookDescription,
            )
        ));
```

I'm reporting this as an issue because the procedure used to create an AddressBook with the same exact properties names works perfectly fine. Given that, i think this isn't just something i did wrong (but it could always be), in case i'm mistaking please let me now.

Have a good day!

**Comment by PHPGangsta** [comment]
The updateAddressBook() method is just preparing the update.
You have to call $propPatch->commit() to do the actual update.

Try the following:
```php
$propPatch = new \Sabre\DAV\PropPatch(
    array(
        '{DAV:}displayname' => $addressBookDisplayName,
        '{' . Sabre\CardDAV\Plugin::NS_CARDDAV . '}addressbook-description' => $addressBookDescription,
    )
);
$cardDAVBackend->updateAddressBook($addressBookID, $propPatch);
$result = $propPatch->commit();
```

See also:
https://github.com/fruux/sabre-dav/blob/master/tests/Sabre/CardDAV/Backend/AbstractPDOTest.php#L114

**Comment by evert** [comment]
Wh

**Comment by Nildric** [comment]
Thank you for the quick response and sorry for the trouble. Have a great day!
