### ISSUE TITLE
Login not checked

### ISSUE THREAD

**Issue by mschering** [fruux/sabre-dav#870]
I tried to upgrade to sabre dav 3.1. But I ran into a problem where getCalendarObjects() is called in my backed while authentication did not happen. Is there something I should change or is this a security bug?

**Comment by evert** [comment]
Are you sure it's not 3.2?

**Comment by mschering** [comment]
Yes it's 3.2 indeed. I downgraded to 3.1 and now it works as expected. Is this a 3.2 bug?

**Comment by evert** [comment]
No, it's a feature. We now postpone authentication until the last possible moment. Some more info here:

http://sabre.io/dav/upgrade/3.1-to-3.2/#support-for-unauthenticated-access
