### ISSUE TITLE
Sabre\HTTP\ClientHttpException: Not Found

### ISSUE THREAD

**Issue by aimeos** [fruux/sabre-dav#873]
Using Sabre DAV via composer require "sabre/dav:~3.1" results in a fatal error if the server isn't available -> "Sabre\HTTP\ClientHttpException: Not Found" in https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Client.php#L234

Used composer packages:
sabre/dav                         3.2.0              WebDAV Framework for PHP
sabre/event                       3.0.0              sabre/event is a library for lig...
sabre/http                        4.2.1              The sabre/http library provides ...
sabre/uri                         1.1.0              Functions for making sense out o...
sabre/vobject                     4.1.1              The VObject library for PHP allo...
sabre/xml                         1.4.2              sabre/xml is an XML library that...

Problem might be a mix of versions that don't play together.

**Comment by evert** [comment]
This is expected behavior, I think. Are you expecting something different? There's some information on the wiki describing the change in sabre/dav 3.0:

http://sabre.io/dav/upgrade/3.0-to-3.1/

**Comment by aimeos** [comment]
Thanks
