### ISSUE TITLE
VCard validation does not verify value fields ....

### ISSUE THREAD

**Issue by DeepDiver1975** [fruux/sabre-dav#874]
refs https://github.com/owncloud/contacts/issues/488

When importing an vcard the invalid date format for BDAY was not recognized but as soon as the vcard is loaded and a different vcard version is requested the converter throws an exception.

This basically leaves the system in a bad state.

Test data on import.

```vcard
BEGIN:VCARD
VERSION:4.0
FN:John Doe
BDAY:Jan 1, 1970
END:VCARD
```

**Comment by evert** [comment]
From sabre/dav 3.2 we actually strictly validate everything. Are you guys on that version or is this for an older version? For pre-3.2 I'm not really sure what the right answer is. I'd really want to suggest to just try to upgrade to fix this problem ;)

**Comment by DeepDiver1975** [comment]
We are on 3.0. With ownCloud 9.2 we plan to update sabre to 3.2 - THX

**Comment by evert** [comment]
I think a solution for older versions would be to catch exceptions like that and handle them gracefully. Full-on validation felt like to big of a change to me to add in a minor version, but I do feel that we can do better in older versions.

If you can get me a stacktrace for that exception, I should be able to come up with a workaround.

**Comment by DeepDiver1975** [comment]
From what I can tell after some minimal local testing - this is the diff which is missing in 3.0

https://github.com/fruux/sabre-dav/blob/master/lib/CardDAV/Plugin.php#L364-L417

Would you accept a pull request for it? I'd happily submit that ....

**Comment by evert** [comment]
No, because I actually waited for a 'major' release to make this change. It changes too much for a point release

**Comment by evert** [comment]
I wrote some details here: http://sabre.io/blog/2016/validation-changes/

However I'm fairly sure that the validation changes are doable in a simple plugin, if you want to take that risk yourself

**Comment by evert** [comment]
But it has the potential to break existing clients so I wanted to be really careful, and I still do ;)

**Comment by DeepDiver1975** [comment]
I guess we will upgrade to 3.2 ... THX
