### ISSUE TITLE
Subscription For all countries Public holidays.

### ISSUE THREAD

**Issue by sagarhspl** [fruux/sabre-dav#878]
Hi Team,

Currently I am using simple php CalDAV-Client library. I am looking for a country wise public holidays' list. I would like to know, is there any provision to get or subscribe the public holidays in sabre account?

Waiting for your response.

Thanks,
Sagar

**Comment by evert** [comment]
Hi Sagar,

There's no default functionality for this. Would be interesting to offer this one day though!

Mozilla provides calendar data for this: 

https://www.mozilla.org/en-US/projects/calendar/holidays/
