### ISSUE TITLE
Why using ob_start() in Browser\Plugin?

### ISSUE THREAD

**Issue by PHPGangsta** [fruux/sabre-dav#883]
I just stumbled upon line 515 in the Browser Plugin:
https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Browser/Plugin.php#L515

What is the advantage of using ob_* functions here? I would have done just a simple assignment to $output:
```php
$output .= '<form method="post" action="">
        <h3>Create new folder</h3>
        <input type="hidden" name="sabreAction" value="mkcol" />
        <label>Name:</label> <input type="text" name="name" /><br />
        <input type="submit" value="create" />
        </form>
        <form method="post" action="" enctype="multipart/form-data">
        <h3>Upload file</h3>
        <input type="hidden" name="sabreAction" value="put" />
        <label>Name (optional):</label> <input type="text" name="name" /><br />
        <label>File:</label> <input type="file" name="file" /><br />
        <input type="submit" value="upload" />
        </form>
        ';
```
Or maybe even better:
```php
$output = <<<HTML
<form method="post" action="">
	<h3>Create new folder</h3>
	<input type="hidden" name="sabreAction" value="mkcol" />
	<label>Name:</label> <input type="text" name="name" /><br />
	<input type="submit" value="create" />
</form>
<form method="post" action="" enctype="multipart/form-data">
	<h3>Upload file</h3>
	<input type="hidden" name="sabreAction" value="put" />
	<label>Name (optional):</label> <input type="text" name="name" /><br />
	<label>File:</label> <input type="file" name="file" /><br />
	<input type="submit" value="upload" />
</form>
HTML;
```

I don't know the ob_* functions very well, is there a feature that you need here?

**Comment by evert** [comment]
There's no real advantage. I suspect this is just a holdover from something that's been refactored a few times over the years.

**Comment by Frzk** [comment]
Well to me there is an advantage : it makes the code clearer because you don't have to deal with quotes escaping (it's also much more friendly in my code editor :P)

Also, it's very convenient if you want to send gzipped content. You'd only have to:

    <?php
    ob_start("ob_gzhandler");
    //...
    ob_end_flush();
    ?>
