### ISSUE TITLE
dav folder does not load for high volumes of files

### ISSUE THREAD

**Issue by billfasoli** [fruux/sabre-dav#884]
Hello,

I'm using webdav for box.com. My box folder contains around 1M files totaling several hundred GB in a myriad of subfolders. I could map to webdav (explorer or cyberduck) prior to uploading a high volume of files to my box account, but now that i've transition all of our legacy files to box, the dav folder no longer loads and i get errors. 

Box has mentioned this is because of the high volume of files i have on my box account. I'm wondering if there are any workarounds for this issue.

Thanks!!
Bill

**Comment by evert** [comment]
Hi Bill,

There are some solutions to improving this. A major one is that we're going to be working on a feature in a future release that allow directories to be 'streamed' to the user, whereas now the entire directory index needs to be compiled and buffered as a whole.

However, the real bottleneck this solves is a large amount of entires in a single directory. 1M files should be 100% fine as long as you don't have massive folders by themselves. If a folder has at most 1000 files and/or subdirectories, it should work pretty well with cyberduck (files in subdirectories don't count towards that, it's really about total entries in a single directory).

If you have this, there's no reason on the sabre/dav end for this to be slow and it could be a problem in the box.com system (or a bug maybe?). In that case you can definitely relay I'd be happy to work with box.com developers towards improving sabre/dav and their implementation.

**Comment by evert** [comment]
Closing this because there's no real actionable item here for us.
