### ISSUE TITLE
How to use MOVE or COPY methods with webdav client?

### ISSUE THREAD

**Issue by quentinsikana** [fruux/sabre-dav#897]
Hello,

I'm using Sabre/DAV and I want to copy and rename files.

Since there is no example about COPY and MOVE methods in the [documentation](http://sabre.io/dav/davclient/), I found a syntax example [here](http://pierresarazin.com/315/move-of-a-file-over-webdav-using-sabre/).

So my code looks like this:

```
use Sabre\DAV\Client;

$settings = array(
     'baseUri' => $this->basePath,
     'userName' => $this->webDavLogin,
     'password' => $this->webDavPassword,
);

$client = new Client($settings);

$response = $client->request(
    'COPY',
    'dav/output/myfile.jpg',
    null,
    array(
        'Host' => $this->basePath,
        'Destination' => $this->basePath.'/dav/output/myfile2.jpg',
        'Overwrite' => 'T',
    )
);
```

But I get a "400 Bad Request" error.

What am I doing wrong here?

Thanks for any help!

**Comment by quentinsikana** [comment]
Hello again, I found the solution to my problem: I just removed the basePath from my destination url.

So 
`'Destination' => $this->basePath.'/dav/output/myfile2.jpg',` 
becomes 
`'Destination' => '/dav/output/myfile2.jpg',`

I hope this will help someone else.

**Comment by evert** [comment]
Glad you figured it out!
