### ISSUE TITLE
Why recurring events are only allowed to generate 3500 instances ?

### ISSUE THREAD

**Issue by strokyl** [fruux/sabre-dav#899]
Hello,
Using Sabre 3.2.0, when I create a recurring event with a RRULE count property greater than 3499 I got the following error.

`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.0/s:sabredav-version
  <s:exception>Sabre\VObject\Recur\MaxInstancesExceededException/s:exception
  <s:message>Recurring events are only allowed to generate 3500/s:message
  <s:file>/var/www/vendor/sabre/vobject/lib/Recur/EventIterator.php/s:file
  <s:line>312/s:line
  <s:code>0/s:code
  <s:stacktrace>#0 /var/www/lib/CalDAV/Backend/Mongo.php(788): Sabre\VObject\Recur\EventIterator-&gt;valid()
#1 /var/www/lib/CalDAV/Backend/Mongo.php(288): ESN\CalDAV\Backend\Mongo-&gt;getDenormalizedData('BEGIN:VCALENDAR...')
#2 /var/www/vendor/sabre/dav/lib/CalDAV/Calendar.php(201): ESN\CalDAV\Backend\Mongo-&gt;createCalendarObject(Array, '309f362f-75fa-4...', 'BEGIN:VCALENDAR...')
#3 /var/www/vendor/sabre/dav/lib/DAV/Server.php(1072): Sabre\CalDAV\Calendar-&gt;createFile('309f362f-75fa-4...', 'BEGIN:VCALENDAR...')
#4 /var/www/vendor/sabre/dav/lib/DAV/CorePlugin.php(525): Sabre\DAV\Server-&gt;createFile('calendars/57fd0...', Resource id #5, NULL)
#5 [internal function]: Sabre\DAV\CorePlugin-&gt;httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/vendor/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#7 /var/www/vendor/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter-&gt;emit('method:PUT', Array)
#8 /var/www/vendor/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /var/www/server.php(169): Sabre\DAV\Server-&gt;exec()
#10 {main}/s:stacktrace

/d:error`

I can reproduce the same error using a big date for the until property.
Then I create a recurring event that never end and I was really surprised to see that in fact it does not repeat more than a certain amount of times, is it wanted ?
##

**Comment by DominikTo** [comment]
Events are generated by the fruux/sabre-vobject library, which indeed [limits the number of recurrences](https://github.com/fruux/sabre-vobject/blob/4.1.1/lib/Recur/EventIterator.php#L311).

It is possible to configure to [configure](https://github.com/fruux/sabre-vobject/blob/4.1.1/lib/Settings.php#L54) the `$maxRecurrences` though. Also check the previous link for info about why this setting exists.

**Comment by evert** [comment]
The main reason is because it's possible otherwise to construct an event that DDOS's the server.

I picked 3500 because it's it would be enough for a single daily event, spanning 10 years. It also covers birthdays (nobody would go over a 100 recurrences really).

What's your use-case?

**Comment by strokyl** [comment]
Thank you for your answer

I understand the concern about preventing the Sabre server computing too much instances.
But I do not understand why this limit is done at the creation of the event.
I think it will be better to expand instances at the last time possible and to impose a limit about the number of recurring event at this moment. Like that we will only limit user in the size of period asked and not limit theme on the size of recurring event.
I do not have a particular use-case but I think it's a bug to have recurring event, that should never, actually end one day.
I think there could have some use-case where a recurring event would be on a period of 10 or 20 years. But I do not see a use-case where a user would like to have all the event on period as big as 10 years.
I do not know if I am clear enough on my explanation or if I miss something that will make impossible to implement my suggestion.

**Comment by evert** [comment]
Can you share the exact event you're uploading? This is definitely starting to sound like a bug.

sabre/dav _should_ currently detect infinitely recurring events, and handle these correctly. This is indeed a common use-case.

**Comment by strokyl** [comment]
For example if I create this event that recur every day for always and that start the 13 october 1980
`BEGIN:VCALENDAR
BEGIN:VEVENT
UID:b448ea7f-4910-4c6c-8a18-a0ed418b3ed2
TRANSP:OPAQUE
DTSTART;TZID=Europe/Berlin:19801013T140000
DTEND;TZID=Europe/Berlin:19801013T150000
ORGANIZER;CN=admin admin:mailto:admin@open-paas.org
SUMMARY:test rec very day
RRULE:FREQ=DAILY
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=FALSE;ROLE=CHAIR:mailto:admin@open-paas.org
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR`

Then when I ask for a period around today, I have the following error:

`<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.0</s:sabredav-version>
  <s:exception>Sabre\VObject\Recur\MaxInstancesExceededException</s:exception>
  <s:message>Recurring events are only allowed to generate 3500</s:message>
  <s:file>/var/www/vendor/sabre/vobject/lib/Recur/EventIterator.php</s:file>
  <s:line>312</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 /var/www/vendor/sabre/vobject/lib/Recur/EventIterator.php(410): Sabre\VObject\Recur\EventIterator-&gt;valid()
#1 /var/www/vendor/sabre/vobject/lib/Component/VEvent.php(49): Sabre\VObject\Recur\EventIterator-&gt;fastForward(Object(DateTimeImmutable))
#2 /var/www/vendor/sabre/dav/lib/CalDAV/CalendarQueryValidator.php(291): Sabre\VObject\Component\VEvent-&gt;isInTimeRange(Object(DateTimeImmutable), Object(DateTimeImmutable))
#3 /var/www/vendor/sabre/dav/lib/CalDAV/CalendarQueryValidator.php(79): Sabre\CalDAV\CalendarQueryValidator-&gt;validateTimeRange(Object(Sabre\VObject\Component\VEvent), Object(DateTimeImmutable), Object(DateTimeImmutable))
#4 /var/www/vendor/sabre/dav/lib/CalDAV/CalendarQueryValidator.php(41): Sabre\CalDAV\CalendarQueryValidator-&gt;validateCompFilters(Object(Sabre\VObject\Component\VCalendar), Array)
#5 /var/www/vendor/sabre/dav/lib/CalDAV/Backend/AbstractBackend.php(145): Sabre\CalDAV\CalendarQueryValidator-&gt;validate(Object(Sabre\VObject\Component\VCalendar), Array)
#6 /var/www/lib/CalDAV/Backend/Mongo.php(402): Sabre\CalDAV\Backend\AbstractBackend-&gt;validateFilterForObject(Array, Array)
#7 /var/www/vendor/sabre/dav/lib/CalDAV/Calendar.php(372): ESN\CalDAV\Backend\Mongo-&gt;calendarQuery(Array, Array)
#8 /var/www/lib/JSON/Plugin.php(395): Sabre\CalDAV\Calendar-&gt;calendarQuery(Array)
#9 /var/www/lib/JSON/Plugin.php(50): ESN\JSON\Plugin-&gt;getCalendarObjects('calendars/57fd0...', Object(Sabre\CalDAV\SharedCalendar), Object(stdClass))
#10 [internal function]: ESN\JSON\Plugin-&gt;httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#11 /var/www/vendor/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#12 /var/www/vendor/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter-&gt;emit('method:REPORT', Array)
#13 /var/www/vendor/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#14 /var/www/server.php(169): Sabre\DAV\Server-&gt;exec()
#15 {main}</s:stacktrace>
</d:error>
`

**Comment by evert** [comment]
That makes sense, but it's not the same problem that you described earlier.

This definitely to me falls in a category of 'unrealistic use-case'. Even though iCalendar allows it, we need to impose some limits around what we think are realistic use-cases.

`PUT`ing this request should work just fine, because it should correctly be identified as an infinite recurrence.

**Comment by strokyl** [comment]
I did not notice it cause an error until today sorry, I thought it just does not expand the event.

But this case is for sure very problematic and a 'unrealistic use-case'. Because that someone create a infinite event every day, on a system that use Sabre on day and that system is always in use 10 year after is definitely something that could happen.

When do you expand the event, why don't you expand the event only on the asked period by the user ?

**Comment by evert** [comment]
> Because that someone create a infinite event every day, on a system that use Sabre on day and that system is always in use 10 year after is definitely something that could happen.

Yea it's not impossible, but that's also partially why I wanted to wait and see what people do with this and what problems people are running into. That's why I'm not really interested in the case where you create a daily event from january 1st, 1970, because it's not real. Instead, give me a real-world example of when you ran into a problem and based on what we might be able to figure out how to better handle that scenario, instead of your fictional one.

> When do you expand the event, why don't you expand the event only on the asked period by the user ?

Because for many, many recurrences we _must_ calculate every previous recurrence to figure out which recurrences fall in the requested time period. The simplest example is a recurrence with `COUNT` (we need to count recurrences to know for sure that it's still recurring in that time period), but there's a lot of other situations that are not as simple as that.

If it's _just_ a `DAILY` rule and 0 other restrictions, I agree that's a specific case we can optimize for and just 'skip ahead' to that time period, but I've not optimized these type of scenarios yet until I get to the point where I have real-world use-cases where this is beneficial. I don't want to make the already complex code even more complicated unless I can measure the benefit it brings.

**Comment by strokyl** [comment]
I understand your point and for expanding event in our frontend using ICAL.js, I know ICAL.js have the same issue because they provide a iterator that can only start from the start of the master and not from a arbitrary start.
For information, for our front-end expand of a recurring event on a specific period, we for the moment do expand from the beginning of the recurring event even if it's way before the beginning of the period. I made a test with a recurring event starting at 1930 and asking a period around today it took about 3 second to our code to finish expanding the event.
I definitely agree with the fact, you don't want to take care of a bug before it really happen in a real situation. But will you accept a PR to improve that issue if by miracle we find time to work on it ?
Don't you thing that at least when a requested period has a 'too big recurring event' should just be ignored instead of making the response of the full period (that could include other event) fail ?

**Comment by evert** [comment]
I would actually be happy to do this fix myself, _if_ you can send me some specific examples of _real_ situations where we're currently breaking.

But yes, for those situations I would also accept patches. The key here is real cases though.

**Comment by evert** [comment]
No further feedback received.
