### ISSUE TITLE
WebDav Nginx Problem

### ISSUE THREAD

**Issue by SystemhausSaarland** [fruux/sabre-dav#902]
Hay there, everytime when i try to open a folder or file via Browser on https://myurl.com//groupoffice/modules/dav/files.php it ends in 404. 
example i try to open https://myurl.com/groupoffice/modules/dav/files.php/Shared i click on the Shared it ends in 404.
The Server is using NGinx and FastCGI.

What Nginx directives do i need to set?
Hope you can help me. Thx

**Comment by evert** [comment]
Hi, since you are running GroupOffice, you should report the bug there. GroupOffice is a user of sabre/dav. We're basically just another library for them.
