### ISSUE TITLE
fruux to support photo with link/url?

### ISSUE THREAD

**Issue by neandr** [fruux/sabre-dav#905]
The RFC allows to define a photo on a vcard also with an url: https://tools.ietf.org/html/rfc6350#section-6.2.4
fuux/contacts doesn't show the photo after importing such a vcard. Also exporting that card from fruux holds it, so no detail is lost .. which is good.
Will fruux/contact somehow support photo/link?

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39293960-fruux-to-support-photo-with-link-url?utm_campaign=plugin&utm_content=tracker%2F294006&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F294006&utm_medium=issues&utm_source=github).

**Comment by evert** [comment]
The only thing fruux will in the future support is the ability to automatically turn an existing embedded PHOTO in a URI that fruux itself hosts. We won't allow external URI's due to security concerns.
