### ISSUE TITLE
vCard with 'CATEGORIES'

### ISSUE THREAD

**Issue by neandr** [fruux/sabre-dav#907]
https://tools.ietf.org/html/rfc6350#section-6.7.1 defines for 'Categories':
>    Purpose:  To specify application category information about the vCard, also known as "tags".
>    Value type:  One or more text values separated by a COMMA character (U+002C).

Importing a vCard with multiple Categories and exporting the card shows loosing data. 
Example with a card including the RFC example, doing some edit and exporting gives the following:

```
BEGIN:VCARD
VERSION:3.0
PRODID;VALUE=TEXT:-//TB//vContacts//-alpha0.1//EN
FN:Contact w tags
CATEGORIES:TRAVEL AGENT
CATEGORIES:INTERNET,IETF,INDUSTRY,INFORMATION TECHNOLOGY
UID:38f1c981-c2a7-449e-99f6-b4704d0aaba4
END:VCARD
```

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.0.0-alpha3//EN
FN:Contact w tags
N:;Contact w tags;;;
NICKNAME:tag testing
CATEGORIES:INTERNET
UID:38f1c981-c2a7-449e-99f6-b4704d0aaba4
REV:2016-11-18T15:53:25Z
END:VCARD
```
 It seems, the second definition overwrites the first, and also only the first definition is handled. RFC says something different ( see above).

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39362038-vcard-with-categories?utm_campaign=plugin&utm_content=tracker%2F294006&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F294006&utm_medium=issues&utm_source=github).

**Comment by evert** [comment]
Hi @neandr ,

The correct way to interpret the first body is that this:

``` 
CATEGORIES:TRAVEL AGENT
CATEGORIES:INTERNET,IETF,INDUSTRY,INFORMATION TECHNOLOGY
````

Actually becomes:

```
[
  'TRAVEL AGENT',
  'INTERNET',
  'IETF',
  'INDUSTRY',
  'INFORMATION TECHNOLOGY'
]
```

**Comment by neandr** [comment]
Yes,  that's what it should bei.  But import a contact/vcard with those 2 'CATEGORIES' into fruux contact. The only way to Check is to export. And there is only INTERNET. 
Missing  the others
