### ISSUE TITLE
IMAP Auth: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by c0d3z3r0** [fruux/sabre-dav#915]
sebastian-schmid | commented 2 hours ago
Hello @evert @c0d3z3r0 ,

I tested this piece of code but on my first try it did not work.

I think in IMAP.php the following part has to be part of the catch block:
foreach (imap_errors() as $error)
error_log($error);

after I moved the code into the catch block it works.

Better than a /readonly connect to IMAP is the OP_HALFOPEN option I think, should be faster and no mailbox will be touched:
$imap = imap_open($mailbox, $username, $password, OP_HALFOPEN, 1);

------------------------------------------------------------------------------------------------------

c0d3z3r0 commented 2 hours ago
@sebastian-schmid the imap_errors have to be read in every case. Otherwise you'd get an Exception / PHP Notice: https://secure.php.net/manual/de/function.imap-errors.php

What do you mean by "it did not work"? Were there any errors, exceptions etc.?

OP_HALFOPEN may be a good idea but needs to be tested.

------------------------------------------------------------------------------------------------------

sebastian-schmid commented an hour ago
@c0d3z3r0 yes, it did not work - means authentication did not work. IMAP open was successful as I could see in the dovecot log. But on calendar clients I got "invalid User and/or password".

And over Webbrowser I got "Invalid argument supplied for foreach()" error message in sabre/dav xml response. After moving this into the catch block it worked as expected.

OP_HALFOPEN is working at my installation, but would be great if somebody else can verify this.

------------------------------------------------------------------------------------------------------

c0d3z3r0 commented an hour ago • edited
I have to check this on my setup....
In the meantime, could you provide some more information (PHP version etc.), logs from php-fpm, the exact xml response...?

------------------------------------------------------------------------------------------------------

c0d3z3r0 commented 5 minutes ago
@sebastian-schmid IMAP auth is working correctly on my systems... also the travis checks passed without any errors.

When you move the for loop into the catch block, it'll be never run... that's why it's working then but I don't know why it fails for you

------------------------------------------------------------------------------------------------------

sebastian-schmid commented 2 minutes ago
Of course:

PHP Version: 5.5.38 (PHP nativ no php-fpm)
Dovecot: 2.1.7

sabre/dav XML response:
<d:error>
<s:sabredav-version>3.2.0</s:sabredav-version>
<s:exception>ErrorException</s:exception>
<s:message>Invalid argument supplied for foreach()</s:message>
</d:error>

In Apache Logs are no errors logged and dovecot login is successful.

**Comment by c0d3z3r0** [comment]
#914

**Comment by sebastian-schmid** [comment]
Interesting that it's working on your setup.

Looks to me that "imap_errors()" is not returning any error if imap_open was successful. 
In this case if imap_open() was successful there is no need for this foreach to be executed I think.

**Comment by c0d3z3r0** [comment]
Yep, you're right. I always have at least one error since I'm not using TLS (on localhost.. so it's fine without..). That is why it works for me.
Fixed in #914

**Comment by sebastian-schmid** [comment]
That explains it.

Thanks for submitting a merge request to fix this. Your solution is better than my dirty move to the catch block ;)
