### ISSUE TITLE
database indexes probably missing?

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#918]
_From @derStephan on November 28, 2016 8:22_

Hi, 

out of curiosity, I opened db.sqlite in a database manager. Without knowing any reading sql command it seems odd that there are so few indexes. 

Let's take "calendarobjects" as an example. There is only a primary key on column "ID". But I would imagine that the normal use case is: the client asks for all objects of a specific calendar (column "calendarid") within a time span (is that in columns "firstoccurence" and "lastoccurence"?)

So an index over calendarid, firstoccurence, lastoccurence may be useful. 

Again: I did not look over the real sql commands but I can hardly imagine, that you query this table only by IDs.

_Copied from original issue: fruux/Baikal#633_

**Comment by evert** [comment]
Hey! You're not wrong. There's a pretty low amount of sql indexes in the sqlite files. MySQL is a lot better in that regard. This is definitely worth fixing.

**Comment by evert** [comment]
_From @derStephan on November 29, 2016 6:19_

Hey, thanks for your quick reply.

So this may have a serious performance impact when it comes to a lot of objects within the database. Maybe some hint during installation regarding performance of baikal with the different databases may be useful? 
As far as I can see it, sqlite is seen as the standard database engine, so there should be some kind of help to decide which database suits what load.

**Comment by derStephan** [comment]
Thanks for that. I just got a brief glimpse on these indexes and have 2 additional questions. 

1. Are there really no queries involving event dates? These should speed up things quite a bit when you have lots of events within one single calendar. 
2. I did not see any ALTER-Commands for upgrades of existing installations. How will this be done?

**Comment by evert** [comment]
Hi @derStephan ,

I missed the index on the `firstoccurence` field, but added this now. There's no ALTER TABLE commands yet, but I will eventually get around this when I'm closer to the 3.3 release and I'm writing the migration scripts.

In the meantime you can just apply the indexes manually for a speed boost. If you are seeing performance problems though, you might also consider switching to MySQL, which will probably be faster.

**Comment by derStephan** [comment]
Thanks. Keep up your great work!

**Comment by derStephan** [comment]
@evert 

I just checked again. 

https://github.com/fruux/sabre-dav/blob/master/examples/sql/sqlite.calendars.sql

There is no index which includes ``firstoccurence``. Do I miss something or did you? 😃

**Comment by staabm** [comment]
the change was committed to 3.3, not master yet.
https://github.com/fruux/sabre-dav/pull/922

**Comment by evert** [comment]
3.3 is where most of the development happens. Master will eventually be 4.0 but 3.3 isn't even released yet.
