### ISSUE TITLE
Faulty version of sabre-http as requirement in latest SabreDAV composer release

### ISSUE THREAD

**Issue by memmaker** [fruux/sabre-dav#926]
The current release version of SabreDAV bundles a faulty version of sabre-http (4.2.1).

If PHP is set to print out warnings, this release of sabre-http produces warnings in the output if a content-length header has been set, thus rendering the XML output invalid:

`stream_get_contents() expects parameter 2 to be integer, string given in /code/vendor/sabre/http/lib/Message.php on line 81`

Current versions of sabre-http have fixed this bug by casting the content-length to int.

If we could have the current composer file of SabreDAV pointing to a fixed release, this would not be an issue anymore.

**Comment by evert** [comment]
odd issue, because I think it should only appear when sabre/http is ran in strict-mode. I'm gonna add some tests to see if I can reproduce this.

**Comment by evert** [comment]
This issue was moved to fruux/sabre-http#72
