### ISSUE TITLE
Release of next version?

### ISSUE THREAD

**Issue by petrkotek** [fruux/sabre-dav#928]
Hi @evert & the team,

I was wondering when is next release (tag) of `sabre/dav` planned? I'm particularly interested in current `dev-master` changes in `sabre/http` (i.e. changes which are not in `sabre/http-4.2.2`).

(we currently have to use our forks, which is not great)

Thanks a lot for maintaining this project!

**Comment by evert** [comment]
Hey, we don't currently have a plan. Most of my focus is currently on getting a Baikal version out. I'll also probably release sabre/dav 3.3 before dev-master (which will become sabre/dav 4).

I just don't have enough time these days to work on things and I don't want that to be the cause of more unstable software. So unfortunately I can only say "it's done when it's done".
