### ISSUE TITLE
Is it possible to return an error and stop the rest operation on CalDAV client?

### ISSUE THREAD

**Issue by halilibrahim** [fruux/sabre-dav#929]
I want to block user (which has read-write permission on calendar) while deleting some calendar objects.
I've modified deleteCalendarObject method of Sabre\CalDAV\Backend\PDO to return error on specified conditions.
Now my server returns status 500 and the exception detail (and keeps the object) as i've expected. But the client (calendar app on iPhone) deletes the event from phone's local storage and it keeps trying to delete the event again by sending same request before every interaction with server.

Sample exception response of the operation:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.0</s:sabredav-version>
  <s:exception>InvalidArgumentException</s:exception>
  <s:message>You can't delete a pinned event!</s:message>
</d:error>
```

Does sabre-dav have exception classes which also stops the CalDAV client?
(If sabre-dav doesn't have such classes) Does CalDAV support such an error handling mechanism?

**Comment by evert** [comment]
Hi @halilibrahim ,

Exceptions that are not recognized are automatically turned into a HTTP 500, as you noticed. If you throw a forbidden event, it might work. The exception classes are in lib/Sabre/DAV/Exception (including Forbidden).

Give that a shot.
