### ISSUE TITLE
Response for preflight has invalid HTTP status code 401

### ISSUE THREAD

**Issue by MetallianFR68** [fruux/sabre-dav#930]
When I try to access the webdav server using a script that runs from a different server (cross-origin requests known as CORS), I get this error : Response for preflight has invalid HTTP status code 401

Check the JS error console here : https://www.ajaxbrowser.com/?CrossDomainDemo
The problem is the same with Evert's DAVCLIENT.JS library

The problem seems related to the fact that sabredav requires authorization to answer to OPTIONS requests but this is non standard behaviour.

I tried adding these headers in my server.php file, but this doesn't change anything:
header("Access-Control-Allow-Origin: https://www.ajaxbrowser.com");
header("Access-Control-Allow-Credentials: true");
header("Access-Control-Allow-Methods: ACL, CANCELUPLOAD, CHECKIN, CHECKOUT, COPY, DELETE, GET, HEAD, LOCK, MKCALENDAR, MKCOL, MOVE, OPTIONS, POST, PROPFIND, PROPPATCH, PUT, REPORT, SEARCH, UNCHECKOUT, UNLOCK, UPDATE, VERSION-CONTROL");
header("Access-Control-Allow-Headers: Overwrite, Destination, Content-Type, Depth, User-Agent, Translate, Range, Content-Range, Timeout, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control, Location, Lock-Token, If");
header("Access-Control-Expose-Headers: DAV, content-length, Allow");

Any idea ?

**Comment by MetallianFR68** [comment]
you can also check this site for more information on the subject : https://www.webdavsystem.com/ajaxfilebrowser/programming/cross_domain

**Comment by evert** [comment]
This is not a bug and not non-standard. Responding to a 401 on a OPTIONS request is actually required by some DAV clients.

The right solution is to create a CORS plugin that returns the correct headers and does not return a 200 response, but only for CORS pre-flight requests and nothing else. It is possible to detect whether something was a CORS pre-flight or not.
