### ISSUE TITLE
Read Error

### ISSUE THREAD

**Issue by jarodium** [fruux/sabre-dav#931]
Hello I found out an error while doing this:

```php
$client = new Sabre\DAV\Client($apis["cloud1"]);
$response = $client->propfind($user["token"], array(
   '{DAV:}displayname',
   '{DAV:}getcontentlength'
));
```

Below is the issued error:

[Fri Jan 13 18:09:23 2017] [error] [client X.X.X.X] PHP Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /vendor/sabre/xml/lib/Reader.php on line 79

**Comment by staabm** [comment]
Looks like your php version is to old?

**Comment by jarodium** [comment]
I have 5.4 but I can use the lib to write to DAV... I'll try using sabre 3.0 and post back.

**Comment by jarodium** [comment]
Still having the same issue having switched back to 3.0.0.
Here is the composer entry:
"sabre/dav": "3.0.0"

sabre/event is at 2.0.2 and sabre/dav is at 3.0.0

I'm using the new keyword in the code, since i'm calling it from a class function. Not sure if that is the reason its having issues...

**Comment by evert** [comment]
I hope you're using sabre/dav 3.0.9, and not 3.0.0. Are you getting the exact same error with that version?

By the way, you should really just be using supported PHP versions. 5.4 is out of support for a long while now. There's no excuse!

**Comment by jarodium** [comment]
@evert yes I am. 

You are absolutely right about using supported versions, but unfortunately for me, there is no officially supported version of PHP7 at Openshift. Although there is a community version for PHP7, it does not receive automatic security updates and does not have Apache with it.

**Comment by evert** [comment]
How did you install sabre/dav?

**Comment by jarodium** [comment]
My composer.json looks like this:

{
    "require": {
        "altorouter/altorouter": "1.1.0",
        "sabre/dav": "3.0.9"
    }
}

At the sabre/xml composer.json i see this:

"require" : {
        "php" : ">=5.5.5",
        "ext-xmlwriter" : "*",
        "ext-xmlreader" : "*",
        "ext-dom" : "*",
        "lib-libxml" : ">=2.6.20",
        "sabre/uri" : ">=1.0,<3.0.0"
    },

**Comment by evert** [comment]
In that case the wrong sabre/xml got installed. Try reinstalling it. This won't work correctly unless you are actually running this on PHP 5.4.

**Comment by jarodium** [comment]
I see now that sabre/xml 1.5.0 is installed. Will try and post back results.

**Comment by jarodium** [comment]
Still same error.

**Comment by evert** [comment]
Please do some more investigation. You should be getting 1.4.x which does not use `finally`.

**Comment by evert** [comment]
1.5.x won't even install on PHP 5.4.

**Comment by jarodium** [comment]
I believe this is a composer issue. I will try to force sabre/xml to 1.4.x

**Comment by evert** [comment]
Composer is behaving as expected. The problem is more likely that you are running composer on a newer version of PHP later than 5.5, but then you run the actual application runs on PHP 5.4.

**Comment by jarodium** [comment]
I just got into that myself. but thanks for pointing me that :D
