### ISSUE TITLE
macOS Calendar gets 403 response for PROPPATCH and stops after that

### ISSUE THREAD

**Issue by felixkiss** [fruux/sabre-dav#935]
I use `sabre/dav` in my project to build a read-only CalDAV interface to the data of my web application.

Sabre version: 3.2.0

The following parts are custom, implemented by my application:
 - `CustomAuthBackend` extending `Sabre\DAV\Auth\Backend\AbstractBasic`
 - `CustomPrincipalBackend` implementing `Sabre\DAVACL\PrincipalBackend\BackendInterface`
 - `CustomCalendarBackend` implementing `Sabre\CalDAV\Backend\BackendInterface`

I have the following plugins activated:
 - `Sabre\DAV\Auth\Plugin`
 - `Sabre\CalDAV\Plugin`
 - `Sabre\DAVACL\Plugin`
 - `Sabre\DAV\Browser\Plugin`

CalDAV works fine with iOS and Android devices, but now I have tested with macOS' Calendar.app and I can't get it to download the events.

The following happens (observed in Charles Proxy):

1) `PROPFIND /caldav/calendars/felixkiss/` => returns 401
2) `PROPFIND /caldav/calendars/felixkiss/` (with Auth header) => returns 

```
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"> 
	<d:response> 
		<d:href>/caldav/calendars/felixkiss/</d:href> 
		<d:propstat> 
			<d:prop> 
				<d:current-user-privilege-set> 
					<d:privilege> 
						<d:write /> 
					</d:privilege> 
					<d:privilege> 
						<d:write-properties /> 
					</d:privilege> 
					<d:privilege> 
						<d:write-content /> 
					</d:privilege> 
					<d:privilege> 
						<d:unlock /> 
					</d:privilege> 
					<d:privilege> 
						<d:bind /> 
					</d:privilege> 
					<d:privilege> 
						<d:unbind /> 
					</d:privilege> 
					<d:privilege> 
						<d:write-acl /> 
					</d:privilege> 
					<d:privilege> 
						<d:read /> 
					</d:privilege> 
					<d:privilege> 
						<d:read-acl /> 
					</d:privilege> 
					<d:privilege> 
						<d:read-current-user-privilege-set /> 
					</d:privilege> 
				</d:current-user-privilege-set> 
				<d:owner> 
					<d:href>/caldav/principals/felixkiss/</d:href> 
				</d:owner> 
				<d:resourcetype> 
					<d:collection /> 
				</d:resourcetype> 
				<d:supported-report-set> 
					<d:supported-report> 
						<d:report> 
							<d:expand-property /> 
						</d:report> 
					</d:supported-report> 
					<d:supported-report> 
						<d:report> 
							<d:principal-match /> 
						</d:report> 
					</d:supported-report> 
					<d:supported-report> 
						<d:report> 
							<d:principal-property-search /> 
						</d:report> 
					</d:supported-report> 
					<d:supported-report> 
						<d:report> 
							<d:principal-search-property-set /> 
						</d:report> 
					</d:supported-report> 
				</d:supported-report-set> 
			</d:prop> 
			<d:status>HTTP/1.1 200 OK</d:status> 
		</d:propstat> 
	</d:response> 
</d:multistatus>
```

3) `PROPPATCH /caldav/calendars/felixkiss/`

Request:
```
PROPPATCH /caldav/calendars/felixkiss/ HTTP/1.1
Content-Type: text/xml
Authorization: Basic ZmVsaXhraXNzOmZlbGl4
Connection: keep-alive
Accept: */*
User-Agent: Mac+OS+X/10.12.2 (16C67) CalendarAgent/384
Content-Length: 425
Accept-Language: en-us
Accept-Encoding: gzip, deflate

<?xml version="1.0" encoding="UTF-8"?>
<A:propertyupdate xmlns:A="DAV:"><A:set><A:prop><B:default-alarm-vevent-date xmlns:B="urn:ietf:params:xml:ns:caldav">BEGIN:VALARM&#13;
X-WR-ALARMUID:CC59F3F7-020D-42BA-AA37-3EFD07055D32&#13;
UID:CC59F3F7-020D-42BA-AA37-3EFD07055D32&#13;
TRIGGER:-PT15H&#13;
ATTACH;VALUE=URI:Basso&#13;
ACTION:AUDIO&#13;
END:VALARM&#13;
</B:default-alarm-vevent-date></A:prop></A:set></A:propertyupdate>
```

Response:
```
HTTP/1.1 207 Multi-Status
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Fri, 20 Jan 2017 17:54:53 GMT
Server: Caddy
Status: 207 Multi-Status
Vary: Brief,Prefer
X-Powered-By: PHP/7.0.14
X-Sabre-Version: 3.2.0
Content-Length: 402
Connection: Keep-alive

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/">
 <d:response>
  <d:href>/caldav/calendars/felixkiss</d:href>
  <d:propstat>
   <d:prop>
    <cal:default-alarm-vevent-date/>
   </d:prop>
   <d:status>HTTP/1.1 403 Forbidden</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

4) Another `PROPPATCH` similar to 3), but with `default-alarm-vevent-datetime` instead of `default-alarm-vevent-date`

5) `REPORT /caldav/principals/felixkiss/` => return 401
6) `REPORT /caldav/principals/felixkiss/` (with Auth header) => returns 

```
HTTP/1.1 207 Multi-Status
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Fri, 20 Jan 2017 17:54:53 GMT
Server: Caddy
Status: 207 Multi-Status
X-Powered-By: PHP/7.0.14
X-Sabre-Version: 3.2.0
Content-Length: 429
Connection: Keep-alive

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/">
 <d:response>
  <d:href>/caldav/principals/felixkiss/</d:href>
  <d:propstat>
   <d:prop>
    <cs:calendar-proxy-read-for/>
    <cs:calendar-proxy-write-for/>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

---

What I have tried:
 - I thought if request 2) would not return any `write` privileges, the client wouldn't try to set `default-alarm-vevent-date` in the first place, but a custom ACL plugin that only featured the `{DAV:}read` privileges did nothing
 - I searched through all interfaces that I implement myself but couldn't find anything I thought was related.

Any ideas or hints where I can continue debugging?

**Comment by evert** [comment]
Hi @felixkiss ,

Can you try enabling a `PropertyStorage` plugin and try again? The 403 ideally shouldn't be a problem, but maybe something changed in the latest OS X.

The easiest is to enable it with the PDO backend for  testing:

http://sabre.io/dav/property-storage/

It's a _really good idea_ to have this enabled regardless. It will make many clients a bit better.

cc: @DominikTo

**Comment by felixkiss** [comment]
@evert I've tested the property storage. I think now we are getting somewhere.

As you can see in the [request/response pairings that happen](https://gist.github.com/felixkiss/07376ece4c4640228c3e1fbb8ae4baf6), the client actually downloads the event data, but it is not being displayed. In fact, not even the calendar name is displayed in Calendar.app

Do the responses look good now? What might be the problem?

**Comment by evert** [comment]
Hey @felixkiss ,

For some reason, the `cal:supported-calendar-component-set` is wrong. Any idea why that could be?

**Comment by felixkiss** [comment]
Thanks for the hint.

I fixed it in my custom `Sabre\CalDAV\Backend\BackendInterface@getCalendarsForUser` implementation:

before:
```php
'{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set' => ['VEVENT'],
```

after:
```php
'{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set' => new Sabre\CalDAV\Xml\Property\SupportedCalendarComponentSet(['VEVENT']),
```

Everything seems to work now. 🥇 🍻
