### ISSUE TITLE
Could we get a 3.2 series release?

### ISSUE THREAD

**Issue by daniellandau** [fruux/sabre-dav#936]
Any chance of a 3.2 series point release? I'm especially interested in https://github.com/fruux/sabre-dav/issues/889, which has the fix already merged in the 3.2 branch and others.

**Comment by evert** [comment]
Hi @daniellandau ,

I just made some changes for 3.2.1 and also  tagged it. The internet is too slow where I am to generate a build  and upload it,  but on composer 3.2.1 is now the latest stable. .zip build will follow later this weekend.

**Comment by evert** [comment]
This is now publicly released.

**Comment by daniellandau** [comment]
Great, thanks!
