### ISSUE TITLE
Is it possible to combine WebDAV, CalDAV and CardDAV in one php file?

### ISSUE THREAD

**Issue by Offerel** [fruux/sabre-dav#938]
This are my first tests with SabreDAV, so please forgive me, if this is a stupid Question. I'm starting with the examples folder and see, that there are file for caldav, carddav and files. There is also a groupwareserver.php, which seems to combine CalDAV and CardDAV. Can i add there also the Files Plugin, to use the same file also as WebDAV Server or must is use two separate Files?

**Comment by evert** [comment]
Hi @Offerel ,

Yes this is totally possible. The `.php` files in `examples/` are all just examples. They contain the building blocks to build your DAV server with whatever features you might want. A CalDAV, CardDAV  server and WebDAV server can all live on the same endpoint.

Try and figure out what the actual  examples files do. Once you know that, it might be easier to figure out how you might combine it. If you  have more specific questions about this, just ask.
