### ISSUE TITLE
Cant use Windows 10 Client

### ISSUE THREAD

**Issue by Offerel** [fruux/sabre-dav#940]
Sine yesterday i have installed SabreDAV my first time. I could access calendars and contacts fine via Web, eM Client and DavDroid. Syncing works like a charm. Today i would like to connect my Windows 10 Laptop but failed. Primary a have tried the Principal URL https://sub.mydomain.com/dav/groupwareserver.php/principals/username/ like i used in the other Apps, but i failed. I failed also with direct URL to the Calendar and Contacts. I have tried before Baikal and it worked with the Principal URL and Windows 10, but would like to use SabreDAV.

Any Ideas, what i can try?

**Comment by Offerel** [comment]
There come me something in mind: As i could remember, i access Baikal via Basic Auth, but if i use SabeDAV via MySQL, i use Digest. Could it be, that Windows 10 Clients can only connect via Basic Auth and not with Digest?

**Comment by evert** [comment]
Hi @Offerel , I do believe that Windows indeed only supports Basic Auth. Give that a shot and let me know if it worked =) If it didn't, we can re-open this ticket.

**Comment by Offerel** [comment]
I have tested it with Baikal. If I change the Auth to Digest, I can’t sync. If I change it back to Basic-Auth, it works again.

**Comment by evert** [comment]
well, at least we know now =) Basic probably going to be the default in the future. Make sure your server is behind SSL / HTTPS =)

**Comment by staabm** [comment]
As far as I rembee basic auth only works on https on win10
