### ISSUE TITLE
POST Method not implemented error while using Calendar.app

### ISSUE THREAD

**Issue by sporykhin** [fruux/sabre-dav#942]
Hey

I'm trying to implement nextcloud file sharing solution that uses sabre/dav as backend for Calendar web application. In the web browser everything is really nice. Then I connected Calendar.app to this service I got only limited feature list - I cant share calendar and cant send email invitation on some event.
Also I have a lot of errors in server log with main point - **Sabre\DAV\Exception\NotImplemented: HTTP/1.1 501 There was no plugin in the system that was willing to handle this POST method**.

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')

Is it system misconfiguration or some bug? Any help will be appreciated.

**Comment by sporykhin** [comment]
BTW
Calendar.app shows this error 

**The server responded with “501” to operation CalDAVUpdateShareesQueuableOperation.**

**Comment by evert** [comment]
Hi! You should send nextcloud bug reports @ nextcloud. If they find that there's an underlying bug inside sabre/dav, this ticket can be reopened.
