### ISSUE TITLE
Dumb Question how to add Users and Principals

### ISSUE THREAD

**Issue by Offerel** [fruux/sabre-dav#944]
Maybe this is a dumb question, but i cannot find the answer in the FAQ or Doc, so please forgive me, if it is a dumb question.

Currently, im using `$authBackend = new \Sabre\DAV\Auth\Backend\Apache();` also with Nginx, because, so i could use my existing htpasswd files and Authentication. Normally, i would like to use `htpasswd /path/to/.htpasswd username` to add a new User to that file. After this, i could also successfully Login to SabreDAV with the new User.

The Problem is, i couldn't add a Calendar and/or Addressbook because no principal was found. I cant also access the principal URL for this user, to add a new Principal for this User. 

If i try to add a principal for this user with another, existing user (the Admin User), i get the error `Sabre\DAVACL\Exception\NeedPrivileges  User did not have the required privileges ({DAV:}bind) for path "principals"`. 

--> _Why does the Admin does not have that right?_

The only way i could see is, that i add a principal via SQL:

`INSERT INTO principals (uri,email,displayname) VALUES ('principals/username', 'foo@domain.tld','Testuser');`

If i do this, i could now login and add new calendars and addressbooks for this new user.

If i look now in the principals table, i see that the Admin has 2 other principals. principals/admin/calendar-proxy-read and principals/admin/calendar-proxy-write.

--> _Do i need this Principals also for my new User?_

**Comment by evert** [comment]
> --> Why does the Admin does not have that right?

Even if the user is named admin, it actually doesn't get admin privileges right out of the box. You need to explicitly tell the ACL plugin to treat certain principals as admin. For example:

```php
$aclPlugin->adminPrincipals = [
  'principals/admin'
];
```

> If i look now in the principals table, i see that the Admin has 2 other principals. principals/admin/calendar-proxy-read and principals/admin/calendar-proxy-write.
> 
> --> Do i need this Principals also for my new User?

You only need it, if you want 'delegation' support for calendaring. Most clients don't support it, but iCal for example does. If you don't care, you can ignore it, otherwise you just insert a principal that follows that exact pattern.

**Comment by evert** [comment]
Closing this because I think it's answered. If not, feel free to comment here.

**Comment by Offerel** [comment]
Incredible how easy it is. Many, many thx for this info. And thx for fixing #943 , i have made a Testinstallation right now and Syncing works as before now. Basics Test's with real Clients with Android are all passed, but i didn't have made a 100% Testsuite yet. If i have enough time in the next weeks, it's planned to make small synthetic Testsuite for Functional Testing. If its done, i can share it with the Community. I don't know if such thing exists at this time.
