### ISSUE TITLE
Entry "addressbook" missing from DAV header in response to OPTIONS request

### ISSUE THREAD

**Issue by hielsnoppe** [fruux/sabre-dav#945]
First, thanks for building and maintaining Sabre! So far it served me well and is structured very nicely.

I am implementing a custom backend by extending `Sabre\CardDAV\Backend\PDO` and overriding `getCard` and `getCards`. So far I can access an addressbook and the cards therein through the Browser Plugin as well as using `cadaver`.

When I tested with other applications (pycarddav, SOGo Connector, CardBook, CardDAV Browser) they fail, telling me that there is no valid addressbook. From the exception thrown by `pycarddav` I concluded the problem to be a missing entry in the `DAV` header in the response to an OPTION request to the addressbook URL.

This is the actual response that I get:

    HTTP/1.1 200 OK
    Date: Mon, 13 Feb 2017 02:13:34 GMT
    Server: Apache/2.4.16 (Ubuntu)
    X-Sabre-Version: 3.2.1
    Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT
    DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search
    MS-Author-Via: DAV
    Accept-Ranges: bytes
    Content-Length: 0
    Keep-Alive: timeout=5, max=99
    Connection: Keep-Alive
    Content-Type: text/html; charset=UTF-8

The `DAV` header should read as follows, though:

    DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, addressbook

Since `pycarddav` claims to be compatible with Sabre in general, I think, that I have made a mistake in my implementation, but I don't seem to be able to find it. Now I wonder, whether you could help me out on that? Many thanks in advance!

**Comment by hielsnoppe** [comment]
My bad, I forgot to add the `CardDAV\Plugin` to my server:

        // CardDAV plugin
        $server->addPlugin(new \Sabre\CardDAV\Plugin());

I think this results from the example in the combined [integration guide for CalDAV and CardDAV](http://sabre.io/dav/caldav-carddav-integration-guide/). Maybe the example should be that of a complete groupware server as in `examples/groupwareserver.php`?

**Comment by evert** [comment]
Hi @hielsnoppe ,

I added the carddav plugin to that page, thank you!
