### ISSUE TITLE
add Content-Length header when returning xmls

### ISSUE THREAD

**Issue by PechenTreski** [fruux/sabre-dav#949]
(I copy the text from https://github.com/nextcloud/server/issues/3724, since they tell me to place it here)

### Steps to reproduce
1. make a request like https://nextcloud.example.com/remote.php/dav/addressbooks/users/juza/contacts/
2. take a look at response headers
3. "content-type:application/xml; charset=utf-8" presents, but there is no header about the content length :)

### Expected behaviour
Content-Length should present, so nginx could compress the response with gzip

### Actual behaviour
No headers make nginx ignore compressing. My nextcloud server is run at home, where I have only 5 Mbps of upload speed, so the list of contacts is being downloaded for 3 annoying sec

### Server configuration
**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Contacts version:** (see Nextcloud apps page) 1.5.3

**Comment by evert** [comment]
Hi,

This is not happening, because it will prevent us from streaming the response to the client. We're moving towards a streaming model, and we can't predict how big the xml responses will be when we start sending headers.
