### ISSUE TITLE
Method PROPFIND did not work correctly?

### ISSUE THREAD

**Issue by SerafimArts** [fruux/sabre-dav#950]
## Positive example 1:
 
- Request: `PROPFIND ....`
- Response: `Status: 404 Not Found`

---

**Expected**: ClientHttpException
**Actual**:  DAV\Client throws a "ClientHttpException": https://github.com/fruux/sabre-dav/blob/e987775e619728f12205606c9cc3ee565ffb1516/lib/DAV/Client.php#L234

## Negative example 2:

- Request: `PROPFIND ....`
- Response: `StatusCode 207 Multi-Status` with body:

```php
<?xml version="1.0" encoding="utf-8" ?>\n
<D:multistatus xmlns:D="DAV:">\n
    <D:response>\n
        <D:href>/some/any.jpg</D:href>\n
        <D:propstat>\n
            <D:prop></D:prop>\n
            <D:status>HTTP/1.1 404 Not Found</D:status>\n
        </D:propstat>\n
    </D:response>\n
</D:multistatus>\n
```

---

**Expected**: ClientHttpException
**Actual**:  DAV\Client returns and empty array: https://github.com/fruux/sabre-dav/blob/e987775e619728f12205606c9cc3ee565ffb1516/lib/DAV/Client.php#L243

**Comment by evert** [comment]
This is expected. The resource _is_ found, but the properties are _not_. This should not result in a 404.
