### ISSUE TITLE
Microsoft Word in read-only mode because "bad response" for LOCK?

### ISSUE THREAD

**Issue by km-77** [fruux/sabre-dav#955]
Hi,

I have came across this great project just few days ago. I know the
development is closed, but perhaps someone will able to help me. 

I can't force Microsoft Word to open file in read-write mode.
When I put an URL in address bar:

**ms-word:ofe|u|https://my.domain/sabredav/server/test3.doc**

Microsoft Word opens with warning about the internet location, then 
it opens the file but in read-only mode. I'm pretty sure, that I do
everything as it should be. Perhaps someone could help me.

**I tried to debug the exchanged data (using Charles ) and saw that when Office sends
LOCK message it doesn't get the answer back (Response = 400 Bad Request)**

So I think that this is the reason why Office blocks edit mode. The question is - why
LOCKING does not work on server site.

request from Word:

```
<D:lockinfo xmlns:D="DAV:">
	<D:lockscope>
		<D:exclusive />
	</D:lockscope>
	<D:locktype>
		<D:write />
	</D:locktype>
	<D:owner>
		<D:href>computerid/user</D:href>
	</D:owner>
</D:lockinfo>
```

answer from server:

```
<HTML>
<HEAD>

	<TITLE>400 Bad Request</TITLE>

</HEAD>
<BODY BGCOLOR=#FFFFFF>

	<H1>400 Bad Request</H1>
	Your browser sent a request that this server could not understand.

</BODY>
</HTML>
```

My server.php code:

```
require 'vendor/autoload.php';
use
    Sabre\DAV;
$rootDirectory = new DAV\FS\Directory('public2');
$server = new DAV\Server($rootDirectory);
$server->setBaseUri('/sabredav/server');
$lockBackend = new DAV\Locks\Backend\File('data/locks');
$lockPlugin = new DAV\Locks\Plugin($lockBackend);
$server->addPlugin($lockPlugin);
\Sabre\DAV\Xml\Property\LockDiscovery::$hideLockRoot = true;
$server->addPlugin(new DAV\Browser\Plugin());
$server->exec();

```

My .htaccess

```
RewriteEngine On
RewriteRule ^sabredav/server/([^/]*)$ /sabredav/server.php/$1 [L]
```

The structure of my folders

-sabredav
   - bin
   - data
   - examples
   - public2
   - vendor
    server.php

The environment
- Windows 8.1
- Microsoft Office 2010 SP2 

Anyone knows what can be wrong?

Thank you,
Konrad

**Comment by km-77** [comment]
At this moment I think that the source of the problem is that my hosting does not allow HTTP requests with LOCK method. So when Office sends HTTP request with LOCK method - it doesn't get the answer. And as it does not get the answer - it opens .doc file in read-only mode.

**Comment by Hywan** [comment]
Hello @km-77,

> I  know the development is closed, but perhaps someone will able to help me.

This is not true 🙂. The main maintainer is transitionning its activity to someone else. This is totally different 😉.

About your issue, I think this is because of Apache indeed. The response is generated by Apache, not by sabre/dav. You will find some examples here, https://github.com/fruux/sabre-dav/tree/master/examples/webserver. I am not an expert with Apache, but it should foward to request to PHP FCGI, and so to sabre/dav. Here, it catches it. Have you been able to reach the admin part of sabre/dav though the same server?

**Comment by km-77** [comment]
Hello Hywan,

Thank you. I'm almost 100% sure that the http LOCK method is currently blocked at my server as I composed HTTP request in Charles (great software) and forwarded it to a very simple php script. The script hasn't been fired since my Apache blocks http with LOCK method.

At this moment I have asked my administrator to list Limit section in httpd.conf.
I will ask him to add all methods I need.

To all who had a problem with Office. Office requires LOCK method. Office will not open document
in read-write mode without LOCK.

Thank you Hywan.

**Comment by km-77** [comment]
I would like to write that I have finally managed to open Microsoft Word document in edit mode.
I have unlocked all methods in .htaccess:
```
<Limit GET PUT POST DELETE PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK>
order allow,deny
allow from all
</Limit>
```

I put .htaccess in sabre folder (the folder that contains server.php file)

Everything works now fine!
