### ISSUE TITLE
GAB [Global Address Book] and Z-Push

### ISSUE THREAD

**Issue by halilemreozen** [fruux/sabre-dav#958]
Hi Guys,

I do not know if I am in the right place to ask but the z-push forum doesn't approve my account to open a new thread and I need an advice from who experienced person.

I just assigned to a project wich its use sabre-dav with z-push and its works well except global address book.

Our Z-Push carddav/config.php contains :

define('CARDDAV_SERVER', 'IPADRESS');
define('CARDDAV_PORT', '80');

define('CARDDAV_GAL_PATH', '/dav.php/gab/');
or
define('CARDDAV_GAL_PATH', '/dav/gab/');

and our Z-Push version is "2.3.5".

But still, we can't see the global address book contacts on the phone.

I'm open to all suggestions.

**Comment by evert** [comment]
Sorry, this is not the right place to report this. I have no idea how to go about fixing z-push as I've never used it.
