### ISSUE TITLE
Retrieve custom properties

### ISSUE THREAD

**Issue by JosephP91** [fruux/sabre-dav#968]
Hi,
I would like to know how to structure the XML PROPFIND query to fetch custom properties such the addressbook description, stored in the addressbook table.

**Comment by evert** [comment]
This is the relevant section in the WebDAV RFC for structuring PROPFIND requests:

* https://tools.ietf.org/html/rfc4918#section-9.1.3

This is the relevant section in the CardDAV rfs for the addressbook-description property:

* https://tools.ietf.org/html/rfc6352#section-6.2.1
