### ISSUE TITLE
IMip Handler doesn't work in SabreDAV 1.8

### ISSUE THREAD

**Issue by KrasikovA** [fruux/sabre-dav#971]
Hello! I was forced to use old version of SabreDAV(1.8). I configured IMip handler like it was provided in manual. I'm pretty sure, that php mail()  function works fine on my server. 
I use Calendar mac app version 9. Is SabreDAV 1.8 too old for it?

**Comment by evert** [comment]
Hi @KrasikovA , sabre/dav 1.8 is out of support. This literally means that we're simply not providing support for it. Sorry about that, but we have to draw the line somewhere.
