### ISSUE TITLE
Question: Allowed memory size 

### ISSUE THREAD

**Issue by gasparyanyur** [fruux/sabre-dav#975]
I am using sabre\dav and sabre\client to send large files to another host, but the response I have got the following error

> Allowed memory size of 134217728 bytes exhausted (tried to allocate 31860068 bytes)

I have investigated and have found that the error comes from `Sabre\HTTP\Client:499`

```
$headerBlob = substr($response, 0, $curlInfo['header_size']);
$responseBody = substr($response, $curlInfo['header_size']) ?: null;
```

**Comment by staabm** [comment]
this issue should be opened at https://github.com/fruux/sabre-http

**Comment by gasparyanyur** [comment]
Yes. But the issue is associated with file transferings

**Comment by staabm** [comment]
so whats your exact use case. do you post large files? how exactly do you send the payload?

**Comment by gasparyanyur** [comment]
My project based on Laravel ,so I am using `putContent()` function to put the content of file via url

**Comment by staabm** [comment]
could you create  a small example which reproduces your issue?

**Comment by gasparyanyur** [comment]
For put, read or update streams I am using FileSytyem. Here is the code which need to send files to another host

```
$files = $old_storage->files()->withTrashed()->get();

        try {
            foreach( $files as $file ) {
                try {
                    $stream = $file->readStream();
                    $file->setStorage( $storage->id );
                    $file->storage()->getDriver()->putStream( $file->getRealDestination(), $stream );
                    $file->putStream( $file->getRealDestination(), $stream );
                } catch( \Exception $e ) {
                    $file->setStorage( $storage->id );
                }
                $file->save();
            }

            $old_storage->is_active = 0;
            $old_storage->status    = DiskStorage::STATUS_OK;
            $old_storage->save();
            $storage->is_active = 1;
            $storage->status    = DiskStorage::STATUS_OK;
            $storage->save();
```

**Comment by staabm** [comment]
I dont know laravel enough to help you with laravel specific code. you should reduce your failing example to something more concrete and related to sabre-dav/http.

at best you could hand us some runnable code which shows/reproduces the problem

**Comment by staabm** [comment]
which exact version of sabre-dav and sabre-http do you use?

**Comment by gasparyanyur** [comment]
Here is a functions which calling 
 ```
public function read($path)
    {
        $location = "/abc/13/Storage/Files/6/61bad8ee7dcd736a966d09fbb7839847.mp4"

        try {
            $response = $this->client->request('GET', $location);

            if ($response['statusCode'] !== 200) {
                return false;
            }

            return array_merge([
                'contents' => $response['body'],
                'timestamp' => strtotime(is_array($response['headers']['last-modified'])
                    ? current($response['headers']['last-modified'])
                    : $response['headers']['last-modified']),
                'path' => $path,
            ], Util::map($response['headers'], static::$resultMap));
        } catch (Exception $e) {
            return false;
        }
    }
// Sabre\DAV\Client
function request($method, $url = '', $body = null, array $headers = []) {

        $url = $this->getAbsoluteUrl($url);

        $response = $this->send(new HTTP\Request($method, $url, $headers, $body));
        return [
            'body'       => $response->getBodyAsString(),
            'statusCode' => (int)$response->getStatus(),
            'headers'    => array_change_key_case($response->getHeaders()),
        ];

    }
```

After sending get method I am getting the error 
>Allowed memory size of 134217728 bytes exhausted (tried to allocate 31860068 bytes)  Client.php line 498:

**Comment by staabm** [comment]
nice, I guess we can work with it.

I will close this issue here as it needs to be handled in the http-client.

we will continue the analysis at https://github.com/fruux/sabre-http/issues/82
