### ISSUE TITLE
Sabre\DAVACL\PrincipalBackend\PDO interface for deleting principals

### ISSUE THREAD

**Issue by stevewi** [fruux/sabre-dav#976]
I have a set of command-line utilities to do maintenance on a SabreDAV PDO database.  I wrote them for 3.1.4 and now want to update them for 3.2.2.  I used PDO to directly write entries to the database for the various objects that need to be added/updated/deleted.

I'm taking baby steps in converting these utilities to use the SabreDAV PDO objects to do this.  I have the Principal object converted.  However, I can't seem to find any available interface to delete princpals entries using Sabre\DAVACL\PrincipalBackend\PDO.

That being said, is there such an interface?  If so, where might I find it?

If not, can anyone give me some tips on how I might extend Sabre\DAVACL\PrincipalBackend\PDO to provide such an interface?

Thanks in advance...

**Comment by christophdb** [comment]
Hi stevewi,

> SabreDAV does not provide an administrative interface to add users. While this may happen in the future, for now SabreDAV is mostly intended for developers. Adding new users is done directly on the database. In order to allow a user to log in, add them to the users table. You must also add them to the principals table to enable calendar access. – Evert Pot auf http://sabre.io/dav/caldav/

So I am sorry, but sabredav will not help you with the administration of the users and the principals. 
You have to change or administrate the users with mysql requests directly. 

So if you want to delete a user from the sabredav database you should delete the following

1. entry in principals table
2. entry in users table
3. delete all objects that are related to that principal

Does that help you or did I miss something?
Best regards
Christoph

**Comment by stevewi** [comment]
Thanks Christoph...  I sorta figured this out on my own after seeing Evert's post about putting development of sabredav on the shelf.  I have a tool that administers users/principals that includes a mechanism for deleting principals.  I'm in the middle of doing some re-factoring with it but the functionality will remain the same...  Hopefully, this effort will lead to a minimal  Sabre\DAVACL\UsersBackend\* set of objects for managing the users table in a sabredav way.

Evert posted on the now-defunct sabredav Google group that there was no CardDAV/CalDAV standard for managing users so that's why sabredav doesn't have such a mechanism.  Since sabredav is going to be static for awhile, it doesn't seem likely that such a standard mechanism for managing users will appear anytime soon so my development effort will probably be protected for awhile.

Just FYI, sabredav supports SQLite as well (which is what I use because of my modest needs) so MySQL isn't necessary.  The tools/system I have on top of sabredav is heavily oriented toward Apple Calendar (née iCal) because that is the calendaring system my customers use.

Thanks again for your help...
