### ISSUE TITLE
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in [...] PDO.php on line 478

### ISSUE THREAD

**Issue by c0d3z3r0** [fruux/sabre-dav#978]
- Debian stretch
- nginx 1.10.3
- php 7.0.19-1
- sabre-dav 3.2.2
- sqlite3 database

sabre-dav[8363]: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/sabre-dav/vendor/sabre/dav/lib/CalDAV/Backend/PDO.php on line 478

It is always line 478: $stmt->execute([$calendarId, $objectUri]);

I had no such problems with PHP 5 before.

I can't create or change any calendar objects. After restarting php7.0-fpm everything works fine again for some hours or days. Then it stops working and I have to restart php7.0-fpm.
I am not sure if this is a sabre-dav or php related problem but since this only happens with sabre-dav but not with any other php application on this server I think it is a sabre problem.

Increasing the execution timeout as suggested below didn't change anything. After restarting php the request only takes some seconds so it should never hit the timeout anyway.

Maybe the db gets locked but not unlocked again?

**Comment by gasparyanyur** [comment]
Its means that you request is very slow, so you need to increase you max_execution time
`max_execution_time = 900` or `ini_set('max_execution_time', 900);`
or change driver of request

**Comment by c0d3z3r0** [comment]
@gasparyanyur Thanks for your answer. I forgot to mention that increasing the timeout doesn't change anything. Anyway, after restarting php the request only takes some seconds so it should _never_ hit the timeout.

**Comment by gasparyanyur** [comment]
I think the cause of the  execution_time error can be several.
1) Slow external requests 
2)Infinite cycles and recursion

**Comment by staabm** [comment]
please increase your time-limit and use a profiler, like blackfire.io or similar and measure what exactly is eating all your time in your use-case.

**Comment by c0d3z3r0** [comment]
I did some more tests and again increased the timeout to 90 secs. The problem didn't appear since three days. I have no clue why this didn't work before but the problem seems to be solved.

**Comment by pkcompaddicts** [comment]
Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\phpMyAdmin\libraries\ErrorHandler.php on line 162

Please tell me solution ??

**Comment by DeepDiver1975** [comment]
> Please tell me solution ??

https://github.com/sabre-io/dav/issues/978#issuecomment-311987612

**Comment by jinyiwoo** [comment]
vi  /etc/php.ini
max_execution_time = 360      ; Maximum execution time of each script, in seconds (I CHANGED THIS VALUE)
max_input_time = 120          ; Maximum amount of time each script may spend parsing request data
;max_input_nesting_level = 64 ; Maximum input variable nesting level
memory_limit = 128M           ; Maximum amount of memory a script may consume (128MB

**Comment by pkcompaddicts** [comment]
thank you

**Comment by pranab155** [comment]
Still increasing the execution time to max_execution_time = 1800 in php.in and restart the apache web server on which matomo with php is running ...still not working
