### ISSUE TITLE
iCal: The server specified an invalid calendar home.

### ISSUE THREAD

**Issue by jschultze** [fruux/sabre-dav#983]
When trying to connect to a sabre/dav server (in this case CalDAV) iCal prompts the following error:

**The server specified an invalid calendar home.**

This error occurs:
- sabre/dav 3.2.2 in own Symfony-project
- Baïkal 0.5.0

I tried to monitor the communication with Charles and mitmproxy, but I'm just starting to work with CalDAV and sabre/dav, so I don't know which information will be helpful - if somebody tells me which capture of mitmproxy might help, I'm glad to provide.

**Comment by evert** [comment]
First thing I would try is adding the browser plugin and see if you can browse around and find the calendar-home yourself, without errors.

**Comment by jschultze** [comment]
Yes, browsing works for both systems. I can also work with single calendars in Lightning (also in both systems).

**Comment by jschultze** [comment]
I'm working with: iCal (9.0) / macOS (10.12.5)

**Comment by jschultze** [comment]
Just checked: accessing the Baïkal installation from iOS seems to work perfectly. So, maybe this is a problem with changed requirements because of a new iCal Version on macOS?

**Comment by jschultze** [comment]
I think I found my error. I was trying to access the calendars via

http://localhost/caldav/

... thinking that iCal would add the needed paths to /calendars, /principals, ... by itself.

Turns out, I had to use

http://localhost/caldav/principals/<username>

to configure the account in iCal.
