### ISSUE TITLE
Why does CalDAV Backend PDO class does not allow to change the uri of a calendar?

### ISSUE THREAD

**Issue by christophdb** [fruux/sabre-dav#985]
Hi everybody,
I am using the PDO Backend Class of caldav to update my calendars within my own php backend. Here is the file I am refering to:
https://github.com/fruux/sabre-dav/blob/6fda658c4a57b4a6aaf514d7d2beb1894ce4ad61/lib/CalDAV/Backend/PDO.php

I am using the function **createCalendar**  which uses the **propertyMap** to define which changes are allowed with properties.

**propertyMap** is defined like that:
```
public $propertyMap = [
        '{DAV:}displayname'                                   => 'displayname',
        '{urn:ietf:params:xml:ns:caldav}calendar-description' => 'description',
        '{urn:ietf:params:xml:ns:caldav}calendar-timezone'    => 'timezone',
        '{http://apple.com/ns/ical/}calendar-order'           => 'calendarorder',
        '{http://apple.com/ns/ical/}calendar-color'           => 'calendarcolor',
    ];

```
My Question is now: Why is it not allowed to change the uri of a calendar? 
Of cause I can change the propertyMap and add:
'uri' => 'uri'
```
public $propertyMap = [
        '{DAV:}displayname'                                   => 'displayname',
        '{urn:ietf:params:xml:ns:caldav}calendar-description' => 'description',
        '{urn:ietf:params:xml:ns:caldav}calendar-timezone'    => 'timezone',
        '{http://apple.com/ns/ical/}calendar-order'           => 'calendarorder',
        '{http://apple.com/ns/ical/}calendar-color'           => 'calendarcolor',
        'uri'                                             => 'uri',
    ];

```

Is there any reason why this is not allowed by default? In my opinion it does not make sense to update the displayname of a calendar without changing the uri.

Imagine that I create a calendar with _uri=private_ and _displayname=Private Stuff_. 
If I then change _Private Stuff_ to _Public Stuff_, I should also update the uri from _private_ to _public_. Makes sense, right?

I would appreciate any comment to that.
Best regards
Christoph

**Comment by evert** [comment]
Hey Christoph,

I think that breaking existing urls for entities is kind of bad design for any api. A lot of clients will index and store things based on urls. The url is the true primary key.

It's technically not impossible to allow clients to change the url with a HTTP MOVE request, but I would strongly advise against this. Most other CalDAV servers disallow this, and I can imagine clients not being happy with that type of change.

If you're worried about giving your calendar a uri that's later on no longer accurate, maybe just give it a more generic or abstract uri. Most CalDAV clients will just use a UUID (or let the server decide).

Evert

**Comment by christophdb** [comment]
Thanks for the answer...
