### ISSUE TITLE
adding new item with 2Do App gives back error: "The value type (DATE or DATE-TIME) must be identical for DUE and DTSTART"

### ISSUE THREAD

**Issue by Zephyr82** [fruux/sabre-dav#986]
Hello Sabre.io team,

I very much love 2Do whether on iOS or Mac OS. I used it with owncloud 8.1 for a longer time and now had the time to upgrade to nextcloud 12. But unfortunately there now are errors for every new item I try to add in 2Do (does not depend on the platform, the error happens on Mac OS X and on iOS) in the Nextcloud Logging resulting in not being synced to Nextcloud.

You may follow the following steps to reproduce the error:

1) make a clean install of Nextcloud 12.0.0
2) install the Nextcloud App "Tasks 0.9.5" via the apps Interface inside Nextcloud
3) configure the sync to Nextcloud inside of 2Do with the following settings:
Account type: user define CalDav Server
user name: <username from Nextcloud>
password: <password for user from Nextcloud>
server address: <url of Nextcloud server>
path: </remote.php/caldav/principals/user name>

4) try to add a item in 2Do and look inside the 2Do Log, there I for example get the following results:
[D] 2017/07/24 22:35:09:334: [SYNC] Connect and perform sync, current status: 0
[D] 2017/07/24 22:35:09:334: Logged out of CalDAV: 0
[D] 2017/07/24 22:35:09:335: [SYNC] Syncing Status Changed, informing: DELEGATE (Connecting - Result: Succes)
[I] 2017/07/24 22:35:09:350: Updating domain URL: https://example.com:443, User Principal: /remote.php/caldav/principals/<username>/, Calendar Home: /remote.php/caldav/calendars/<username>/
[D] 2017/07/24 22:35:09:351: [SYNC] Connected successfully, requesting sync
[D] 2017/07/24 22:35:09:352: [SYNC] Syncing Status Changed, informing: TD_SYNC_STARTED (Syncing - Result: Succes)
[I] 2017/07/24 22:35:09:352: [SYNC NOTICE] Sync Started
[D] 2017/07/24 22:35:09:352: [SYNC] CalDAV sync started
[D] 2017/07/24 22:35:09:353: 

[START SYNC]
[D] 2017/07/24 22:35:09:353: [SYNC] CalDAV Sync Started

[E] ---> 2017/07/24 22:35:13:275: ...Error adding CalDAV Task: Error Domain=com.guidedways.2Do.CalDAV Code=415 "unsupported media type" UserInfo={NSLocalizedDescription=unsupported media type}

[E] ---> 2017/07/24 22:35:13:275: ...Error syncing tasks for calendar: Error Domain=2DoApp Code=415 "Unable to add the following task to the server: Einladung Arbeitseinsatz für 15.7. verschicken

unsupported media type" UserInfo={NSLocalizedDescription=Unable to add the following task to the server: Einladung Arbeitseinsatz für 15.7. verschicken

And inside of Nextcloud I get the following error messages:
Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in iCalendar: The value type (DATE or DATE-TIME) must be identical for DUE and DTSTART
/var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 802: Sabre\CalDAV\Plugin->validateICalendar('BEGIN VCALENDAR...', 'calendars/1316b...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), true)
[internal function] Sabre\CalDAV\Plugin->beforeCreateFile('calendars/1316b...', 'BEGIN VCALENDAR...', Object(OCA\DAV\CalDAV\Calendar), false)
/var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1093: Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)
/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('calendars/1316b...', Resource id #20, NULL)
[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/owncloud/apps/dav/appinfo/v1/caldav.php - line 91: Sabre\DAV\Server->exec()
/var/www/owncloud/remote.php - line 162: require_once('/var/www/ownclo...')
{main}

The version of SabreDav installed with this version of Nextcloud ist 3.2.2 according to the CHANGELOG.md in /3rdparty/sabre/dav/CHANGELOG.md

The version of 2Do I am using on MacOS X is 2.3.7 build 49130.

I cannot say if the error ist on the side of SabreDav / Nextcloud or the side of 2Do according to the specification. But may be  you could get a look into the problem?

Thank you in advance
Karsten Bessner

**Comment by evert** [comment]
Please open a ticket at either the owncloid or 2do project

**Comment by Zephyr82** [comment]
I'm sorry to comment again... But do you really think that i.e. this line is not related to Sabre/dav?
`/var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 802: Sabre\CalDAV\Plugin->validateICalendar('BEGIN VCALENDAR...', 'calendars/1316b...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), true)`

**Comment by evert** [comment]
Owncloud is a user of sabre/dav. Any support requests should go there. Yes, there is a possibility that there's an underlying bug related to sabre/dav, but if there is, I rather hear that from the owncloud folks, because I'm simply not interested in being owncloud's level 1 support.

**Comment by Zephyr82** [comment]
Jeah, you're kind of right. I could have taken a deeper look into the problem. Now I did exactly that as I did not get an answer from 2Do or the Nextcloud project. 

I traced the problem down to the function `validate($options = 0)` in the file `sabre/vobject/lib/Component/VTodo.php`.

The vtodo object, 2Do ist trying to sync, has a DTSTART property with the value type of DATE. And a DUE property which is of type DATE-TIME. As the function tries to assure DTSTART and DUE have the same value type, the `validate($options = 0)` gives back an error. 
As I read RFC 5545 on page 95 to 97 there is no definitive need that DUE and DTSTART have the same value type, because section "3.8.2.3. Date-Time Due" says: 

> Value Type:  The default value type is DATE-TIME.  **The value type can
      be set to a DATE value type.**

And even DTSTART does not necessarily has to be of value type DATE-TIME. RFC 5545 says on page 96, section "3.8.2.4.  Date-Time Start":

> Value Type:  The default value type is DATE-TIME.  The time value
      MUST be one of the forms defined for the DATE-TIME value type.
      **The value type can be set to a DATE value type.**

Or did I get something wrong? Am I something missing?

Kind regards
Zephyr

**Comment by evert** [comment]
From RFC5545 (https://tools.ietf.org/html/rfc5545#section-3.8.2.3)


> For cases where this property
>       is specified in a "VTODO" calendar component that also specifies a
>       "DTSTART" property, the value type of this property MUST be the
>       same as the "DTSTART" property, and the value of this property

**Comment by Zephyr82** [comment]
Oh, you're right. Now I do feel completely dumb. 
Thank you very much for taking the time for responding and to refer to the correct point in the RFC.

Kind regards
Zephyr

**Comment by evert** [comment]
No worries! I appreciate you took the time to dive deeper. Sorry for all my brief answers.

**Comment by deluxestyle** [comment]
@Zephyr82 have you contacted the 2do app developer? I'll get the same error

**Comment by Zephyr82** [comment]
@deluxestyle I did send them the issue. But I did never get an answer. Even after asking a second time. Although I never pointed them to this particular post here. May be you could write them too?

**Comment by deluxestyle** [comment]
@Zephyr82 good idea. I will ask him and send him the link to this post

**Comment by deluxestyle** [comment]
@Zephyr82 I'll got already an reply

> Sadly nextcloud is one of those CalDAV servers 2Do does not fully support (or rather, nextcloud has a half-hearted, obsolete implementation taken from an older version of Sabre). Given it's got a poorly implemented CalDAV server, we're currently not endorsing it nor able to provide any support as there are various known issues with nextcloud as we speak. I apologize for this unhelpful response, but we've in the past spent several man-hours trying to resolve this with little to no luck :) We're instead asking our users to provide us with any tips if they're able to get it to work

**Comment by blackandcold** [comment]
I ran into the same problem. 

> Sabre\DAV\Exception\UnsupportedMediaType: Validation error in iCalendar: The value type (DATE or DATE-TIME) must be identical for DUE and DTSTART

2DO app has the option to not sync due dates/times. This is sad to no sync those values but imho better than nothing
