### ISSUE TITLE
Problem with beforeMethod:PUT

### ISSUE THREAD

**Issue by JosephP91** [fruux/sabre-dav#996]
Hi everybody,
I'm having a problem with beforeMethod:PUT handler. When the server receives a PUT request I need to do some pre processing that I have implemented in beforeMethod:PUT handler. 
The problem is that when that handler finishes its execution, the server responds me with:

```
<d:error>
      <s:sabredav-version>3.2.2</s:sabredav-version>
      <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
      <s:message>This resource only supports valid vCard or jCard data. Parse error: End of document reached prematurely</s:message>
 </d:error>
```

This is my beforeMethod:PUT handler:

```
function beforePutHandler(RequestInterface $request, ResponseInterface $response) {
        if (!$this->authenticate($request, $response)) {
            return false;
        }
        if ($this->isAddressbookSyncActive($response)) {
            return false;
        }
        $auth = $this->getAuthFromHeaders($request);
        $details = $this->getInfoFromPath($request);
        $this->logger->writeInfo("Context is $details[context].");
        if ($details['context'] == 'addressbooks') {
            $addressbook = $this->getAddressbookInfo($details['object'], $auth['username'], $response);
            if (!$addressbook) {
                return true;
            }
            $api = $this->getAPIProvider($addressbook['provider']);
            if (!$api) {
                return true;
            }
            $contact = $request->getBodyAsString();
            if ($request->hasHeader('If-Match')) {
                $this->logger->writeInfo("Got modify request from $auth[username] for addressbook $details[object]");
                $this->logger->writeInfo("Requesting update to synchronizer.");
                $response = $api->updateContact($details['object'], $contact);
            } else {
                $this->logger->writeInfo("Got creation request from $auth[username] for addressbook $details[object]");
                $response = $api->createContact($details['object'], $contact);
            }
            $this->logger->writeInfo(json_encode($response));
        }
        return true;
    }
```

Thank you!

**Comment by evert** [comment]
Hi Joseph,

Request bodies can only be read once. So once you read it, the body is gone. You can however repopulate the body with `$request->setBody($body);` afterwards.

**Comment by JosephP91** [comment]
Thank you @evert 
Now the vcard is created, but is empty. Should I set something else?

**Comment by evert** [comment]
You have to make sure that `$body` actually contains your request body ;)

**Comment by JosephP91** [comment]
Yes, ```$body``` contains my request body :)

**Comment by evert** [comment]
That should be all you need then. I would try and do a bit more debugging to figure out where the information is lost. The CardDAV plugin uses 2 different events (beforeWriteContent, beforeCreateFile) to do something similar.

**Comment by JosephP91** [comment]
Ok, I will do another debugging session and I will let you know here. Thank you!

**Comment by JosephP91** [comment]
Well @evert  , nothing to do. Sabre keeps creating file with no contents. Any suggestions?

**Comment by JosephP91** [comment]
Updating sabre from 3.2.0 to 3.2.2 solves the issue. Don't know why, but it works.
